'use strict';

const {FastBrowserUiRouteRunner}=require('./fast_browser_ui_route_runner');
const {surfaceItems}=require('./topic_transition_runner');
const {summarizeRuns}=require('./head_keyword_next_runner');
const {classifyTopic,classifySurface,transitionEvidence}=require('./topic_route_runner');

const sleep=ms=>new Promise(resolve=>setTimeout(resolve,Math.max(0,Number(ms)||0)));
const GENERIC_TOPIC_KEYS=new Set(['knowledge','society','lifestyle (sociology)','entertainment','politics','business']);
const NOISE_KEYS=new Set(['https','http','www','com','the','and','for','with','from','this','that','video','youtube','channel','today','latest','tai','cua','cho','voi','trong','tren','nay','moi','mot','nhung','cac','duoc','khong','nguoi','lam','the','nao','is_from_webapp','sender_device']);

function clean(value){return String(value??'').normalize('NFKC').replace(/\s+/g,' ').trim();}
function fold(value){return clean(value).toLowerCase().normalize('NFD').replace(/\p{M}+/gu,'').replace(/đ/g,'d');}
function uniq(values){return [...new Set((values||[]).map(clean).filter(Boolean))];}
function apiOf(node){return node?.youtubeApi||node||{};}
function median(values){const xs=(values||[]).map(Number).filter(Number.isFinite).sort((a,b)=>a-b);if(!xs.length)return 0;const m=Math.floor(xs.length/2);return xs.length%2?xs[m]:(xs[m-1]+xs[m])/2;}
function meaningfulKey(value){const x=fold(value);if(!x||x.length<3||x.length>72||NOISE_KEYS.has(x))return false;if(/^https?:|www\.|accounts\.|google\.|youtube\./.test(x))return false;if(/^\d+(?:[.,]\d+)?$/.test(x))return false;return /\p{L}/u.test(x);}
function topicFamily(node){const api=apiOf(node),topics=uniq(api.topicLabels),category=String(api.categoryId||'unknown');return topics.length?topics.map(x=>`topic:${fold(x)}`):[`category:${category}`];}
function viewStats(node){const api=apiOf(node),views=Number(api.statistics?.viewCount||0),vph=Number(node?.viewsPerHour??api.viewsPerHour??0);return {views:Number.isFinite(views)?views:0,viewsPerHour:Number.isFinite(vph)?vph:0};}
function videoKeyRows(node){
  const api=apiOf(node),out=[];
  const push=(value,source,videoLevel=true)=>{const display=clean(value),key=fold(display);if(!meaningfulKey(display))return;out.push({key,display,source,videoLevel});};
  for(const x of api.tags||[])push(x,'tag',true);
  for(const x of api.topicLabels||[])push(x,'video_topic',true);
  for(const row of api.keywords||[]){const term=row?.term||row,sources=Array.isArray(row?.sources)?row.sources:[],videoLevel=!sources.length||sources.some(s=>['tag','tag_token','video_topic','video_topic_token','title','description'].includes(String(s)));push(term,'derived_keyword',videoLevel);}
  for(const x of api.channel?.topicLabels||[])push(x,'channel_topic',false);
  const seen=new Set();return out.filter(row=>{const id=`${row.key}:${row.source}:${row.videoLevel}`;if(seen.has(id))return false;seen.add(id);return true;});
}
function topicDistance(a,b){const aa=new Set(topicFamily(a)),bb=new Set(topicFamily(b));let common=0;for(const x of aa)if(bb.has(x))common++;const union=new Set([...aa,...bb]).size||1;const categoryA=String(apiOf(a).categoryId||''),categoryB=String(apiOf(b).categoryId||'');const jaccard=common/union;return Math.min(1,(1-jaccard)*0.75+(categoryA&&categoryB&&categoryA!==categoryB?0.25:0));}
function factorKeys(factors){return uniq([...(factors?.sharedTags||[]),...(factors?.sharedKeywords||[]),...(factors?.sharedTopics||[]),...(factors?.sharedTitleTokens||[])]).filter(meaningfulKey);}
function specificTopicBonus(node){const topics=uniq(apiOf(node).topicLabels).map(fold).filter(x=>!GENERIC_TOPIC_KEYS.has(x));return Math.min(3,topics.length)*0.8;}

class ObservedKeyGraph{
  constructor(){this.keys=new Map();this.edges=[];this.videoIds=new Set();}
  row(key,display){let row=this.keys.get(key);if(!row){row={key,display,videoIds:new Set(),topicFamilies:new Set(),surfaces:new Set(),sourceTypes:new Set(),videoLevelCount:0,occurrences:0,crossTopicEdges:0,views:[],viewsPerHour:[],provenance:[]};this.keys.set(key,row);}return row;}
  addNode(node,{surface='unknown',reason='observe',trackVideoId=null}={}){
    const api=apiOf(node),videoId=String(node?.videoId||api.videoId||'');if(!videoId||videoId===String(trackVideoId||''))return;
    this.videoIds.add(videoId);const stats=viewStats(node),families=topicFamily(node);
    for(const k of videoKeyRows(node)){const row=this.row(k.key,k.display);row.videoIds.add(videoId);for(const f of families)row.topicFamilies.add(f);row.surfaces.add(surface);row.sourceTypes.add(k.source);row.videoLevelCount+=k.videoLevel?1:0;row.occurrences++;row.views.push(stats.views);row.viewsPerHour.push(stats.viewsPerHour);if(row.provenance.length<16)row.provenance.push({videoId,title:clean(api.title||node?.title).slice(0,140),surface,reason,source:k.source,videoLevel:k.videoLevel});}
  }
  addObservedEdge(source,candidate,{surface='related',rank=null,reason='observe',trackVideoId=null}={}){
    const sourceId=String(source?.videoId||apiOf(source).videoId||''),candidateId=String(candidate?.videoId||apiOf(candidate).videoId||'');if(!sourceId||!candidateId||candidateId===String(trackVideoId||''))return;
    const a=new Map(videoKeyRows(source).filter(x=>x.videoLevel).map(x=>[x.key,x])),b=new Map(videoKeyRows(candidate).filter(x=>x.videoLevel).map(x=>[x.key,x])),shared=[];
    for(const [key,row] of a)if(b.has(key)&&meaningfulKey(key))shared.push(row.display||b.get(key)?.display||key);
    if(!shared.length)return;const distance=topicDistance(source,candidate),crossTopic=distance>=0.35;
    for(const keyDisplay of shared){const key=fold(keyDisplay),row=this.keys.get(key);if(row&&crossTopic)row.crossTopicEdges++;}
    if(this.edges.length<1200)this.edges.push({sourceVideoId:sourceId,candidateVideoId:candidateId,surface,rank:Number(rank)||null,sharedKeys:uniq(shared).slice(0,24),topicDistance:Number(distance.toFixed(3)),crossTopic,reason});
  }
  observe(obs,{reason='observe',trackVideoId=null}={}){
    const current=obs?.currentVideo||null;if(current)this.addNode(current,{surface:'current_video',reason,trackVideoId});
    for(const row of surfaceItems(obs)){this.addNode(row,{surface:row.surface||'unknown',reason,trackVideoId});if(current)this.addObservedEdge(current,row,{surface:row.surface,rank:row.position,reason,trackVideoId});}
  }
  score(row){const videoCount=row.videoIds.size,topicDiversity=row.topicFamilies.size,medianViews=median(row.views),medianViewsPerHour=median(row.viewsPerHour),multiword=/\s/.test(row.display)?0.45:0;return Number((Math.log1p(videoCount)*1.25+Math.log1p(topicDiversity)*1.8+Math.log1p(row.crossTopicEdges)*2.6+Math.log1p(medianViews)/6+Math.log1p(medianViewsPerHour)/4+multiword).toFixed(3));}
  ranked({limit=30}={}){return [...this.keys.values()].map(row=>({key:row.display,normalizedKey:row.key,videoCount:row.videoIds.size,topicDiversity:row.topicFamilies.size,crossTopicEdges:row.crossTopicEdges,medianViews:Math.round(median(row.views)),medianViewsPerHour:Number(median(row.viewsPerHour).toFixed(2)),surfaces:[...row.surfaces],sourceTypes:[...row.sourceTypes],videoLevelCount:row.videoLevelCount,demandProxy:this.score(row),demandInterpretation:'observed_video_statistics_proxy_not_query_search_volume',provenance:row.provenance.slice(0,8)})).sort((a,b)=>b.demandProxy-a.demandProxy||b.crossTopicEdges-a.crossTopicEdges||b.videoCount-a.videoCount).slice(0,limit);}
  searchCandidates({limit=10,headQueries=[],targetTopic=null,targetTitle=null,trackVideoId=null}={}){const heads=new Set((headQueries||[]).map(fold)),tt=fold(targetTopic),title=fold(targetTitle),id=fold(trackVideoId);return this.ranked({limit:120}).filter(row=>row.videoCount>=2&&row.topicDiversity>=2&&row.crossTopicEdges>=1&&row.videoLevelCount>=2).filter(row=>{const k=fold(row.key);if(heads.has(k)||k===tt||k===id)return false;if(title&&(k===title||(k.length>=24&&title.includes(k))))return false;return true;}).slice(0,limit);}
  report(){return {uniqueObservedVideos:this.videoIds.size,keyCount:this.keys.size,topKeys:this.ranked({limit:40}),crossTopicEdges:this.edges.filter(x=>x.crossTopic).slice(0,300)};}
}

function chooseDiversifyingBridge(rows,source,visited,keyGraph){
  const scored=[];
  for(const row of rows||[]){if(!row?.videoId||row.semanticTitle===false||row.isRadio===true||!String(row.path||'').startsWith('/watch')||visited.has(String(row.videoId)))continue;const evidence=transitionEvidence(source,row),f=evidence.publicFactors||{},keys=factorKeys(f);if(!keys.length)continue;const tagCount=(f.sharedTags||[]).filter(meaningfulKey).length,keywordCount=(f.sharedKeywords||[]).filter(meaningfulKey).length,topicCount=(f.sharedTopics||[]).filter(meaningfulKey).length,titleCount=(f.sharedTitleTokens||[]).filter(meaningfulKey).length,bridgeStrength=Math.min(2,tagCount)*4+Math.min(3,keywordCount)*1.8+Math.min(2,topicCount)*4+Math.min(3,titleCount)*0.45,distance=topicDistance(source,row),stats=viewStats(row),keyDemand=Math.max(0,...keys.map(key=>keyGraph?.keys?.get(fold(key))).filter(Boolean).map(x=>keyGraph.score(x))),score=bridgeStrength+distance*5+specificTopicBonus(row)+Math.min(3,Math.log10(1+stats.viewsPerHour))*0.9+Math.min(3,keyDemand)*0.35-Number(row.position||99)*0.02-(f.sameChannel?12:0);scored.push({row,evidence,keys,bridgeStrength,topicDistance:distance,keyDemand,score:Number(score.toFixed(3)),sameChannel:f.sameChannel===true});}
  const crossChannel=scored.filter(x=>!x.sameChannel),pool=crossChannel.length?crossChannel:scored;if(!pool.length)return null;pool.sort((a,b)=>b.score-a.score||Number(a.row.position||9999)-Number(b.row.position||9999));return pool[0];
}

function homeDelta(previous,current){const prevIds=new Set((previous?.candidates||[]).map(x=>String(x?.candidate?.videoId||'')).filter(Boolean)),curIds=new Set((current?.candidates||[]).map(x=>String(x?.candidate?.videoId||'')).filter(Boolean)),added=[...curIds].filter(x=>!prevIds.has(x)),removed=[...prevIds].filter(x=>!curIds.has(x)),intersection=[...curIds].filter(x=>prevIds.has(x)).length,union=new Set([...prevIds,...curIds]).size||1;return {addedVideoIds:added.slice(0,80),removedVideoIds:removed.slice(0,80),overlapCount:intersection,jaccard:Number((intersection/union).toFixed(3)),targetAppeared:current?.targetExposure?.seen===true,targetRank:current?.targetExposure?.rank||null};}
function topicIdentity(topic){return fold([topic?.categoryId||'',topic?.primaryTopic||'',...(topic?.videoTopicLabels||[])].join('|'));}

class KeyGraphRouteRunner extends FastBrowserUiRouteRunner{
  constructor(config,client=null,options={}){super(config,client,options);this.keyGraph=new ObservedKeyGraph();this.bridgeKeyRuns=[];this.homeTopicCheckpoints=[];this.lastHomeCheckpointTopic=null;this.lastHomeScan=null;this.expansionQueries=new Set();}
  async observe(reason='observe'){const obs=await super.observe(reason);this.keyGraph.observe(obs,{reason,trackVideoId:this.config.trackVideoId});return obs;}
  chooseNext(scan,branchMode,visited){if(branchMode==='source_bridge'||branchMode==='metadata_bridge'){const source=scan?.lastObs?.currentVideo||scan?.source||null,choice=chooseDiversifyingBridge(scan.rawRows,source,visited,this.keyGraph);if(choice)return {candidate:choice.row,selectionFactors:choice.evidence.publicFactors,transitionEvidence:{...choice.evidence,diversification:{score:choice.score,topicDistance:Number(choice.topicDistance.toFixed(3)),keyDemand:Number(choice.keyDemand.toFixed(3)),bridgeKeys:choice.keys,sameChannel:choice.sameChannel,crossChannelPreferred:true}},reason:'cross_channel_key_bridge_target_blind'};}return super.chooseNext(scan,branchMode,visited);}
  async restoreAfterHome(original,{reason='home_checkpoint_restore'}={}){if(original?.pageType==='home')return true;for(let attempt=1;attempt<=2;attempt++){await this.browserCommand('back');const obs=await this.waitFor(o=>o.route?.pageType===original.pageType&&(!original.videoId||String(o.route?.videoId||'')===String(original.videoId)),{timeoutMs:2800,intervalMs:100,reason:`${reason}_${attempt}`}).catch(()=>null);if(obs)return true;}return false;}
  async maybeCheckpointHome({query,branch,origin='branch'}={}){if(this.config.homeObserveOnTopicShift===false||this.config.homeExplore===false)return null;const lastHop=(branch?.hops||[]).at(-1),topic=lastHop?.currentTopic||classifyTopic((branch?.topicPath||[]).at(-1)||{}),identity=topicIdentity(topic);if(!identity||identity===this.lastHomeCheckpointTopic)return null;const before=await this.observe(`home_topic_checkpoint_${this.homeTopicCheckpoints.length+1}_before`),original={pageType:before.route?.pageType||null,videoId:before.route?.videoId||null};const stage=`topic_${this.homeTopicCheckpoints.length+1}_${fold(topic?.primaryTopic||'unknown').slice(0,20)}`,scan=await this.scanHome(stage,{navigate:true}),homeTopic=classifySurface((scan.candidates||[]).map(x=>x.candidate).filter(Boolean)),delta=homeDelta(this.lastHomeScan,scan),restored=await this.restoreAfterHome(original,{reason:`${stage}_restore`}),checkpoint={at:Date.now(),query,origin,sourceVideoId:lastHop?.sourceVideoId||original.videoId||null,sourceTopic:topic,homeTopic,scan,delta,restored};this.homeTopicCheckpoints.push(checkpoint);this.lastHomeCheckpointTopic=identity;this.lastHomeScan=scan;this.log('home_topic_checkpoint',{query,origin,sourceVideoId:checkpoint.sourceVideoId,sourceTopic:topic?.primaryTopic||null,homeDisplayedTopic:homeTopic.primaryDisplayedTopic,addedCount:delta.addedVideoIds.length,targetSeen:scan.targetExposure?.seen===true,restored});return checkpoint;}
  async runPrimaryQueries(){for(const query of this.config.headQueries){if(Date.now()-this.startedAt>this.config.maxRuntimeSec*1000)break;const pool=await this.collectSearchSeeds(query),run={query,queryOrigin:'broad_head_keyword',trackedVideoHeadKeywordEvidence:pool.trackedVideoHeadKeywordEvidence,searchSeeds:pool.compactSeeds,branches:[],homeAfterQuery:null};for(const seed of pool.seeds){for(const branchMode of this.config.branchModes){if(Date.now()-this.startedAt>this.config.maxRuntimeSec*1000)break;const branch=await this.exploreBranch(query,seed,branchMode);run.branches.push(branch);await this.maybeCheckpointHome({query,branch,origin:'broad_head_branch'});}}if(this.config.homeExplore!==false){run.homeAfterQuery=await this.scanHome(`after_${fold(query).slice(0,24)}`,{navigate:true});this.homeDiscovery.afterHeadQueries.push({query,scan:run.homeAfterQuery});this.lastHomeScan=run.homeAfterQuery;}this.headKeywordRuns.push(run);}}
  async runBridgeKeyQueries(){if(this.config.bridgeKeySearch===false||Number(this.config.bridgeKeySearchCount||0)<=0)return;const ranked=this.keyGraph.searchCandidates({limit:Math.max(4,Number(this.config.bridgeKeySearchCount||2)*5),headQueries:this.config.headQueries,targetTopic:this.effectiveTargetTopic?.()||this.config.targetTopic,targetTitle:this.trackedVideoApi?.title||null,trackVideoId:this.config.trackVideoId});for(const keyRow of ranked){if(this.bridgeKeyRuns.length>=Number(this.config.bridgeKeySearchCount||2)||Date.now()-this.startedAt>this.config.maxRuntimeSec*1000)break;const query=clean(keyRow.key);if(!query||this.expansionQueries.has(fold(query)))continue;this.expansionQueries.add(fold(query));const pool=await this.collectSearchSeeds(query),run={query,queryOrigin:'observed_bridge_key',keyEvidence:keyRow,searchSeeds:pool.compactSeeds,branches:[],homeAfterQuery:null};const seedLimit=Math.max(1,Math.min(pool.seeds.length,Number(this.config.bridgeKeySeedCount||1)));for(const seed of pool.seeds.slice(0,seedLimit)){const branch=await this.exploreBranch(query,seed,'source_bridge');run.branches.push(branch);await this.maybeCheckpointHome({query,branch,origin:'bridge_key_branch'});}if(this.config.homeExplore!==false){run.homeAfterQuery=await this.scanHome(`after_key_${fold(query).replace(/[^a-z0-9]+/g,'_').slice(0,24)}`,{navigate:true});this.lastHomeScan=run.homeAfterQuery;}this.bridgeKeyRuns.push(run);this.headKeywordRuns.push(run);this.log('bridge_key_search_complete',{query,demandProxy:keyRow.demandProxy,videoCount:keyRow.videoCount,topicDiversity:keyRow.topicDiversity,crossTopicEdges:keyRow.crossTopicEdges,seedCount:run.searchSeeds.length});}}
  async run(){try{await this.selectBrowser();await this.createTask();this.captureEnvironment();await this.validatePristine();await this.loadTrackedVideo();if(this.config.homeExplore!==false){this.homeDiscovery.baseline=await this.scanHome('baseline',{navigate:false});this.lastHomeScan=this.homeDiscovery.baseline;}await this.runPrimaryQueries();await this.runBridgeKeyQueries();await this.loadTrackedVideo({refresh:true});const factorSummary=summarizeRuns(this.headKeywordRuns);return this.complete('head_keyword_next_complete',{mode:'target_blind_key_graph_route_discovery',headKeywordRuns:this.headKeywordRuns,homeDiscovery:this.homeDiscovery,factorSummary,bridgeKeyRuns:this.bridgeKeyRuns,keyGraph:this.keyGraph.report(),homeTopicCheckpoints:this.homeTopicCheckpoints});}catch(error){this.log('runner_error',{error:String(error?.stack||error)});await this.req('TASK_FAIL',{taskId:this.taskId,error:String(error?.message||error)}).catch(finalizeError=>this.log('task_finalize_error',{operation:'TASK_FAIL',error:String(finalizeError?.message||finalizeError)}));this.endedAt=Date.now();const report=this.report('error',{error:String(error?.stack||error),headKeywordRuns:this.headKeywordRuns,homeDiscovery:this.homeDiscovery,factorSummary:summarizeRuns(this.headKeywordRuns),bridgeKeyRuns:this.bridgeKeyRuns,keyGraph:this.keyGraph.report(),homeTopicCheckpoints:this.homeTopicCheckpoints});this.writeReport(report);throw error;}finally{await this.client.close().catch(()=>{});}}
  report(outcome,extra={}){const base=super.report(outcome,extra);return {...base,tool:'BODY Target-Blind Key Graph Route Discovery Lab',mode:'target_blind_key_graph_route_discovery',objective:'Discover cross-topic paths using only keys/tags/topics/keywords observed from non-target videos. Derived key searches are allowed only when the key was observed in the route graph and ranks highly on an observed video-statistics demand proxy. The tracked video title/id and direct target-topic query are forbidden as expansion queries. Home is re-observed after distinct topic branches to measure session-conditioned recommendation changes.',bridgeKeyRuns:this.bridgeKeyRuns,keyGraph:this.keyGraph.report(),homeTopicCheckpoints:this.homeTopicCheckpoints,keySearchPolicy:{targetBlind:true,targetMetadataUsedForPositiveSelection:false,targetMetadataUsedOnlyForNegativeLeakageGuard:true,directTargetTitleSearch:false,directTargetIdSearch:false,directTargetTopicSearch:false,demandProxyIsSearchVolume:false,demandProxyInterpretation:'Uses observed video coverage, topic diversity, cross-topic edges, views and views/hour. YouTube Data API does not expose query search volume.'},guardrails:{...base.guardrails,genericHeadKeywordSearchOnly:false,observedBridgeKeySearchOnly:true,additionalTargetSearchQueries:false,targetMetadataUsedForSelection:false,targetEvaluationPostObservationOnly:true,homeObservationEnabled:this.config.homeExplore!==false,homeObservedAfterDistinctTopics:this.config.homeObserveOnTopicShift!==false}};}
}

module.exports={GENERIC_TOPIC_KEYS,NOISE_KEYS,clean,fold,meaningfulKey,topicFamily,videoKeyRows,topicDistance,factorKeys,ObservedKeyGraph,chooseDiversifyingBridge,homeDelta,topicIdentity,KeyGraphRouteRunner};
