'use strict';

const {HeadKeywordNextRunner,publicFactorComparison,compactNode,chooseNaturalNext}=require('./head_keyword_next_runner');
const {semanticArrivalReady}=require('./topic_transition_runner');

const sleep=ms=>new Promise(resolve=>setTimeout(resolve,Math.max(0,Number(ms)||0)));
const clean=v=>String(v??'').normalize('NFKC').replace(/\s+/g,' ').trim();
const fold=v=>clean(v).toLowerCase().normalize('NFD').replace(/\p{M}+/gu,'').replace(/đ/g,'d');
const uniq=xs=>[...new Set((xs||[]).map(clean).filter(Boolean))];
const apiOf=node=>node?.youtubeApi||node||{};
const CATEGORY_NAMES={'1':'Film & Animation','2':'Autos & Vehicles','10':'Music','15':'Pets & Animals','17':'Sports','19':'Travel & Events','20':'Gaming','22':'People & Blogs','23':'Comedy','24':'Entertainment','25':'News & Politics','26':'Howto & Style','27':'Education','28':'Science & Technology','29':'Nonprofits & Activism'};
const STOP=new Set(['the','and','for','with','from','this','that','video','official','latest','today','youtube','channel','watch','va','voi','cua','cho','nay','do','la','mot','nhung','cac','tai','tu','trong','tren','duoc','moi','hom','khong','nhu','ve','co','den','khi','sau','truoc','phai','dang','cach','ra','vao','neu']);

function tokens(value){return fold(value).split(/[^\p{L}\p{N}+#._-]+/gu).filter(x=>x.length>=2&&!STOP.has(x)&&!/^[\d._-]+$/.test(x));}
function addScore(map,term,score,source){const key=fold(term);if(!key||key.length<2||STOP.has(key)||!/\p{L}/u.test(key))return;const row=map.get(key)||{term:clean(term),score:0,sources:new Set()};row.score+=Number(score)||0;row.sources.add(source);map.set(key,row);}
function topicTerms(node){
  const api=apiOf(node),scores=new Map();
  for(const x of uniq(api.topicLabels))addScore(scores,x,14,'video_topic');
  for(const x of uniq(api.channel?.topicLabels))addScore(scores,x,7,'channel_topic');
  for(const x of uniq(api.tags)){addScore(scores,x,7,'tag');for(const t of tokens(x))addScore(scores,t,2.5,'tag_token');}
  for(const row of api.keywords||[]){const term=row?.term||row;if(term)addScore(scores,term,Math.min(8,Math.max(.5,Number(row?.score)||1)),'derived_keyword');}
  for(const t of tokens(api.title||node?.title))addScore(scores,t,3,'title');
  for(const x of uniq(api.channel?.keywords).slice(0,30)){addScore(scores,x,1.5,'channel_keyword');for(const t of tokens(x))addScore(scores,t,.5,'channel_keyword_token');}
  return [...scores.values()].map(x=>({...x,sources:[...x.sources]})).sort((a,b)=>b.score-a.score||a.term.localeCompare(b.term)).slice(0,24);
}
function classifyTopic(node){
  const api=apiOf(node),terms=topicTerms(node),videoTopicLabels=uniq(api.topicLabels),channelTopicLabels=uniq(api.channel?.topicLabels),categoryId=api.categoryId?String(api.categoryId):null,categoryName=categoryId?(CATEGORY_NAMES[categoryId]||`YouTube category ${categoryId}`):null;
  return {primaryTopic:videoTopicLabels[0]||terms[0]?.term||channelTopicLabels[0]||categoryName||'unclassified',categoryId,categoryName,videoTopicLabels,channelTopicLabels,dominantTerms:terms.slice(0,12),topicSignature:uniq([...videoTopicLabels,...channelTopicLabels,...terms.slice(0,8).map(x=>x.term)]).slice(0,12),basis:'public_metadata_only',heuristicOnly:true};
}
function classifySurface(rows,{limit=40}={}){
  const labels=new Map(),termsMap=new Map(),categories=new Map(),sample=(rows||[]).slice(0,limit);
  for(const row of sample){const p=classifyTopic(row),w=1/Math.sqrt(Math.max(1,Number(row.position)||1));for(const x of uniq([...p.videoTopicLabels,...p.channelTopicLabels]))labels.set(x,(labels.get(x)||0)+2*w);if(p.categoryName)categories.set(p.categoryName,(categories.get(p.categoryName)||0)+w);for(const x of p.dominantTerms.slice(0,8))termsMap.set(x.term,(termsMap.get(x.term)||0)+w*Math.min(6,Math.max(.5,x.score/4)));}
  const rank=map=>[...map.entries()].map(([value,score])=>({value,score:Number(score.toFixed(3))})).sort((a,b)=>b.score-a.score||a.value.localeCompare(b.value));
  const dominantTopics=rank(labels).slice(0,8),dominantTerms=rank(termsMap).slice(0,12),categoryMix=rank(categories).slice(0,8);
  return {sampleSize:sample.length,primaryDisplayedTopic:dominantTopics[0]?.value||dominantTerms[0]?.value||categoryMix[0]?.value||'unclassified',dominantTopics,dominantTerms,categoryMix,basis:'observed_surface_public_metadata',heuristicOnly:true};
}
function bridgeKeys(factors){return uniq([...(factors?.sharedTags||[]),...(factors?.sharedKeywords||[]),...(factors?.sharedTopics||[]),...(factors?.sharedChannelKeywords||[]),...(factors?.sharedChannelTopics||[]),...(factors?.sharedTitleTokens||[])]).slice(0,30);}
function transitionEvidence(source,candidate){
  const publicFactors=publicFactorComparison(source,candidate),sourceTopic=classifyTopic(source),candidateTopic=classifyTopic(candidate),sourceTerms=new Set(sourceTopic.dominantTerms.map(x=>fold(x.term))),keys=bridgeKeys(publicFactors),emergingTerms=candidateTopic.dominantTerms.map(x=>x.term).filter(x=>!sourceTerms.has(fold(x))).slice(0,10),expansionScore=Number((publicFactors.publicAffinityScore+Math.min(5,emergingTerms.length)*.35-(publicFactors.sameChannel?1.5:0)).toFixed(3));
  return {sourceTopic,candidateTopic,bridgeKeys:keys,emergingTerms,publicFactors,expansionScore,selectionEligible:keys.length>0,targetMetadataUsed:false};
}
function usable(row,visited){return Boolean(row?.videoId&&row?.semanticTitle!==false&&row?.isRadio!==true&&String(row.path||'').startsWith('/watch')&&!visited.has(String(row.videoId)));}
function chooseSourceBridge(rows,source,visited){return (rows||[]).filter(row=>usable(row,visited)).map(row=>({row,evidence:transitionEvidence(source,row)})).filter(x=>x.evidence.selectionEligible).sort((a,b)=>b.evidence.expansionScore-a.evidence.expansionScore||Number(a.row.position||9999)-Number(b.row.position||9999))[0]||null;}
function topicMatchEvidence(node,targetTopic){
  const target=fold(targetTopic),profile=classifyTopic(node);if(!target)return {targetTopic:null,score:null,matched:[],evaluationOnly:true,targetUsedForSelection:false};
  const targetTokens=new Set(tokens(target)),rows=[profile.primaryTopic,...profile.videoTopicLabels,...profile.channelTopicLabels,...profile.dominantTerms.map(x=>x.term),profile.categoryName].filter(Boolean),matched=[];
  for(const row of rows){const f=fold(row);if(f===target||f.includes(target)||target.includes(f)||tokens(row).some(x=>targetTokens.has(x)))matched.push(row);}
  const exact=rows.some(row=>fold(row)===target),phrase=rows.some(row=>fold(row).includes(target)||target.includes(fold(row))),score=Math.min(1,(exact?0.65:0)+(phrase?0.25:0)+Math.min(.45,uniq(matched).length*.09));
  return {targetTopic:clean(targetTopic),score:Number(score.toFixed(3)),matched:uniq(matched).slice(0,12),profile,evaluationOnly:true,targetUsedForSelection:false};
}
function directionProfile(currentTopic,displayedTopic,targetTopic){const sourceTerms=new Set((currentTopic?.dominantTerms||[]).map(x=>fold(x.term))),emergingTerms=(displayedTopic?.dominantTerms||[]).map(x=>x.value).filter(x=>!sourceTerms.has(fold(x))).slice(0,8);return {currentTopic:currentTopic?.primaryTopic||'unclassified',displayedTopic:displayedTopic?.primaryDisplayedTopic||'unclassified',directionToward:displayedTopic?.dominantTopics?.[0]?.value||emergingTerms[0]||displayedTopic?.primaryDisplayedTopic||'unclassified',emergingTerms,targetTopic:targetTopic||null,heuristicOnly:true};}
function observedExposureRows(runs,homeDiscovery,trackVideoId){
  const out=[];
  for(const run of runs||[]){const searchHit=(run.searchSeeds||[]).find(x=>String(x?.candidate?.videoId||'')===String(trackVideoId||''));if(searchHit)out.push({kind:'search',query:run.query,surface:'search_results',rank:searchHit.candidate.position||null,directDomEvidence:true,sourceVideoId:null,branchMode:null,topicPath:[]});for(const branch of run.branches||[])for(const hop of branch.hops||[])if(hop.targetExposure?.seen)out.push({kind:'related',query:run.query,surface:hop.targetExposure.surface,rank:hop.targetExposure.rank,directDomEvidence:true,sourceVideoId:hop.sourceVideoId,source:hop.source||null,branchMode:branch.branchMode,depth:hop.depth,edgeFactors:hop.targetExposure.edgeFactors||null,topicPath:branch.topicPath||[]});if(run.homeAfterQuery?.targetExposure?.seen)out.push({kind:'home_after_query',query:run.query,surface:'home_feed',rank:run.homeAfterQuery.targetExposure.rank,directDomEvidence:true,sourceVideoId:null,branchMode:null,topicPath:[]});}
  if(homeDiscovery?.baseline?.targetExposure?.seen)out.unshift({kind:'home_baseline',query:null,surface:'home_feed',rank:homeDiscovery.baseline.targetExposure.rank,directDomEvidence:true,sourceVideoId:null,branchMode:null,topicPath:[]});return out;
}
function buildAppearanceConclusion({runs,homeDiscovery,trackVideoId,trackedVideoApi,targetTopic}){
  const exposures=observedExposureRows(runs,homeDiscovery,trackVideoId),targetVideoTopic=classifyTopic({videoId:trackVideoId,youtubeApi:trackedVideoApi}),topicReached=[];
  for(const run of runs||[])for(const branch of run.branches||[])for(const hop of branch.hops||[])if(hop.targetTopicEvaluation?.score>=.6)topicReached.push({query:run.query,branchMode:branch.branchMode,depth:hop.depth,sourceVideoId:hop.sourceVideoId,score:hop.targetTopicEvaluation.score,matched:hop.targetTopicEvaluation.matched,currentTopic:hop.currentTopic?.primaryTopic||null,displayedTopic:hop.displayedTopic?.primaryDisplayedTopic||null});
  if(exposures.length){const first=exposures[0],mechanism=first.surface==='search_results'?'BROAD_SEARCH_RESULT':first.surface==='home_feed'?'HOME_FEED':'RELATED_UP_NEXT',publicBridgeKeys=bridgeKeys(first.edgeFactors),path=(first.topicPath||[]).map(x=>({videoId:x.videoId,title:x.title||null,topic:x.topic?.primaryTopic||null,via:x.via||null,bridgeKeys:x.bridgeKeys||[]}));return {status:'OBSERVED',mechanism,firstObserved:first,observedExposureCount:exposures.length,allObservedExposures:exposures,targetVideoTopic,targetTopic:targetTopic||targetVideoTopic.primaryTopic,path,publicBridgeKeys,conclusionVi:`Đã quan sát trực tiếp video đích xuất hiện trên ${first.surface}${first.rank?` ở vị trí ${first.rank}`:''}${first.sourceVideoId?` từ video nguồn ${first.sourceVideoId}`:''}. Đường đi trước thời điểm xuất hiện được ghi nhận theo từng video và các key/tag/topic giao nhau; metadata của video đích không được dùng để chọn bước tiếp theo.`,causalClaim:false,causalBoundary:'Kết luận được đường xuất hiện quan sát được, surface, rank và metadata bridge công khai; không kết luận trọng số nội bộ của thuật toán YouTube.'};}
  if(topicReached.length)return {status:'TARGET_TOPIC_REACHED_TRACKED_VIDEO_NOT_OBSERVED',mechanism:null,observedExposureCount:0,targetVideoTopic,targetTopic:targetTopic||targetVideoTopic.primaryTopic,targetTopicReached:topicReached,conclusionVi:'Đã đi vào vùng chủ đề đích theo metadata công khai, nhưng chưa quan sát thấy chính video đích trên Search/Related/Up Next/Home trong giới hạn lần chạy.',causalClaim:false};
  return {status:'NOT_OBSERVED',mechanism:null,observedExposureCount:0,targetVideoTopic,targetTopic:targetTopic||targetVideoTopic.primaryTopic,conclusionVi:'Chưa quan sát thấy video đích và chưa có bằng chứng đủ mạnh rằng đường đi đã vào vùng chủ đề đích trong giới hạn lần chạy; không suy diễn nguyên nhân khi chưa có DOM evidence.',causalClaim:false};
}
function homeTopicProfiles(homeDiscovery){const classify=scan=>scan?.candidates?classifySurface(scan.candidates.map(x=>x.candidate).filter(Boolean)):{sampleSize:0,primaryDisplayedTopic:'unclassified',dominantTopics:[],dominantTerms:[],categoryMix:[],heuristicOnly:true};return {baseline:classify(homeDiscovery?.baseline),afterHeadQueries:(homeDiscovery?.afterHeadQueries||[]).map(x=>({query:x.query,topic:classify(x.scan)}))};}

class TopicRouteRunner extends HeadKeywordNextRunner{
  effectiveTargetTopic(){return clean(this.config.targetTopic)||classifyTopic({youtubeApi:this.trackedVideoApi}).primaryTopic;}
  chooseNext(scan,branchMode,visited){const source=scan?.lastObs?.currentVideo||scan?.source||null;if(branchMode==='source_bridge'||branchMode==='metadata_bridge'){const choice=chooseSourceBridge(scan.rawRows,source,visited);return choice?{candidate:choice.row,selectionFactors:choice.evidence.publicFactors,transitionEvidence:choice.evidence,reason:'source_metadata_bridge_target_blind'}:null;}const candidate=chooseNaturalNext(scan.rawRows,visited);return candidate?{candidate,selectionFactors:publicFactorComparison(source,candidate),transitionEvidence:transitionEvidence(source,candidate),reason:'natural_top_related_non_radio_target_blind'}:null;}
  async exploreBranch(query,seed,branchMode){
    let obs=await this.openSeed(query,seed,branchMode);const visited=new Set([String(seed.videoId)]),hops=[],topicPath=[{videoId:seed.videoId,title:seed.youtubeApi?.title||seed.title||null,topic:classifyTopic(seed),via:'broad_search_seed',bridgeKeys:[]}];
    for(let depth=1;depth<=this.config.maxHops;depth++){
      if(this.config.dwellSec>0){await sleep(this.config.dwellSec*1000);obs=await this.observe(`branch_${branchMode}_dwell_${depth}`);}
      const scan=await this.scanNextSurface(obs,{depth,branchMode,visited}),sourceRaw=scan.lastObs?.currentVideo||scan.source,currentTopic=classifyTopic(sourceRaw),displayedTopic=classifySurface(scan.rawRows),targetTopic=this.effectiveTargetTopic(),targetTopicEvaluation=topicMatchEvidence(sourceRaw,targetTopic),direction=directionProfile(currentTopic,displayedTopic,targetTopic),publicScan={depth:scan.depth,branchMode:scan.branchMode,sourceVideoId:scan.sourceVideoId,source:scan.source,currentTopic,displayedTopic,direction,targetTopicEvaluation,sourceToTrackedFactors:scan.sourceToTrackedFactors,targetExposure:scan.targetExposure,candidates:scan.candidates,visited:scan.visited};hops.push(publicScan);
      if(scan.targetExposure.seen||depth>=this.config.maxHops)break;const next=this.chooseNext(scan,branchMode,visited);if(!next||String(next.candidate.videoId)===String(this.config.trackVideoId))break;const clicked=await this.clickCandidate(next.candidate,{reason:`next_hop:${branchMode}:${next.reason}`});if(!clicked)break;visited.add(String(next.candidate.videoId));publicScan.nextSelection={videoId:next.candidate.videoId,title:next.candidate.youtubeApi?.title||next.candidate.title||null,surface:next.candidate.surface,position:next.candidate.position,reason:next.reason,selectionFactors:next.selectionFactors,transitionEvidence:next.transitionEvidence,targetMetadataUsedForSelection:false};topicPath.push({videoId:next.candidate.videoId,title:next.candidate.youtubeApi?.title||next.candidate.title||null,topic:next.transitionEvidence?.candidateTopic||classifyTopic(next.candidate),via:next.reason,bridgeKeys:next.transitionEvidence?.bridgeKeys||[],emergingTerms:next.transitionEvidence?.emergingTerms||[]});obs=await this.waitFor(o=>semanticArrivalReady(o,next.candidate),{timeoutMs:12000,intervalMs:250,reason:`next_arrival_${branchMode}_${depth+1}`}).catch(async()=>this.observe(`next_arrival_timeout_${branchMode}_${depth+1}`));
    }
    const result={query,seedVideoId:seed.videoId,seed:compactNode(seed),seedTopic:classifyTopic(seed),branchMode,hops,topicPath,targetSeen:hops.some(x=>x.targetExposure?.seen),searchRestored:false,targetMetadataUsedForSelection:false};const restored=await this.restoreHeadSearch(query,{reason:`branch_${branchMode}_return_to_search`}).catch(error=>{this.log('search_restore_error',{query,branchMode,error:String(error?.message||error)});return null;});result.searchRestored=Boolean(restored);return result;
  }
  report(outcome,extra={}){const base=super.report(outcome,extra),targetTopic=this.effectiveTargetTopic(),appearanceConclusion=buildAppearanceConclusion({runs:this.headKeywordRuns,homeDiscovery:this.homeDiscovery,trackVideoId:this.config.trackVideoId,trackedVideoApi:this.trackedVideoApi,targetTopic}),topicRouteSummary={startBroadTopics:this.config.headQueries,targetTopic,targetVideoId:this.config.trackVideoId,selectionRule:'TARGET_BLIND_SOURCE_METADATA_ONLY',targetMetadataUsedForSelection:false,homeTopics:homeTopicProfiles(this.homeDiscovery),branchSummaries:this.headKeywordRuns.flatMap(run=>(run.branches||[]).map(branch=>({query:run.query,seedVideoId:branch.seedVideoId,branchMode:branch.branchMode,targetSeen:branch.targetSeen,topicPath:branch.topicPath||[],hopTopics:(branch.hops||[]).map(hop=>({depth:hop.depth,currentTopic:hop.currentTopic,displayedTopic:hop.displayedTopic,direction:hop.direction,targetTopicEvaluation:hop.targetTopicEvaluation}))}))),appearanceConclusion};return {...base,tool:'BODY Target-Blind Topic Route Discovery Lab',mode:'target_blind_topic_route_discovery',objective:'Discover an observable route from a broad starting topic toward another topic without directly searching the target topic/video. After the initial broad search, bridge decisions use only public keys/tags/topics/keywords shared by the current video and observed candidates. Classify the current video topic, the displayed recommendation surface, the direction of topic drift, and conclude exactly where/how the tracked video was observed.',topicRouteSummary,appearanceConclusion,guardrails:{...base.guardrails,directTargetTopicSearch:false,targetVideoTitleUsedAsSearchQuery:false,targetMetadataUsedForSelection:false,targetEvaluationPostObservationOnly:true,bridgeSelectionSourceMetadataOnly:true,additionalTargetSearchQueries:false},interpretationBoundary:'BODY concludes observable route, surface, rank, topic drift and public metadata bridges. It does not claim access to YouTube internal recommendation weights or causal ranking reasons.'};}
}

module.exports={CATEGORY_NAMES,topicTerms,classifyTopic,classifySurface,bridgeKeys,transitionEvidence,chooseSourceBridge,topicMatchEvidence,directionProfile,observedExposureRows,buildAppearanceConclusion,homeTopicProfiles,TopicRouteRunner};
