'use strict';

const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {classifyVideo}=require('../research/autonomous_discovery/topic_classifier');
const {inspectQuery,buildQueryPlan,buildObservedQueryExpansion}=require('../research/autonomous_discovery/query_firewall');
const {adaptiveQueryPlan}=require('../research/autonomous_discovery/adaptive_query_planner');
const {bodyCapabilityCatalog}=require('../research/autonomous_discovery/body_capabilities');
const {AutonomousAgentPlanner}=require('../research/autonomous_discovery/agent_planner');
const {buildWorld}=require('../research/autonomous_discovery/world_model');
const {YouTubeApi}=require('../research/autonomous_discovery/youtube_api');
const {ExperienceMemory}=require('../research/autonomous_discovery/experience_memory');
const {reportMarkdown}=require('../research/autonomous_discovery/reporter');
const {planningProximity}=require('../research/autonomous_discovery/brain');
const {fingerprintText,sameFingerprint,randomScrollPoint}=require('../research/autonomous_discovery/brain_v2');
const {youtubeSemanticObservation,textFingerprint}=require('../src/youtube_semantic_observer');
const {parseArgs}=require('../research/autonomous_discovery/entry');

const target={videoId:'qXy0iyni-xk',title:'Khu dân cư mới Cầu Tràm 5x28m SHR đường rộng ô tô tránh nhau',categoryId:'22',defaultLanguage:'vi',tags:['bất động sản','nhà bình chánh','sổ hồng'],topicLabels:['Hobby','Lifestyle (sociology)'],channel:{country:'VN',keywords:['nhà bình chánh','bán nhà chính chủ'],topicLabels:['Knowledge']},keywords:[{term:'bất động sản',sources:['tag']},{term:'nhà bình chánh',sources:['channel_keyword']},{term:'cầu tràm',sources:['title']},{term:'Hobby',sources:['video_topic']}]};
assert.equal(inspectQuery('qXy0iyni-xk',{targetVideoId:target.videoId,targetTitle:target.title}).allowed,false);
assert.equal(inspectQuery('Khu dân cư mới Cầu Tràm 5x28m',{targetVideoId:target.videoId,targetTitle:target.title}).allowed,false);
assert.equal(inspectQuery('bất động sản',{targetVideoId:target.videoId,targetTitle:target.title}).allowed,true);
const plan=buildQueryPlan(target,{maxQueries:12});
assert.equal(plan.planner,'target_metadata_combinatorial_v2');assert.ok(plan.plan.length>=1);assert.ok(plan.plan.every(x=>inspectQuery(x.query,{targetVideoId:target.videoId,targetTitle:target.title}).allowed));assert.equal(plan.plan.some(x=>x.query.includes(target.videoId)),false);assert.equal(plan.plan.some(x=>x.kind==='domain'||x.kind==='fallback'),false);assert.ok(plan.plan.some(x=>x.kind==='combined'||x.kind==='metadata_phrase'));assert.equal(plan.plan.some(x=>/real\s+estate/i.test(x.query)),false);
const expansion=buildObservedQueryExpansion(['Nhà Bình Chánh sổ hồng giá rẻ 10 phút','Bán nhà Bình Chánh chính chủ giá rẻ','Nhà Bình Chánh giá rẻ đường ô tô'],plan.fingerprint,{targetVideoId:target.videoId,targetTitle:target.title},{existingQueries:plan.plan.map(x=>x.query),limit:5});assert.ok(expansion.plan.every(x=>!/(?:phút|phut|real\s+estate)/i.test(x.query)));assert.ok(expansion.plan.every(x=>inspectQuery(x.query,{targetVideoId:target.videoId,targetTitle:target.title}).allowed));

const adaptive=adaptiveQueryPlan(target,{maxQueries:24});assert.equal(adaptive.planner,'adaptive_target_metadata_v3');assert.equal(adaptive.targetLanguage,'vi');assert.ok(adaptive.plan.length>0);assert.equal(adaptive.plan.some(row=>/\bhobby\b/i.test(row.query)),false);assert.equal(adaptive.plan.some(row=>/\bknowledge\b/i.test(row.query)),false);assert.ok(adaptive.plan.every(row=>inspectQuery(row.query,{targetVideoId:target.videoId,targetTitle:target.title}).allowed));
const capabilities=bodyCapabilityCatalog();assert.ok(capabilities.motor.includes('click'));assert.ok(capabilities.motor.includes('drag'));assert.ok(capabilities.browserUi.includes('devtools'));assert.ok(capabilities.browserUi.includes('newwindow'));assert.deepEqual(capabilities.tab,['tab_switch']);

const game=classifyVideo({title:'VALORANT Gameplay Highlights',youtubeApi:{categoryId:'20',tags:['gaming','esports'],topicLabels:['Video game culture']}});assert.equal(game.primary,'gaming');
const estate=classifyVideo({title:'Bán nhà Bình Chánh sổ hồng riêng',youtubeApi:{categoryId:'22',tags:['nhà đất','bất động sản'],topicLabels:[]}});assert.equal(estate.primary,'real_estate');
const adaptiveFingerprint={videoId:target.videoId,categoryId:target.categoryId,primaryTopic:'real_estate',topics:target.topicLabels,tags:target.tags,keywords:target.keywords.map(x=>x.term),country:'VN',language:'vi'};
const proximity=planningProximity({classification:estate,youtubeApi:{categoryId:'22',tags:['bất động sản'],topicLabels:[],keywords:[{term:'nhà bình chánh'}],channel:{country:'VN'}}},adaptiveFingerprint);assert.ok(proximity>0.2);

const plannerMemory={ucb(){return 0;},state:{queries:{}}};const agentPlanner=new AutonomousAgentPlanner({memory:plannerMemory,explorationBase:0});const world=buildWorld({observation:{environment:{online:true,eligible:true,status:'ELIGIBLE'},bodyState:{activeTabId:1,pointer:{known:true,x:20,y:20}}},semantic:{route:{pageType:'watch',videoId:'source'},viewport:{width:1000,height:700,scrollY:0},controls:{},advertising:{playingAd:false}},snapshot:{pageType:'watch',currentVideoId:'source',currentTopic:'real_estate',candidates:[{videoId:target.videoId,surface:'related',position:9,visible:true,actionable:true,hitTested:true,actionPoint:{x:110,y:60},visibleRect:{x:10,y:20,width:200,height:80,centerX:110,centerY:60},actionRect:{x:10,y:20,width:200,height:80},evidence:{geometryKnown:true,rectIntersectsViewport:true,hitOwned:true},classification:{primary:'real_estate',confidence:0.9},targetMatch:true,targetProximity:0.95}]},browser:{tabs:[{id:1,active:true,siteKey:'youtube.com',title:'YT'},{id:2,active:false,siteKey:'youtube.com',title:'branch'}]},tabId:1,target:{videoId:target.videoId},history:[]});const taskModel=agentPlanner.inferTask(target,{targetLanguage:'vi',fingerprint:adaptiveFingerprint});const agentPlan=agentPlanner.generate(world,{task:taskModel,queryPlan:adaptive,dynamicQueries:[],usedQueries:new Set(),stagnation:0});assert.equal(agentPlan.actions[0].type,'click_candidate');assert.equal(agentPlan.actions[0].target.videoId,target.videoId);assert.ok(agentPlan.actions.some(a=>a.capability==='browser_ui.devtools'));assert.ok(agentPlan.actions.some(a=>a.type==='tab_switch'&&a.tabId===2));assert.equal(agentPlan.actions.some(a=>['related_top','related_long_tail','new_query','home_reset'].includes(a.type)),false);

function makeAnchor(){const card={tagName:'YTD-VIDEO-RENDERER',querySelectorAll(){return [];},getBoundingClientRect(){return {x:100,y:150,width:420,height:100};}};return {href:'https://www.youtube.com/watch?v=abc123xyz',parentElement:null,getAttribute(name){if(name==='href')return '/watch?v=abc123xyz';if(name==='title')return 'Minecraft Gameplay Challenge';return null;},closest(selector){if(selector.includes('ytd-ad-slot-renderer'))return null;return card;},getBoundingClientRect(){return {x:110,y:160,width:300,height:70};}};}
const anchor=makeAnchor();const searchRoot={querySelectorAll(selector){return selector.includes('a[href')?[anchor]:[];},getBoundingClientRect(){return {x:0,y:100,width:900,height:600};}};const searchInput={tagName:'INPUT',value:'hidden',getBoundingClientRect(){return {x:200,y:20,width:400,height:40};}};const skipButton={tagName:'BUTTON',getBoundingClientRect(){return {x:900,y:620,width:150,height:45};}};const player={classList:{contains(name){return name==='ad-showing';}}};const documentRef={activeElement:searchInput,title:'YouTube',documentElement:{scrollHeight:1800},body:{scrollHeight:1700},querySelector(selector){if(selector==='input#search')return searchInput;if(selector==='ytd-search #contents')return searchRoot;if(selector==='#movie_player')return player;if(selector==='button.ytp-skip-ad-button')return skipButton;return null;},querySelectorAll(){return [];}};const observation=youtubeSemanticObservation({documentRef,windowRef:{innerWidth:1200,innerHeight:800,scrollY:125,scrollX:0},locationRef:{href:'https://www.youtube.com/results?search_query=hidden'}});assert.equal(observation.surfaces[0].items[0].videoId,'abc123xyz');assert.equal(observation.surfaces[0].items[0].title,'Minecraft Gameplay Challenge');assert.equal(observation.privacy.searchQueryCaptured,false);assert.equal(observation.privacy.searchQueryFingerprintCaptured,true);assert.equal(JSON.stringify(observation).includes('search_query=hidden'),false);assert.deepEqual(observation.route.searchQueryFingerprint,textFingerprint('hidden'));assert.deepEqual(observation.controls.searchInput.valueFingerprint,textFingerprint('hidden'));assert.equal(observation.advertising.playingAd,true);assert.equal(observation.advertising.skippable,true);assert.equal(observation.viewport.scrollY,125);assert.ok(sameFingerprint(fingerprintText('nhà đất đời sống'),textFingerprint('nhà đất đời sống')));assert.equal(sameFingerprint(fingerprintText('nhà đất'),textFingerprint('nhà đấtđời sống')),false);const scrollPoint=randomScrollPoint(observation,'search_results');assert.ok(scrollPoint.x>=20&&scrollPoint.x<=1180);assert.ok(scrollPoint.y>=90&&scrollPoint.y<=780);

const dir=fs.mkdtempSync(path.join(os.tmpdir(),'body-autodiscovery-'));const memory=new ExperienceMemory(path.join(dir,'memory.json'));memory.startRun();memory.recordStrategy('motor.click:follow_environment_edge',{context:'watch|music',reward:8,success:true,newTopics:1,newTransitions:2});memory.recordTransition('music','gaming',{surface:'related'});memory.recordQuery('gaming',{reward:4,resultCount:20});memory.save();const reloaded=new ExperienceMemory(path.join(dir,'memory.json'));assert.equal(reloaded.summary().strategies[0].attempts,1);assert.equal(reloaded.summary().transitions[0].toTopic,'gaming');const md=reportMarkdown({runId:'run-test',status:'RUNNING',target:{videoId:target.videoId,title:target.title},startedAt:new Date(0).toISOString(),updatedAt:new Date(1).toISOString(),summary:{steps:1,uniqueVideosObserved:1,uniqueTopicsObserved:1,queryAttempts:1,bodyActions:3},targetDiscovery:{surface:'related',rank:8,fromVideoId:'source',fromTopic:'music',strategy:'agent_planner',opened:false},path:[],snapshots:[],memory:reloaded.summary(),queryAudit:[]});assert.match(md,/Found via: \*\*next_video\*\*/);assert.match(md,/Learned experience/);const parsed=parseArgs(['--target',target.videoId,'--unlimited','true','--report-every-steps','5','--action-retries','4','--exploration-rate','0.25']);assert.equal(parsed.unlimited,true);assert.equal(parsed.maxSteps,0);assert.equal(parsed.reportEverySteps,5);assert.equal(parsed.actionRetries,4);assert.equal(parsed.browserWaitSec,120);assert.equal(parsed.explorationRate,0.25);

function abortingFetch(_url,{signal}={}){return new Promise((resolve,reject)=>{const fail=()=>{const error=new Error('mock aborted');error.name='AbortError';reject(error);};if(signal?.aborted)return fail();signal?.addEventListener('abort',fail,{once:true});});}
async function apiResilienceContract(){let candidateCalls=0;const optionalApi=new YouTubeApi({apiKey:'test-key',fetchImpl:(url,options)=>{candidateCalls++;return abortingFetch(url,options);},required:true,timeoutMs:50,maxRetries:1,retryBaseMs:0});const candidateMap=await optionalApi.enrichVideoIds(['candidate-video']);assert.equal(candidateMap.size,0);assert.equal(candidateCalls,2);assert.equal(optionalApi.stats().retries,1);assert.equal(optionalApi.stats().timeouts,1);assert.equal(optionalApi.stats().degradedCalls,1);let targetCalls=0;const requiredApi=new YouTubeApi({apiKey:'test-key',fetchImpl:(url,options)=>{targetCalls++;return abortingFetch(url,options);},required:true,timeoutMs:50,maxRetries:1,retryBaseMs:0});await assert.rejects(()=>requiredApi.profileTarget('target-video'),error=>error?.code==='YOUTUBE_API_TIMEOUT'&&/youtube_api_videos_timeout_after_50ms/.test(error.message));assert.equal(targetCalls,2);assert.equal(requiredApi.stats().retries,1);assert.equal(requiredApi.stats().degradedCalls,0);}
apiResilienceContract().then(()=>{fs.rmSync(dir,{recursive:true,force:true});console.log('autonomous_discovery_contract: PASS');}).catch(error=>{fs.rmSync(dir,{recursive:true,force:true});console.error(error);process.exitCode=1;});
