'use strict';

const assert=require('node:assert/strict');
const {DaemonBridge,siteKeyFromUrl,observedEffect,PROTOCOL_VERSION}=require('../src/daemon_bridge');
function chromeStub(){const state={};const tabListeners={onActivated:[],onUpdated:[],onRemoved:[]};let contextQueries=0;const tab={id:1,active:true,windowId:1,title:'Example',url:'https://example.com/path',status:'complete'};return {state,tabListeners,get contextQueries(){return contextQueries;},runtime:{id:'runtime-id',getManifest(){return {version:'0.4.0'};}},storage:{local:{async get(defaults){return {...defaults,...state};},async set(v){Object.assign(state,v);}}},tabs:{async query(){return [tab];},async get(){return tab;},async update(){return tab;},async sendMessage(_id,message){if(message.action==='body.targetContextAt'){contextQueries++;return {ok:true,result:{tag:'input',role:'textbox',inputType:'text',editable:true,sensitive:false,rect:{x:0,y:0,width:100,height:20}}};}if(message.action==='body.pageObservation')return {ok:true,result:{available:true,hasFocus:true,visibilityState:'visible',activeTarget:{tag:'input',role:'textbox',editable:true,sensitive:false,rect:{x:0,y:0,width:100,height:20}},scrollX:0,scrollY:0,viewport:{width:800,height:600}}};return {ok:true};},onActivated:{addListener(fn){tabListeners.onActivated.push(fn);}},onUpdated:{addListener(fn){tabListeners.onUpdated.push(fn);}},onRemoved:{addListener(fn){tabListeners.onRemoved.push(fn);}}},windows:{async update(){return {focused:true};},async get(){return {focused:true};}}};}
(async()=>{
  assert.equal(PROTOCOL_VERSION,5);const sent=[];const chromeApi=chromeStub();const gateway={attachedTabs:new Set(),async sendInput(tabId,method,params){sent.push({tabId,method,params});return {ok:true};},async detach(){return {detached:true};}};const bridge=new DaemonBridge(chromeApi,{gateway,WebSocketImpl:function(){}});bridge.extensionInstanceId='ext-test';bridge.socket={readyState:1,send(raw){sent.push(JSON.parse(raw));}};
  assert.equal(siteKeyFromUrl('https://Sub.Example.com/a'),'sub.example.com');
  await bridge.forwardUserMotor(1,{source:'USER',kind:'pointer',url:'https://example.com/a',event:{type:'mouseMoved',x:10,y:20,at:100},context:{}});assert.equal(chromeApi.contextQueries,0);
  await bridge.forwardUserMotor(1,{source:'USER',kind:'pointer',url:'https://example.com/a',event:{type:'mousePressed',x:10,y:20,at:110},context:{}});assert.equal(chromeApi.contextQueries,1);
  await bridge.forwardUserMotor(1,{source:'USER',kind:'keyboard',url:'https://example.com/a',event:{type:'keydown',key:'a',code:'KeyA',at:120},context:{}});assert.equal(chromeApi.contextQueries,2);const keyboard=sent.find(x=>x.type==='RECORDER_EVENT'&&x.event?.keyClass==='alpha');assert.equal(keyboard.event.key,null);
  sent.length=0;const result=await bridge.executePlan({commandId:'c1',tabId:1,plan:{executionCapability:'HUMAN_MOTOR',steps:[{method:'Input.dispatchMouseEvent',delayMs:0,params:{type:'mouseMoved',x:30,y:40,button:'none'}}]}});assert.equal(result.delivered,true);assert.equal(result.observed,true);assert.equal(result.taskSuccess,null);assert.ok(result.observedEffect);assert.equal(sent.some(x=>x.method==='Input.dispatchMouseEvent'),true);await assert.rejects(()=>bridge.executePlan({tabId:1,plan:{executionCapability:'HUMAN_MOTOR',steps:[{method:'Runtime.evaluate',params:{}}]}}),/forbidden_method/);
  const effect=observedEffect({navigationToken:'a',navigationEpoch:1,page:{available:true,activeTarget:{tag:'body'},scrollX:0,scrollY:0,hasFocus:true,visibilityState:'visible'}},{navigationToken:'b',navigationEpoch:2,page:{available:true,activeTarget:{tag:'input'},scrollX:0,scrollY:10,hasFocus:true,visibilityState:'visible'}});assert.equal(effect.navigationChanged,true);assert.equal(effect.activeTargetChanged,true);assert.equal(effect.scrollChanged,true);assert.equal(effect.changed,true);
  console.log('daemon_bridge_contract: PASS');
})().catch(error=>{console.error(error);process.exitCode=1;});
