'use strict';
const assert=require('node:assert/strict');
const {nodeView}=require('../src/dom_perception');
const {youtubeSemanticObservation,interactiveAffordances,candidateFromAnchor}=require('../src/youtube_semantic_observer');
const {buildWorld,worldDelta}=require('../research/autonomous_discovery/world_model');
const {evaluateAction,rebindAffordance}=require('../research/autonomous_discovery/action_feedback');
const {AutonomousAgentPlanner}=require('../research/autonomous_discovery/agent_planner');
const {BrowserUiAdapter}=require('../daemon/src/browser_ui_adapter');
const {HUMAN_MOTOR_METHODS}=require('../src/cdp_input_gateway');
const rect={x:20,y:200,width:200,height:100};
const style={display:'block',visibility:'visible',opacity:'1'};
const win={innerWidth:1000,innerHeight:700,getComputedStyle:n=>n.style||style};
function node(extra={}){return {tagName:'A',textContent:'Video example',parentElement:null,getBoundingClientRect:()=>rect,getAttribute:n=>({href:'/watch?v=candidate01',title:'Video example'})[n]||null,closest:()=>null,querySelectorAll:()=>[],...extra};}
async function main(){
  const link=node(),doc={querySelectorAll:()=>[link],elementFromPoint:()=>link};link.ownerDocument=doc;
  assert.equal(interactiveAffordances(doc,win).length,1);
  link.style={...style,visibility:'hidden'};assert.equal(interactiveAffordances(doc,win).length,0);delete link.style;
  link.parentElement=node({hidden:true});assert.equal(nodeView(link,rect,{documentRef:doc,windowRef:win}).reason,'hidden');link.parentElement=null;
  doc.elementFromPoint=()=>node({tagName:'DIALOG'});
  const covered=candidateFromAnchor(link,'related',1,{windowRef:win});assert.equal(covered.visible,false);assert.equal(covered.actionable,false);assert.equal(covered.reason,'occluded');
  doc.elementFromPoint=(x,y)=>x>150?link:node({tagName:'DIALOG'});
  const partial=nodeView(link,rect,{documentRef:doc,windowRef:win});assert.equal(partial.actionable,true);assert.ok(partial.actionPoint.x>150);
  link.parentElement=node({style:{...style,overflow:'hidden'},getBoundingClientRect:()=>({x:0,y:0,width:100,height:100})});assert.equal(nodeView(link,rect,{documentRef:doc,windowRef:win}).reason,'outside_view');link.parentElement=null;
  const ad=node({textContent:'Get quote',closest:selector=>selector.includes('companion')?{}:null});
  assert.equal(interactiveAffordances({querySelectorAll:()=>[ad]},win)[0].sponsored,true);
  const error=node({tagName:'DIV',textContent:'Không xem được nội dung này. Vui lòng thử lại sau.',getAttribute:()=>null});
  const channelRoot={querySelectorAll:()=>[link],getBoundingClientRect:()=>rect};
  const channelDoc={hasFocus:()=>false,visibilityState:'visible',querySelector:s=>s==='ytd-browse[page-subtype="channels"]'?channelRoot:null,querySelectorAll:s=>s.includes('.ytp-error-content')?[error]:[],elementFromPoint:(x,y)=>error};
  const scene=youtubeSemanticObservation({documentRef:channelDoc,windowRef:win,locationRef:{href:'https://www.youtube.com/channel/example'}});
  assert.equal(scene.route.pageType,'channel');assert.equal(scene.surfaces[0].surface,'channel_feed');assert.equal(scene.surfaces[0].items[0].videoId,'candidate01');assert.ok(scene.scene.errors[0].label.includes('Không xem được'));
  assert.equal(scene.scene.browserUi.observed,false);assert.equal(scene.scene.browserUi.state,'focus_outside_document');
  const aff={tag:'button',role:'button',label:'Expand',state:{expanded:'false'},actionRect:rect,actionPoint:{x:40,y:220}};
  const semantic={route:{pageType:'channel'},viewport:{width:1000,height:700},affordances:[aff],scene:{hasFocus:true,dialogs:[],errors:[]}};
  const before=buildWorld({tabId:1,semantic}),after=buildWorld({tabId:1,semantic:{...semantic,affordances:[{...aff,state:{expanded:'true'}}]}});
  const delta=worldDelta(before,after);assert.equal(delta.changed,true);assert.ok(delta.reasons.includes('control_state'));
  assert.equal(evaluateAction({type:'body_step',step:{kind:'motor',intent:{type:'click'}}},{success:true},before,after,delta).verdict,'confirmed');
  assert.equal(evaluateAction({type:'click_candidate',target:{videoId:'other'}},{success:true},before,after,delta).verdict,'failed','unrelated control change cannot verify a video click');
  assert.equal(evaluateAction({type:'body_step',step:{kind:'browser_ui',action:'dismiss'}},{success:true},before,after,delta).verdict,'failed','Escape delivery is not evidence a native prompt closed');
  assert.equal(evaluateAction({type:'body_step',step:{kind:'browser_ui',action:'find'}},{success:true},before,after,delta).verdict,'unknown');
  const moved={...aff,index:19,actionPoint:{x:700,y:250}};assert.equal(rebindAffordance(aff,{affordances:[moved]}).actionPoint.x,700);
  assert.equal(rebindAffordance(aff,{affordances:[moved,moved]}),null);assert.equal(rebindAffordance(aff,{affordances:[{...moved,actionable:false}]}),null);
  const lost={...before,scene:{hasFocus:false}},planner=new AutonomousAgentPlanner({explorationBase:0});
  const plan=planner.generate(lost,{task:{targetFormat:'UNKNOWN'},queryPlan:{plan:[]}});assert.ok(plan.actions.some(a=>a.capability==='browser_ui.dismiss'));assert.ok(!plan.actions.some(a=>a.capability.startsWith('motor')));
  const partialPlan=planner.generate({...before,freshness:{observationUnavailable:true}},{task:{targetFormat:'UNKNOWN'},queryPlan:{plan:[]}});
  assert.ok(partialPlan.actions.some(a=>a.capability==='browser_ui.reload'));assert.ok(!partialPlan.actions.some(a=>a.capability.startsWith('motor')));
  const initial=planner.generate(before,{task:{targetFormat:'UNKNOWN'},queryPlan:{plan:[]}}),tried=initial.actions[0];
  const replanned=planner.generate({...before,history:[{actionKey:tried.actionKey,success:false,feedback:{verdict:'failed'},beforeSignature:before.signature}]},{task:{targetFormat:'UNKNOWN'},queryPlan:{plan:[]}});
  assert.notEqual(replanned.actions[0].actionKey,tried.actionKey,'failure in unchanged state must select an alternative');
  const native=[],adapter=new BrowserUiAdapter({resolveTarget:async()=>({extensionId:'x',tab:{id:1}}),focusTarget:async()=>({verified:true}),snapshot:async()=>({tabs:[{id:1}],active:{id:1}}),runNativeInput:async(mode,value)=>{native.push({mode,value});return {ok:true};}});
  const result=await adapter.execute('dismiss');assert.deepEqual(native,[{mode:'key',value:'Escape'}]);assert.equal(result.verified,false);assert.equal(result.observedEffect.observable,false);
  // The default page transport still has exactly the original CDP input methods.
  assert.deepEqual([...HUMAN_MOTOR_METHODS].sort(),['Input.dispatchKeyEvent','Input.dispatchMouseEvent']);
  console.log('perception_feedback_contract: PASS');
}
main().catch(error=>{console.error(error);process.exitCode=1;});
