'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {ExtensionRegistry,ScopedLearningManager,OnlineBehaviorModel,HumanActionSegmenter,HabitModel,TabHabitModel,SafeJsonPersistence,normalizeSiteKey}=require('./src/runtime_exports');
const {MotorPlanner,bootstrapMove}=require('./src/motor_planner');
const {DatasetStore}=require('./src/dataset_store');
const {BrowserUiAdapter,BROWSER_COMMANDS}=require('./src/browser_ui_adapter');
const {createWindowsInputRunner}=require('./src/windows_native_input');
const {LocalAuth}=require('./src/local_auth');
const {PROTOCOL_VERSION,navigationToken}=require('../src/daemon_bridge');
function tmp(name){return fs.mkdtempSync(path.join(os.tmpdir(),`${name}-`));}
function clickSample(offset=0){return {source:'human',action:'click',tabId:1,context:{target_role:'button',target_rect:{x:100,y:100,width:80,height:32}},pointer_start:{x:0,y:0},points:[{x:0,y:0,t:0},{x:50,y:30+offset,t:60},{x:140,y:116,t:140}],mouse_down_t:145,mouse_up_t:190,hold_ms:45};}

test('extension registry isolates identical tab ids',()=>{const r=new ExtensionRegistry();r.register('a',{}, {tabs:[{id:1,active:true,siteKey:'a.test'}]});r.register('b',{}, {tabs:[{id:1,active:true,siteKey:'b.test'}]});assert.equal(r.get('a').tabs.get(1).siteKey,'a.test');assert.equal(r.get('b').tabs.get(1).siteKey,'b.test');});
test('per-site fallback never crosses extension boundary',()=>{const m=new ScopedLearningManager(tmp('scope'));m.observeHumanSample('ext-a','alpha.test',clickSample(),{learn:true});assert.ok(m.motorFor('ext-a','new.test').sampleMouse({action:'click',role:'button',distance:150,targetWidth:80,targetHeight:32}));assert.equal(m.motorFor('ext-b','new.test').sampleMouse({action:'click',role:'button',distance:150,targetWidth:80,targetHeight:32}),null);m.flushSync();});
test('only human events become segmented ground truth',()=>{const rows=[];const s=new HumanActionSegmenter(x=>rows.push(x));s.handle(1,{source:'agent',eventType:'mousedown',ts:1,x:0,y:0,target:{}});s.handle(1,{source:'agent',eventType:'mouseup',ts:2,x:0,y:0,target:{}});assert.equal(rows.length,0);s.handle(1,{source:'human',eventType:'mousemove',ts:10,x:0,y:0,target:{}});s.handle(1,{source:'human',eventType:'mousedown',ts:20,x:20,y:20,target:{role:'button',rect:{x:10,y:10,width:40,height:30}}});s.handle(1,{source:'human',eventType:'mouseup',ts:50,x:20,y:20,target:{role:'button',rect:{x:10,y:10,width:40,height:30}}});assert.equal(rows[0].source,'human');});
test('trajectory selection stays deterministic and bootstrap stays linear',()=>{const model=new OnlineBehaviorModel(path.join(tmp('model'),'m.json'));model.observe(clickSample(0));model.observe(clickSample(8));const args={action:'click',role:'button',distance:150,targetWidth:80,targetHeight:32};const a=model.sampleMouse(args),b=model.sampleMouse(args),c=model.sampleMouse(args);assert.equal(a.selection,'deterministic-cycle');assert.equal(a.index,0);assert.equal(b.index,1);assert.equal(c.index,0);for(const row of bootstrapMove({x:0,y:0},{x:140,y:70}))assert.ok(Math.abs(row.params.y-row.params.x*0.5)<1e-9);model.flushSync();});
test('canonical typing keeps learned timing and Shift punctuation',()=>{const model={sampleMouse(){return null;},sampleTyping(){return {groupKey:'typing|typeText',count:1,template:{intervals:[100,120],holds:[40,50]}};},sampleScroll(){return null;}};const steps=new MotorPlanner(model).plan({type:'typeText',x:20,y:20,text:'A!'},{pointerStart:{x:0,y:0}}).plan.steps;assert.ok(steps.some(s=>s.params?.key==='Shift'&&s.params?.type==='rawKeyDown'));assert.ok(steps.some(s=>s.params?.key==='!'&&s.params?.code==='Digit1'&&s.params?.type==='char'));assert.throws(()=>new MotorPlanner(model).plan({type:'back'}),/browser_ui_action_required/);});
test('habit and tab learning ignore agent ground truth',()=>{const h=new HabitModel(path.join(tmp('habit'),'habit.json'));h.observe({source:'human',tabId:1,action:'typeText',context:{target_role:'textbox'}});h.observe({source:'human',tabId:1,action:'pressKey',key:'Enter',context:{target_role:'textbox'}});h.observe({source:'agent',tabId:1,action:'click',context:{target_role:'button'}});assert.equal(h.scoreAlternatives({habitKey:'after_typing_submit',alternatives:[{id:'k',modality:'keyboard',actions:[{type:'pressKey'}]},{id:'m',modality:'mouse',actions:[{type:'click'}]}],context:{previousAction:'typeText',previousModality:'keyboard',targetRole:'button'}}).ranking.length,2);const t=new TabHabitModel(path.join(tmp('tabs'),'tabs.json'));t.observe('ext-a',{source:'agent',eventType:'tabActivated',tabId:2,siteKey:'b.test'});const before=JSON.stringify(t.stats('ext-a'));t.observe('ext-a',{source:'human',eventType:'tabActivated',tabId:2,siteKey:'b.test'});assert.notEqual(JSON.stringify(t.stats('ext-a')),before);h.flushSync();t.flushSync();});
test('buffered DatasetStore batches writes and coalesces mousemove pressure',()=>{const dir=tmp('dataset');const store=new DatasetStore(dir,{batchSize:100,flushIntervalMs:10000,maxBufferedRows:100});for(let i=0;i<101;i++)store.appendEvent(1,{source:'human',eventType:'mousemove',ts:i,x:i,y:i});assert.ok(store.stats().bufferedRows<=100);assert.ok(store.stats().coalescedMousemoves>=1);assert.equal(fs.existsSync(path.join(dir,'human_events.jsonl')),false);store.flushSync();assert.equal(fs.existsSync(path.join(dir,'human_events.jsonl')),true);assert.equal(store.stats().bufferedRows,0);});
test('model persistence retries transient Windows rename locks without crashing',()=>{const dir=tmp('persist-retry'),file=path.join(dir,'model.json'),state={revision:7};let attempts=0;const flaky=Object.create(fs);flaky.renameSync=(from,to)=>{attempts++;if(attempts<3){const error=new Error('simulated Windows lock');error.code='EPERM';throw error;}return fs.renameSync(from,to);};const p=new SafeJsonPersistence(file,{getValue:()=>state,debounceMs:10000,retryDelaysMs:[0,0,0],retryAfterMs:10000,fsImpl:flaky,log:null});p.schedule();const result=p.flushSync();assert.equal(result.ok,true);assert.equal(attempts,3);assert.equal(p.status().dirty,false);assert.deepEqual(JSON.parse(fs.readFileSync(file,'utf8')),state);});
test('persistent rename lock keeps model dirty and reports degraded instead of throwing',()=>{const dir=tmp('persist-blocked'),file=path.join(dir,'model.json'),state={revision:9};const blocked=Object.create(fs);blocked.renameSync=()=>{const error=new Error('simulated persistent lock');error.code='EPERM';throw error;};const p=new SafeJsonPersistence(file,{getValue:()=>state,debounceMs:10000,retryDelaysMs:[0,0],retryAfterMs:10000,fsImpl:blocked,log:null});p.schedule();let result;assert.doesNotThrow(()=>{result=p.flushSync();});assert.equal(result.ok,false);assert.equal(p.status().dirty,true);assert.equal(p.status().degraded,true);assert.equal(p.status().lastError.code,'EPERM');assert.equal(fs.existsSync(file),false);});
test('local auth auto-pairs valid local Extension and auto-rotates stale token',()=>{const base=tmp('auth');const auth=new LocalAuth(base);assert.equal(auth.authenticateClient(auth.clientSecret),true);assert.equal(auth.authenticateClient('bad'),false);const first=auth.authenticateExtension({extensionId:'instance-a',browserInstanceId:'browser-a',runtimeExtensionId:'runtime-a',token:null,origin:'chrome-extension://runtime-a'});assert.equal(first.ok,true);assert.equal(first.paired,true);const second=auth.authenticateExtension({extensionId:'instance-a',browserInstanceId:'browser-a',runtimeExtensionId:'runtime-a',token:first.pairedToken,origin:'chrome-extension://runtime-a'});assert.deepEqual(second,{ok:true,paired:false});const rotated=auth.authenticateExtension({extensionId:'instance-a',browserInstanceId:'browser-a',runtimeExtensionId:'runtime-a',token:'bad',origin:'chrome-extension://runtime-a'});assert.equal(rotated.ok,true);assert.equal(rotated.paired,true);assert.equal(rotated.rotated,true);assert.notEqual(rotated.pairedToken,first.pairedToken);assert.equal(auth.authenticateExtension({extensionId:'instance-a',browserInstanceId:'browser-b',runtimeExtensionId:'runtime-a',token:null,origin:'chrome-extension://runtime-a'}).error,'extension_browser_id_mismatch');});
function browserAdapter(states){let index=0;const native=[];return {native,adapter:new BrowserUiAdapter({resolveTarget:async()=>({extensionId:'ext-a',tab:{id:10,windowId:1}}),focusTarget:async()=>({verified:true,focused:true}),finishTarget:async()=>({cleared:true}),snapshot:async()=>states[Math.min(index++,states.length-1)],runNativeInput:async(mode,value)=>{native.push({mode,value});return {ok:true};},sleepImpl:async()=>{},verifyTimeoutMs:100,verifyIntervalMs:20})};}
test('semantic Browser UI remains separate and verifiable',async()=>{for(const name of ['back','forward','reload','newtab','closetab','nexttab','addressbar'])assert.ok(BROWSER_COMMANDS[name]);const before={tabs:[{id:10,windowId:1}],active:{id:10,windowId:1}},after={tabs:[{id:10,windowId:1},{id:11,windowId:1}],active:{id:11,windowId:1}};const {adapter,native}=browserAdapter([before,after]);const result=await adapter.execute('newtab');assert.equal(result.delivered,true);assert.equal(result.verified,true);assert.deepEqual(native,[{mode:'combo',value:'Control+t'}]);});
test('Browser UI protocol is v5 and raw URLs are not returned as navigation tokens',()=>{assert.equal(PROTOCOL_VERSION,5);assert.notEqual(navigationToken('https://x.test/a?secret=1'),navigationToken('https://x.test/b?secret=2'));assert.equal(navigationToken('https://x.test/a?secret=1').includes('secret'),false);});
test('native Browser UI input fails closed off Windows',async()=>{const run=createWindowsInputRunner({platform:'linux'});await assert.rejects(()=>run('combo','Control+t'),/browser_ui_input_windows_only/);});
test('site key normalization is stable',()=>assert.equal(normalizeSiteKey('EXAMPLE.COM'),'example.com'));
