'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {LocalIdentityStore}=require('./src/local_identity');
const {BrowserManager}=require('./src/browser_manager');
const {TaskManager}=require('./src/task_manager');
const {PROTOCOL_VERSION:DEBUG_PROTOCOL_VERSION}=require('../body_cli');
const SOCKET_PROTOCOL=require('../SOCKET_PROTOCOL.json');

function tmp(name){return fs.mkdtempSync(path.join(os.tmpdir(),`${name}-`));}
function setup({tabsA=[1,2,3],tabsB=[1,4]}={}){const base=tmp('task-manager');const identity=new LocalIdentityStore(base,{env:{BODY_COMPANY_ID:'company-test',BODY_DEVICE_ID:'device-test'}});identity.registerBrowser({browserInstanceId:'browser-a',extensionInstanceId:'ext-a',runtimeExtensionId:'runtime'});identity.registerBrowser({browserInstanceId:'browser-b',extensionInstanceId:'ext-b',runtimeExtensionId:'runtime'});const browsers=new BrowserManager(identity);const item=(browserInstanceId,extensionId,tabs)=>({companyId:'company-test',deviceId:'device-test',browserInstanceId,extensionInstanceId:extensionId,extensionId,runtimeExtensionId:'runtime',connectedAt:1,lastSeenAt:1,activeTabId:tabs[0],tabs:new Map(tabs.map((id,i)=>[id,{id,active:i===0,siteKey:'youtube.com'}]))});browsers.registerExtension(item('browser-a','ext-a',tabsA));browsers.registerExtension(item('browser-b','ext-b',tabsB));return {base,identity,browsers,item};}

test('one Browser Instance may host many valid Tasks on different tabs',()=>{const {base,browsers}=setup();const tasks=new TaskManager(base,browsers);const a=tasks.create({taskId:'task-a',capability:'youtube.search',browserInstanceId:'browser-a',primaryTabId:1,tabIds:[1]});const b=tasks.create({taskId:'task-b',capability:'youtube.content_review',browserInstanceId:'browser-a',primaryTabId:2,tabIds:[2]});assert.equal(a.state,'READY');assert.equal(b.state,'READY');assert.equal(browsers.require('browser-a').state,'ONLINE');assert.equal(tasks.owners().length,2);});
test('one TaskWorkspace may own multiple tabs but a tab cannot belong to two active Tasks',()=>{const {base,browsers}=setup();const tasks=new TaskManager(base,browsers);const task=tasks.create({taskId:'multi',capability:'youtube.content_discovery',browserInstanceId:'browser-a',primaryTabId:1,tabIds:[1,3]});assert.deepEqual(task.workspace.tabIds,[1,3]);assert.throws(()=>tasks.create({taskId:'conflict',capability:'youtube.search',browserInstanceId:'browser-a',primaryTabId:3,tabIds:[3]}),/tab_already_owned/);});
test('dynamic TaskWorkspace may adopt additional tabs while preserving ownership isolation',()=>{const {base,browsers}=setup();const tasks=new TaskManager(base,browsers);tasks.create({taskId:'dynamic',capability:'youtube.content_discovery',browserInstanceId:'browser-a',primaryTabId:1,tabIds:[1],workspaceMode:'DYNAMIC'});tasks.start('dynamic');const updated=tasks.updateWorkspace('dynamic',{addTabIds:[2],primaryTabId:2});assert.equal(updated.workspace.mode,'DYNAMIC');assert.deepEqual(updated.workspace.tabIds,[1,2]);assert.equal(updated.workspace.primaryTabId,2);assert.equal(tasks.executionContext('dynamic',2,{autoStart:false}).tabId,2);assert.throws(()=>tasks.create({taskId:'conflict-dynamic',capability:'youtube.search',browserInstanceId:'browser-a',primaryTabId:2,tabIds:[2]}),/tab_already_owned/);});
test('dynamic TaskWorkspace survives a closed side-effect tab and chooses a surviving primary',()=>{const {base,browsers}=setup();const tasks=new TaskManager(base,browsers);tasks.create({taskId:'dynamic-close',capability:'youtube.content_discovery',browserInstanceId:'browser-a',primaryTabId:2,tabIds:[1,2],workspaceMode:'DYNAMIC'});tasks.start('dynamic-close');browsers.removeTabByExtension('ext-a',2);const reconcile=tasks.reconcileBrowser('browser-a'),task=tasks.get('dynamic-close');assert.deepEqual(reconcile.failedTasks,[]);assert.equal(reconcile.adjustedTasks.length,1);assert.equal(task.state,'RUNNING');assert.deepEqual(task.workspace.tabIds,[1]);assert.equal(task.workspace.primaryTabId,1);assert.equal(tasks.executionContext('dynamic-close',1,{autoStart:false}).tabId,1);});
test('Task execution cannot escape its Browser or owned tabs',()=>{const {base,browsers}=setup();const tasks=new TaskManager(base,browsers);tasks.create({taskId:'scoped',capability:'youtube.search',browserInstanceId:'browser-a',primaryTabId:1,tabIds:[1,2]});const ctx=tasks.executionContext('scoped',2);assert.equal(ctx.browserInstanceId,'browser-a');assert.equal(ctx.extensionInstanceId,'ext-a');assert.equal(ctx.tabId,2);assert.throws(()=>tasks.executionContext('scoped',4),/tab_not_owned_by_task/);assert.throws(()=>tasks.create({taskId:'wrong-browser-tab',capability:'youtube.search',browserInstanceId:'browser-b',primaryTabId:2,tabIds:[2]}),/tab_not_in_browser/);});
test('strict BODY execution context does not implicitly start a READY Task',()=>{const {base,browsers}=setup();const tasks=new TaskManager(base,browsers);tasks.create({taskId:'body-step',capability:'youtube.search',browserInstanceId:'browser-a',primaryTabId:1,tabIds:[1]});assert.equal(tasks.get('body-step').state,'READY');assert.throws(()=>tasks.executionContext('body-step','primary',{autoStart:false}),/task_not_executable:body-step:READY/);assert.equal(tasks.get('body-step').state,'READY');tasks.start('body-step');const ctx=tasks.executionContext('body-step','primary',{autoStart:false});assert.equal(ctx.tabId,1);assert.equal(tasks.get('body-step').state,'RUNNING');});
test('Task ownership survives daemon restart and valid extension reconnect',()=>{const {base,browsers,item}=setup();let tasks=new TaskManager(base,browsers);tasks.create({taskId:'persisted',capability:'youtube.search',browserInstanceId:'browser-a',primaryTabId:1,tabIds:[1,3]});tasks.flushSync();const reloadedIdentity=new LocalIdentityStore(base,{env:{BODY_COMPANY_ID:'company-test',BODY_DEVICE_ID:'device-test'}}),reloadedBrowsers=new BrowserManager(reloadedIdentity);tasks=new TaskManager(base,reloadedBrowsers);assert.equal(tasks.owners().length,2);const connected=reloadedBrowsers.registerExtension(item('browser-a','ext-a',[1,2,3])),reconcile=tasks.reconcileBrowser(connected.browserInstanceId);assert.deepEqual(reconcile.failedTasks,[]);assert.equal(tasks.get('persisted').state,'READY');});
test('running Task becomes RECOVERY_REQUIRED after daemon restart',()=>{const {base,browsers}=setup();let tasks=new TaskManager(base,browsers);tasks.create({taskId:'running',capability:'youtube.search',browserInstanceId:'browser-a',primaryTabId:1,tabIds:[1]});tasks.start('running');tasks.flushSync();const identity=new LocalIdentityStore(base,{env:{BODY_COMPANY_ID:'company-test',BODY_DEVICE_ID:'device-test'}}),reloadedBrowsers=new BrowserManager(identity);tasks=new TaskManager(base,reloadedBrowsers);assert.equal(tasks.get('running').state,'RECOVERY_REQUIRED');assert.throws(()=>tasks.executionContext('running',1),/task_not_executable/);assert.equal(tasks.owners().length,1);});
test('reconnect with missing workspace tab fails fixed Task instead of executing on another tab',()=>{const {base,browsers,item}=setup();let tasks=new TaskManager(base,browsers);tasks.create({taskId:'lost-tab',capability:'youtube.search',browserInstanceId:'browser-a',primaryTabId:1,tabIds:[1,3]});tasks.flushSync();const reloadedBrowsers=new BrowserManager(new LocalIdentityStore(base,{env:{BODY_COMPANY_ID:'company-test',BODY_DEVICE_ID:'device-test'}}));tasks=new TaskManager(base,reloadedBrowsers);const connected=reloadedBrowsers.registerExtension(item('browser-a','ext-a',[1,2])),reconcile=tasks.reconcileBrowser(connected.browserInstanceId);assert.deepEqual(reconcile.failedTasks,['lost-tab']);assert.equal(tasks.get('lost-tab').state,'FAILED');assert.equal(tasks.owners().length,0);});
test('control protocol v7 exposes BODY Contract v1 as the only production physical Brain boundary',()=>{assert.equal(DEBUG_PROTOCOL_VERSION,7);assert.equal(SOCKET_PROTOCOL.controlProtocolVersion,7);assert.equal(SOCKET_PROTOCOL.bodyContractVersion,'1.0');assert.deepEqual(SOCKET_PROTOCOL.brain.physicalActions,['BODY_STEP']);assert.match(SOCKET_PROTOCOL.brain.physicalActionRequirement,/exactly one Body step/);assert.equal(/Guardian grant/.test(SOCKET_PROTOCOL.brain.physicalActionRequirement),false);const server=fs.readFileSync(path.join(__dirname,'server.js'),'utf8');assert.match(server,/CONTROL_PROTOCOL_VERSION=7/);assert.match(server,/BODY_CONTRACT_VERSION/);assert.match(server,/msg\.type==='BODY_STEP'/);assert.equal(/msg\.type==='STRATEGY_EXECUTE'/.test(server),false);assert.equal(/msg\.type==='INTENT_EXECUTE'/.test(server),false);});
