'use strict';

const {bodyCapabilityCatalog}=require('./body_capabilities');
const {contextKey}=require('./world_model');
const {fold}=require('./topic_classifier');
const {FORMAT,formatKind,formatRelation}=require('./media_format');

const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0));
const jitter=(scale=1)=>(Math.random()-0.5)*scale;
const TRANSIENT_UI_RE=/(?:microphone|mic\b|micr[oô]|voice search|sử dụng micr[oô]|settings|cài đặt|account|tài khoản|notifications?|thông báo|upload|create|subscribe|đăng ký|like\b|share\b|comment\b)/iu;

function actionKey(action){return `${action.type}|${action.capability||''}|${action.target?.videoId||action.affordance?.index||''}|${action.query||''}|${action.tabId??''}`;}
function actionMemoryId(action){return `${action.capability||action.type}:${action.purpose||'general'}`;}
function recentPenalty(action,history=[]){const key=actionKey(action),recent=(history||[]).slice(-18);let hits=0;for(const row of recent)if(row.actionKey===key&&row.success===false)hits++;return Math.min(72,hits*18);}
function familyFailurePenalty(action,history=[]){const recent=(history||[]).slice(-24),memoryId=actionMemoryId(action);let hits=0;for(const row of recent){const rowId=`${row.capability||row.type}:${row.purpose||'general'}`;if(rowId===memoryId&&row.success===false&&row.changed===false)hits++;}return Math.min(120,hits*14);}
function candidateFailurePenalty(action,history=[]){const id=String(action.target?.videoId||'');if(!id)return 0;let hits=0;for(const row of (history||[]).slice(-40))if(String(row.videoId||'')===id&&row.success===false)hits++;return Math.min(140,hits*32);}
function noOpStreak(history=[]){let count=0;for(let i=(history||[]).length-1;i>=0;i--){const row=history[i];if(row.success===false&&row.changed===false)count++;else break;}return count;}
function memoryBonus(memory,id,context){const value=memory?.ucb?.(id,context,1.05);return Number.isFinite(value)?clamp(value,-12,16):0;}
function safeCandidateRatio(candidate,world){const r=candidate?.actionRect;if(!r)return 0;const width=Math.max(320,Number(world?.viewport?.width||1000)),height=Math.max(240,Number(world?.viewport?.height||700)),x=Number(r.x),y=Number(r.y),w=Number(r.width),h=Number(r.height);if(![x,y,w,h].every(Number.isFinite)||w<=0||h<=0)return 0;const x1=Math.max(8,x),y1=Math.max(105,y),x2=Math.min(width-8,x+w),y2=Math.min(height-24,y+h),vw=Math.max(0,x2-x1),vh=Math.max(0,y2-y1);return (vw*vh)/(w*h);}
function targetCandidateScore(candidate,world,targetFormat=FORMAT.UNKNOWN){let score=18+Number(candidate.targetProximity||0)*105;if(candidate.targetMatch)score+=1000;const safeRatio=safeCandidateRatio(candidate,world);score+=safeRatio>=0.42?10:-55;if(!world.history.some(row=>row.videoId===candidate.videoId&&row.success))score+=6;if(candidate.topic&&candidate.topic!=='unknown'&&!world.history.some(row=>row.topic===candidate.topic))score+=4;if(candidate.visible&&candidate.actionRect)score+=4;if(candidate.surface==='related')score+=2;if(candidate.surface==='search_results')score+=4;if(candidate.isRadio)score-=4;if(Number.isFinite(Number(candidate.position)))score+=Math.max(0,4-Math.log2(Math.max(1,Number(candidate.position))));const relation=formatRelation(targetFormat,candidate.mediaFormat);if(relation==='MATCH')score+=14;else if(relation==='MISMATCH')score-=500;else if(formatKind(targetFormat)!==FORMAT.UNKNOWN)score-=4;return score;}
function rectCenter(rect){if(!rect)return null;const x=Number(rect.centerX??(Number(rect.x||0)+Number(rect.width||0)/2)),y=Number(rect.centerY??(Number(rect.y||0)+Number(rect.height||0)/2));return Number.isFinite(x)&&Number.isFinite(y)?{x,y}:null;}
function words(value){return new Set(String(value||'').toLowerCase().normalize('NFD').replace(/\p{M}+/gu,'').split(/[^\p{L}\p{N}]+/u).filter(x=>x.length>=3));}
function overlapCount(a,b){let n=0;for(const x of a)if(b.has(x))n++;return n;}
function riskyAffordancePenalty(label=''){return TRANSIENT_UI_RE.test(String(label||''))?48:0;}

function affordanceActions(world,{textProbe=null,targetVocabulary=[],targetFormat=FORMAT.UNKNOWN}={}){
  const actions=[],targetWords=new Set((targetVocabulary||[]).flatMap(value=>[...words(value)])),targetKind=formatKind(targetFormat);
  for(const aff of (world.affordances||[]).slice(0,100)){
    if(aff.disabled||!aff.actionRect)continue;const center=rectCenter(aff.actionRect);if(!center)continue;const linkPath=String(aff.link?.path||''),shortLink=aff.link?.youtube===true&&/^\/shorts\//i.test(linkPath);if(targetKind===FORMAT.LONG_FORM&&shortLink)continue;
    const labelWords=words(aff.label),relevance=overlapCount(labelWords,targetWords),youtubeLink=aff.link?.youtube===true,formatBonus=targetKind===FORMAT.SHORT&&shortLink?18:0,risk=riskyAffordancePenalty(aff.label),base=1+relevance*9+(youtubeLink?2:0)+(aff.active?1:0)+formatBonus-risk,role=aff.role||aff.tag||'unknown',descriptor={index:aff.index,label:aff.label,role:aff.role,tag:aff.tag,link:aff.link};
    actions.push({type:'body_step',capability:'motor.click',affordance:descriptor,step:{kind:'motor',intent:{type:'click',x:center.x,y:center.y,width:Number(aff.actionRect.width||12),height:Number(aff.actionRect.height||12),role}},purpose:'activate_observed_affordance',baseUtility:base,expected:'environment_change'});
    actions.push({type:'body_step',capability:'motor.hover',affordance:descriptor,step:{kind:'motor',intent:{type:'hover',x:center.x,y:center.y,width:Number(aff.actionRect.width||12),height:Number(aff.actionRect.height||12),role}},purpose:'inspect_affordance_hover_state',baseUtility:base-8,expected:'pointer_or_affordance_change'});
    actions.push({type:'body_step',capability:'motor.moveTo',affordance:descriptor,step:{kind:'motor',intent:{type:'moveTo',x:center.x,y:center.y,role}},purpose:'position_at_observed_affordance',baseUtility:base-11,expected:'pointer_change'});
    if(['button','link'].includes(String(aff.role||'').toLowerCase())||['button','a'].includes(String(aff.tag||'').toLowerCase()))actions.push({type:'body_step',capability:'motor.doubleClick',affordance:descriptor,step:{kind:'motor',intent:{type:'doubleClick',x:center.x,y:center.y,width:Number(aff.actionRect.width||12),height:Number(aff.actionRect.height||12),role}},purpose:'probe_double_activation_when_single_activation_is_uninformative',baseUtility:base-18,expected:'environment_change'});
    if(String(aff.role||'').toLowerCase()==='slider'){const tx=clamp(center.x+Math.max(40,Number(aff.actionRect.width||100)*0.22),20,Number(world.viewport.width||1000)-20);actions.push({type:'body_step',capability:'motor.drag',affordance:descriptor,step:{kind:'motor',intent:{type:'drag',x:center.x,y:center.y,toX:tx,toY:center.y,width:Number(aff.actionRect.width||12),height:Number(aff.actionRect.height||12),role:'slider'}},purpose:'manipulate_observed_slider',baseUtility:base-6,expected:'control_state_change'});}
    if(aff.editable&&textProbe)actions.push({type:'body_step',capability:'motor.typeText',affordance:descriptor,step:{kind:'motor',intent:{type:'typeText',x:center.x,y:center.y,width:Number(aff.actionRect.width||300),height:Number(aff.actionRect.height||40),role:'textbox',text:String(textProbe)}},purpose:'type_task_derived_text_into_observed_editable_affordance',baseUtility:base+4,expected:'editable_value_change'});
  }
  return actions;
}

function genericBodyActions(world,{textProbe=null,targetVocabulary=[],targetFormat=FORMAT.UNKNOWN,noOpCount=0}={}){
  const catalog=bodyCapabilityCatalog(),actions=[];
  for(const action of catalog.browserUi){let utility=-24,purpose='available_browser_capability';if(action==='back'&&world.current.pageType!=='home'){utility=world.formatMismatch?72:(noOpCount>=2?70:5);purpose=world.formatMismatch?'exit_target_format_mismatch':noOpCount>=2?'recover_from_noop_blocker':'recover_or_branch';}else if(action==='forward'){utility=-8;purpose='inspect_forward_history';}else if(['reload','hardreload'].includes(action)){utility=noOpCount>=4?24:(world.environment.online?0:-6);purpose=noOpCount>=4?'recover_stale_environment':'refresh_environment';}else if(action==='stop'){utility=world.advertising.playingAd?2:-12;purpose='interrupt_current_navigation';}else if(action==='newtab'){utility=-8;purpose='open_parallel_branch';}else if(action==='closetab'){utility=world.tabs.length>1?-4:-30;purpose='prune_branch';}else if(action==='reopentab'){utility=-8;purpose='recover_closed_branch';}else if(['nexttab','prevtab'].includes(action)){utility=world.tabs.length>1?1:-30;purpose='inspect_workspace';}else if(action==='address'){utility=world.formatMismatch?24:(noOpCount>=3?18:0);purpose=world.formatMismatch?'leave_mismatched_format_surface':noOpCount>=3?'recover_environment_via_navigation':'direct_environment_navigation';}actions.push({type:'body_step',capability:`browser_ui.${action}`,step:{kind:'browser_ui',action},purpose,baseUtility:utility,expected:'observable_or_execution_fact'});}
  actions.push(...affordanceActions(world,{textProbe,targetVocabulary,targetFormat}));
  const active=world.controls.activeTarget,rect=active?.rect||active?.actionRect||null,center=rectCenter(rect),viewport=world.viewport||{width:1000,height:700};
  if(noOpCount>=2)actions.push({type:'body_step',capability:'motor.pressKey',step:{kind:'motor',intent:{type:'pressKey',key:'Escape'}},purpose:'dismiss_transient_overlay_or_menu',baseUtility:132+Math.min(48,noOpCount*6),expected:'overlay_or_focus_change'});
  if(center){actions.push({type:'body_step',capability:'motor.click',step:{kind:'motor',intent:{type:'click',x:center.x,y:center.y,width:Number(rect.width||12),height:Number(rect.height||12),role:active?.role||'unknown'}},purpose:'interact_active_affordance',baseUtility:-7,expected:'control_or_page_change'});actions.push({type:'body_step',capability:'motor.doubleClick',step:{kind:'motor',intent:{type:'doubleClick',x:center.x,y:center.y,width:Number(rect.width||12),height:Number(rect.height||12),role:active?.role||'unknown'}},purpose:'probe_double_activation',baseUtility:-18,expected:'control_or_page_change'});actions.push({type:'body_step',capability:'motor.hover',step:{kind:'motor',intent:{type:'hover',x:center.x,y:center.y,width:Number(rect.width||12),height:Number(rect.height||12),role:active?.role||'unknown'}},purpose:'reveal_hover_affordance',baseUtility:-10,expected:'pointer_or_dom_change'});actions.push({type:'body_step',capability:'motor.moveTo',step:{kind:'motor',intent:{type:'moveTo',x:center.x,y:center.y,role:active?.role||'unknown'}},purpose:'move_to_active_affordance',baseUtility:-14,expected:'pointer_change'});const tx=clamp(center.x+Math.min(140,Math.max(45,Number(viewport.width||1000)*0.12)),20,Number(viewport.width||1000)-20),ty=clamp(center.y+Math.min(90,Math.max(30,Number(viewport.height||700)*0.08)),20,Number(viewport.height||700)-20);actions.push({type:'body_step',capability:'motor.drag',step:{kind:'motor',intent:{type:'drag',x:center.x,y:center.y,toX:tx,toY:ty,width:Number(rect.width||12),height:Number(rect.height||12),role:active?.role||'unknown'}},purpose:'probe_draggable_affordance',baseUtility:-24,expected:'pointer_or_dom_change'});}
  if(active?.editable){actions.push({type:'body_step',capability:'motor.pressKey',step:{kind:'motor',intent:{type:'pressKey',key:'Escape'}},purpose:'escape_active_control',baseUtility:noOpCount>=2?95:-2,expected:'control_or_page_change'});actions.push({type:'body_step',capability:'motor.keyCombo',step:{kind:'motor',intent:{type:'keyCombo',key:'Control+a'}},purpose:'select_active_editable_text',baseUtility:-5,expected:'focus_preserved'});if(textProbe)actions.push({type:'body_step',capability:'motor.typeText',step:{kind:'motor',intent:{type:'typeText',x:center?.x||300,y:center?.y||100,width:Number(rect?.width||300),height:Number(rect?.height||40),role:'textbox',text:String(textProbe)}},purpose:'type_task_derived_text_into_active_control',baseUtility:-2,expected:'editable_value_change'});}
  const px=world.body.pointer?.known?Number(world.body.pointer.x||0):Math.round(Number(viewport.width||1000)*0.55),py=world.body.pointer?.known?Number(world.body.pointer.y||0):Math.round(Number(viewport.height||700)*0.55);actions.push({type:'body_step',capability:'motor.scrollVertical',step:{kind:'motor',intent:{type:'scrollVertical',delta:520}},purpose:'raw_vertical_environment_probe',baseUtility:world.formatMismatch?-22:(noOpCount>=2?-18:-7),expected:'scroll_or_dom_change'});actions.push({type:'body_step',capability:'motor.scrollHorizontal',step:{kind:'motor',intent:{type:'scrollHorizontal',delta:420}},purpose:'raw_horizontal_environment_probe',baseUtility:-22,expected:'scroll_or_dom_change'});actions.push({type:'body_step',capability:'motor.moveTo',step:{kind:'motor',intent:{type:'moveTo',x:px,y:py,role:'page'}},purpose:'motor_probe',baseUtility:-28,expected:'pointer_change'});return actions;
}

function actionFamily(action){if(action.type==='click_candidate')return 'candidate';if(action.type==='search')return 'search';if(action.type==='home')return 'home';if(action.type==='scroll')return `scroll:${action.direction||'any'}`;if(action.type==='tab_switch')return 'tab_switch';if(action.type==='dwell')return 'dwell';if(action.purpose==='dismiss_transient_overlay_or_menu'||action.purpose==='escape_active_control')return 'recovery_escape';return `body:${action.capability||action.type}`;}
function explorationPool(actions=[]){const best=new Map();for(const action of actions){const family=actionFamily(action),prior=best.get(family);if(!prior||Number(action.utility)>Number(prior.utility))best.set(family,action);}const representatives=[...best.values()].sort((a,b)=>b.utility-a.utility),top=Number(actions[0]?.utility||0),floor=top-105;return representatives.filter((row,index)=>index<12&&Number(row.utility)>=floor);}

class AutonomousAgentPlanner{
  constructor({memory=null,explorationBase=0.18}={}){this.memory=memory;this.explorationBase=clamp(explorationBase,0,0.8);this.catalog=bodyCapabilityCatalog();}
  inferTask(targetProfile,queryPlan){const targetFormat=formatKind(targetProfile?.mediaFormat);return {objective:'reach_video_id_without_direct_title_or_id_search',targetVideoId:String(targetProfile?.videoId||''),targetTopic:queryPlan?.fingerprint?.primaryTopic||queryPlan?.semanticTopics?.[0]||'unknown',targetLanguage:queryPlan?.targetLanguage||'unknown',targetFormat,targetFormatConfidence:Number(targetProfile?.mediaFormat?.confidence||0),targetFormatEvidence:targetProfile?.mediaFormat?.evidence||[],formatPolicy:targetFormat===FORMAT.UNKNOWN?'observe_both_until_format_known':targetFormat===FORMAT.SHORT?'prefer_short_exploration':'exclude_known_shorts_from_long_form_exploration',constraints:['do_not_search_target_video_id','do_not_search_exact_or_near_exact_target_title'],successEvidence:['current_video_id_equals_target','target_candidate_observed_then_opened'],capabilities:this.catalog};}
  deriveSubgoal(world,task={},history=[]){if(world.currentIsTarget)return {id:'maintain_or_expand_from_goal',reason:'target_is_current'};if(world.formatMismatch)return {id:'exit_target_format_mismatch',reason:`target_${formatKind(task.targetFormat)}_current_${formatKind(world.current.mediaFormat)}`};if(world.targetVisible)return {id:'open_observed_target',reason:`target_visible:${world.targetVisible.surface}`};const noOps=noOpStreak(history);if(noOps>=2)return {id:'recover_from_noop_blocker',reason:`consecutive_noop_failures:${noOps}`};const compatible=world.candidates.filter(c=>formatRelation(task.targetFormat,c.mediaFormat)!=='MISMATCH'),best=[...compatible].sort((a,b)=>Number(b.targetProximity||0)-Number(a.targetProximity||0))[0];if(best&&Number(best.targetProximity||0)>=0.42)return {id:'follow_high_evidence_neighbor',reason:`proximity:${best.targetProximity}`};if(world.advertising.playingAd)return {id:'restore_observable_content',reason:'advertising_interruption'};if(world.current.pageType==='search'&&compatible.length)return {id:'learn_from_search_neighborhood',reason:'compatible_search_results_available'};if(['watch','watch_radio','shorts'].includes(world.current.pageType)&&compatible.length)return {id:'expand_recommendation_graph',reason:'compatible_recommendations_available'};if(world.tabs.length>1)return {id:'inspect_workspace_branches',reason:'multiple_tabs'};return {id:'acquire_more_target_evidence',reason:'low_environment_evidence'};}
  generate(world,{task,queryPlan,dynamicQueries=[],usedQueries=new Set(),stagnation=0}={}){
    const history=world.history||[],context=contextKey(world),targetFormat=formatKind(task?.targetFormat),noOps=noOpStreak(history),subgoal=this.deriveSubgoal(world,task,history),actions=[];if(world.targetVisible){const c=world.targetVisible;actions.push({type:'click_candidate',capability:'motor.click',target:c,purpose:'open_target',baseUtility:1500,expected:'target_video_current'});}for(const c of world.candidates){const relation=formatRelation(targetFormat,c.mediaFormat);if(!c.targetMatch&&relation==='MISMATCH')continue;let utility=targetCandidateScore(c,world,targetFormat);if(!c.targetMatch)utility-=Math.min(125,Math.max(0,Number(stagnation||0)-1)*9+noOps*10);actions.push({type:'click_candidate',capability:'motor.click',target:c,purpose:relation==='MATCH'?'follow_same_format_environment_edge':'follow_environment_edge_with_unknown_format',baseUtility:utility,expected:`current_video:${c.videoId}`,formatRelation:relation});}
    const allQueries=[...(queryPlan?.plan||[]),...(dynamicQueries||[])];for(const row of allQueries){const used=usedQueries.has(fold(row.query)),learned=this.memory?.state?.queries?.[fold(row.query)];let utility=30+Number(row.score||0)*1.35+(used?-14:12)+Number(learned?.meanReward||0)*2;if(stagnation>=2)utility+=Math.min(125,(Number(stagnation)-1)*14);if(noOps>=2)utility+=Math.min(90,noOps*12);if(world.current.pageType==='search'&&used)utility-=8;if(world.formatMismatch)utility+=38;actions.push({type:'search',capability:'motor+search_control',query:row.query,queryRow:row,purpose:world.formatMismatch?'leave_mismatched_format_and_acquire_target_evidence':noOps>=2?'recover_with_new_target_anchored_search':'acquire_target_anchored_evidence',baseUtility:utility,expected:'search_results_for_query'});}
    if(['watch','watch_radio','shorts'].includes(world.current.pageType)&&!world.formatMismatch&&noOps<2)actions.push({type:'dwell',capability:'brain.wait',purpose:'observe_recommendation_change',baseUtility:12+Math.min(12,stagnation*2),expected:'time_or_recommendation_change'});const scrollBase=world.formatMismatch?-18:noOps>=2?-22:(world.candidates.some(c=>!c.visible)?18:5);actions.push({type:'scroll',capability:'motor.scrollVertical',direction:'down',purpose:world.formatMismatch?'low_priority_scroll_on_wrong_format':noOps>=2?'avoid_repeating_noop_scroll':'expand_visible_environment',baseUtility:scrollBase+Math.min(12,stagnation),expected:'scroll_or_candidate_change'});actions.push({type:'scroll',capability:'motor.scrollVertical',direction:'up',purpose:'reinspect_previous_environment',baseUtility:world.formatMismatch?-12:noOps>=2?-20:(stagnation>=3?8:-3),expected:'scroll_or_candidate_change'});if(world.controls.homeLink||world.current.pageType!=='home')actions.push({type:'home',capability:'motor.click|browser_ui.address',purpose:world.formatMismatch?'leave_mismatched_format_surface':noOps>=2?'recover_from_noop_via_home':'sample_home_environment',baseUtility:world.formatMismatch?52:noOps>=2?88+Math.min(50,noOps*5):(stagnation>=3?20:2),expected:'page_type_home'});for(const tab of world.tabs)if(tab.id!==world.tabId)actions.push({type:'tab_switch',capability:'tab.tab_switch',tabId:tab.id,purpose:noOps>=2?'inspect_parallel_branch_after_noop':'inspect_parallel_environment_branch',baseUtility:8+(tab.siteKey.includes('youtube.com')?10:0)+(world.formatMismatch?8:0)+(noOps>=2?28:0),expected:`active_tab:${tab.id}`});const textProbe=allQueries.find(row=>!usedQueries.has(fold(row.query)))?.query||allQueries[0]?.query||null,targetVocabulary=[...(queryPlan?.signals||[]).map(x=>x.term),...(queryPlan?.semanticTopics||[])];actions.push(...genericBodyActions(world,{textProbe,targetVocabulary,targetFormat,noOpCount:noOps}));
    for(const action of actions){const id=actionMemoryId(action);action.memoryId=id;action.context=context;action.subgoal=subgoal;action.actionKey=actionKey(action);action.utility=Number((Number(action.baseUtility||0)+memoryBonus(this.memory,id,context)-recentPenalty(action,history)-familyFailurePenalty(action,history)-candidateFailurePenalty(action,history)+jitter(1.1)).toFixed(3));}actions.sort((a,b)=>b.utility-a.utility);return {task,subgoal,context,targetFormat,noOpStreak:noOps,actions};
  }
  choose(plan,{stagnation=0}={}){const actions=plan.actions||[];if(!actions.length)return null;const epsilon=clamp(this.explorationBase+Math.min(0.32,Number(stagnation||0)*0.04),0,0.6);if(Math.random()<epsilon){const pool=explorationPool(actions);if(pool.length){const top=Number(pool[0].utility||0),weights=pool.map(row=>Math.max(1,Number(row.utility||0)-(top-100))),total=weights.reduce((a,b)=>a+b,0);let r=Math.random()*total;for(let i=0;i<pool.length;i++){r-=weights[i];if(r<=0)return {...pool[i],selection:'exploration_family_diverse',epsilon};}}}return {...actions[0],selection:'utility_max',epsilon};}
}

module.exports={AutonomousAgentPlanner,actionKey,actionMemoryId,targetCandidateScore,safeCandidateRatio,genericBodyActions,affordanceActions,recentPenalty,familyFailurePenalty,candidateFailurePenalty,noOpStreak,explorationPool};
