'use strict';

const {bodyCapabilityCatalog}=require('./body_capabilities');
const {contextKey}=require('./world_model');
const {fold}=require('./topic_classifier');
const {FORMAT,formatKind,formatRelation}=require('./media_format');
const {ACCOUNT_STATE}=require('./account_profile');
const {MODE,SURFACE,normalizeSurface}=require('./surface_policy');

const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0));
const jitter=(scale=1)=>(Math.random()-0.5)*scale;
function actionKey(action){return `${action.type}|${action.capability||''}|${action.target?.videoId||action.affordance?.index||''}|${action.query||''}|${action.tabId??''}`;}
function recentPenalty(action,history=[]){const key=actionKey(action),recent=(history||[]).slice(-12);let hits=0;for(const row of recent)if(row.actionKey===key&&row.success===false)hits++;return Math.min(40,hits*12);}
function memoryBonus(memory,id,context){const value=memory?.ucb?.(id,context,1.05);return Number.isFinite(value)?clamp(value,-8,12):8;}
function accountSurfaceBias(task,surface){return Number(task?.accountContext?.plan?.surfaceBias?.[surface]||0);}
function accountSearchBias(task){return Number(task?.accountContext?.plan?.searchUtility||0);}
function accountHomeBias(task){return Number(task?.accountContext?.plan?.homeUtility||0);}
function accountPreviewBias(task){return Number(task?.accountContext?.plan?.previewUtility||0);}
function accountNeighborClickBias(task){return Number(task?.accountContext?.plan?.neighborClickUtility||0);}
function accountHomeCheckBias(task){return Number(task?.accountContext?.plan?.homeCheckUtility||0);}
function coldStartState(task){return [ACCOUNT_STATE.NEW_ACCOUNT_EMPTY,ACCOUNT_STATE.COLD_START_WEAK].includes(task?.accountContext?.accountState);}
function targetCandidateScore(candidate,world,targetFormat=FORMAT.UNKNOWN){let score=20+Number(candidate.targetProximity||0)*120;if(candidate.targetMatch)score+=1000;if(!world.history.some(row=>row.videoId===candidate.videoId&&row.success))score+=8;if(candidate.topic&&candidate.topic!=='unknown'&&!world.history.some(row=>row.topic===candidate.topic))score+=6;if(candidate.visible&&candidate.actionRect)score+=5;if(candidate.surface==='related')score+=3;if(candidate.surface==='search_results')score+=2;if(candidate.isRadio)score-=3;if(Number.isFinite(Number(candidate.position)))score+=Math.max(0,5-Math.log2(Math.max(1,Number(candidate.position))));const relation=formatRelation(targetFormat,candidate.mediaFormat);if(relation==='MATCH')score+=18;else if(relation==='MISMATCH')score-=500;else if(formatKind(targetFormat)!==FORMAT.UNKNOWN)score-=3;return score;}
function rectCenter(rect){if(!rect)return null;const x=Number(rect.centerX??(Number(rect.x||0)+Number(rect.width||0)/2)),y=Number(rect.centerY??(Number(rect.y||0)+Number(rect.height||0)/2));return Number.isFinite(x)&&Number.isFinite(y)?{x,y}:null;}
function words(value){return new Set(String(value||'').toLowerCase().normalize('NFD').replace(/\p{M}+/gu,'').split(/[^\p{L}\p{N}]+/u).filter(x=>x.length>=3));}
function overlapCount(a,b){let n=0;for(const x of a)if(b.has(x))n++;return n;}
function policy(task){return task?.discoveryPolicy||{mode:MODE.AUTO,preferredSurface:SURFACE.AUTO,fallbackActive:false};}
function targetSurfaceAllowed(task,surface){const p=policy(task),preferred=normalizeSurface(p.preferredSurface);if(p.mode!==MODE.SURFACE_TEST||p.fallbackActive||preferred===SURFACE.AUTO)return true;return normalizeSurface(surface)===preferred;}
function discoverySurfaceBias(task,surface,{routeBootstrap=false}={}){
  const p=policy(task),preferred=normalizeSurface(p.preferredSurface),actual=normalizeSurface(surface);if(p.mode===MODE.AUTO||preferred===SURFACE.AUTO)return 0;
  if(p.mode===MODE.DIVERSITY)return actual===preferred?28:-2;
  if(p.mode===MODE.SURFACE_TEST){if(p.fallbackActive)return 0;if(actual===preferred)return 85;if(routeBootstrap)return 12;return -42;}
  return 0;
}
function surfaceTestMismatch(task,surface){const p=policy(task);return p.mode===MODE.SURFACE_TEST&&!p.fallbackActive&&normalizeSurface(p.preferredSurface)!==SURFACE.AUTO&&!targetSurfaceAllowed(task,surface);}
function affordanceActions(world,{textProbe=null,targetVocabulary=[],targetFormat=FORMAT.UNKNOWN}={}){
  const actions=[],targetWords=new Set((targetVocabulary||[]).flatMap(value=>[...words(value)])),targetKind=formatKind(targetFormat);
  for(const aff of (world.affordances||[]).slice(0,100)){
    if(aff.disabled||!aff.actionRect)continue;const center=rectCenter(aff.actionRect);if(!center)continue;const linkPath=String(aff.link?.path||''),shortLink=aff.link?.youtube===true&&/^\/shorts\//i.test(linkPath);if(targetKind===FORMAT.LONG_FORM&&shortLink)continue;
    const labelWords=words(aff.label),relevance=overlapCount(labelWords,targetWords),youtubeLink=aff.link?.youtube===true,formatBonus=targetKind===FORMAT.SHORT&&shortLink?18:0,base=1+relevance*9+(youtubeLink?2:0)+(aff.active?1:0)+formatBonus,role=aff.role||aff.tag||'unknown',descriptor={index:aff.index,label:aff.label,role:aff.role,tag:aff.tag,link:aff.link};
    actions.push({type:'body_step',capability:'motor.click',affordance:descriptor,step:{kind:'motor',intent:{type:'click',x:center.x,y:center.y,width:Number(aff.actionRect.width||12),height:Number(aff.actionRect.height||12),role}},purpose:'activate_observed_affordance',baseUtility:base,expected:'environment_change'});
    actions.push({type:'body_step',capability:'motor.hover',affordance:descriptor,step:{kind:'motor',intent:{type:'hover',x:center.x,y:center.y,width:Number(aff.actionRect.width||12),height:Number(aff.actionRect.height||12),role}},purpose:'inspect_affordance_hover_state',baseUtility:base-8,expected:'pointer_or_affordance_change'});
    actions.push({type:'body_step',capability:'motor.moveTo',affordance:descriptor,step:{kind:'motor',intent:{type:'moveTo',x:center.x,y:center.y,role}},purpose:'position_at_observed_affordance',baseUtility:base-11,expected:'pointer_change'});
    if(['button','link'].includes(String(aff.role||'').toLowerCase())||['button','a'].includes(String(aff.tag||'').toLowerCase()))actions.push({type:'body_step',capability:'motor.doubleClick',affordance:descriptor,step:{kind:'motor',intent:{type:'doubleClick',x:center.x,y:center.y,width:Number(aff.actionRect.width||12),height:Number(aff.actionRect.height||12),role}},purpose:'probe_double_activation_when_single_activation_is_uninformative',baseUtility:base-18,expected:'environment_change'});
    if(String(aff.role||'').toLowerCase()==='slider'){
      const tx=clamp(center.x+Math.max(40,Number(aff.actionRect.width||100)*0.22),20,Number(world.viewport.width||1000)-20);actions.push({type:'body_step',capability:'motor.drag',affordance:descriptor,step:{kind:'motor',intent:{type:'drag',x:center.x,y:center.y,toX:tx,toY:center.y,width:Number(aff.actionRect.width||12),height:Number(aff.actionRect.height||12),role:'slider'}},purpose:'manipulate_observed_slider',baseUtility:base-6,expected:'control_state_change'});
    }
    if(aff.editable&&textProbe)actions.push({type:'body_step',capability:'motor.typeText',affordance:descriptor,step:{kind:'motor',intent:{type:'typeText',x:center.x,y:center.y,width:Number(aff.actionRect.width||300),height:Number(aff.actionRect.height||40),role:'textbox',text:String(textProbe)}},purpose:'type_task_derived_text_into_observed_editable_affordance',baseUtility:base+4,expected:'editable_value_change'});
  }
  return actions;
}
function genericBodyActions(world,{textProbe=null,targetVocabulary=[],targetFormat=FORMAT.UNKNOWN}={}){
  const catalog=bodyCapabilityCatalog(),actions=[];
  for(const action of catalog.browserUi){let utility=-20,purpose='available_browser_capability';if(action==='back'&&world.current.pageType!=='home'){utility=world.formatMismatch?72:5;purpose=world.formatMismatch?'exit_target_format_mismatch':'recover_or_branch';}else if(action==='forward'){utility=-4;purpose='inspect_forward_history';}else if(['reload','hardreload'].includes(action)){utility=world.environment.online?0:-6;purpose='refresh_environment';}else if(action==='stop'){utility=world.advertising.playingAd?2:-8;purpose='interrupt_current_navigation';}else if(action==='newtab'){utility=-2;purpose='open_parallel_branch';}else if(action==='closetab'){utility=world.tabs.length>1?-1:-30;purpose='prune_branch';}else if(action==='reopentab'){utility=-5;purpose='recover_closed_branch';}else if(['nexttab','prevtab'].includes(action)){utility=world.tabs.length>1?1:-30;purpose='inspect_workspace';}else if(action==='address'){utility=world.formatMismatch?24:0;purpose=world.formatMismatch?'leave_mismatched_format_surface':'direct_environment_navigation';}actions.push({type:'body_step',capability:`browser_ui.${action}`,step:{kind:'browser_ui',action},purpose,baseUtility:utility,expected:'observable_or_execution_fact'});}
  actions.push(...affordanceActions(world,{textProbe,targetVocabulary,targetFormat}));
  const active=world.controls.activeTarget,rect=active?.rect||active?.actionRect||null,center=rectCenter(rect),viewport=world.viewport||{width:1000,height:700};
  if(center){actions.push({type:'body_step',capability:'motor.click',step:{kind:'motor',intent:{type:'click',x:center.x,y:center.y,width:Number(rect.width||12),height:Number(rect.height||12),role:active?.role||'unknown'}},purpose:'interact_active_affordance',baseUtility:-5,expected:'control_or_page_change'});actions.push({type:'body_step',capability:'motor.doubleClick',step:{kind:'motor',intent:{type:'doubleClick',x:center.x,y:center.y,width:Number(rect.width||12),height:Number(rect.height||12),role:active?.role||'unknown'}},purpose:'probe_double_activation',baseUtility:-16,expected:'control_or_page_change'});actions.push({type:'body_step',capability:'motor.hover',step:{kind:'motor',intent:{type:'hover',x:center.x,y:center.y,width:Number(rect.width||12),height:Number(rect.height||12),role:active?.role||'unknown'}},purpose:'reveal_hover_affordance',baseUtility:-8,expected:'pointer_or_dom_change'});actions.push({type:'body_step',capability:'motor.moveTo',step:{kind:'motor',intent:{type:'moveTo',x:center.x,y:center.y,role:active?.role||'unknown'}},purpose:'move_to_active_affordance',baseUtility:-12,expected:'pointer_change'});const tx=clamp(center.x+Math.min(140,Math.max(45,Number(viewport.width||1000)*0.12)),20,Number(viewport.width||1000)-20),ty=clamp(center.y+Math.min(90,Math.max(30,Number(viewport.height||700)*0.08)),20,Number(viewport.height||700)-20);actions.push({type:'body_step',capability:'motor.drag',step:{kind:'motor',intent:{type:'drag',x:center.x,y:center.y,toX:tx,toY:ty,width:Number(rect.width||12),height:Number(rect.height||12),role:active?.role||'unknown'}},purpose:'probe_draggable_affordance',baseUtility:-22,expected:'pointer_or_dom_change'});}
  if(active?.editable){actions.push({type:'body_step',capability:'motor.pressKey',step:{kind:'motor',intent:{type:'pressKey',key:'Escape'}},purpose:'escape_active_control',baseUtility:-2,expected:'control_or_page_change'});actions.push({type:'body_step',capability:'motor.keyCombo',step:{kind:'motor',intent:{type:'keyCombo',key:'Control+a'}},purpose:'select_active_editable_text',baseUtility:-3,expected:'focus_preserved'});if(textProbe)actions.push({type:'body_step',capability:'motor.typeText',step:{kind:'motor',intent:{type:'typeText',x:center?.x||300,y:center?.y||100,width:Number(rect?.width||300),height:Number(rect?.height||40),role:'textbox',text:String(textProbe)}},purpose:'type_task_derived_text_into_active_control',baseUtility:-1,expected:'editable_value_change'});}
  const px=world.body.pointer?.known?Number(world.body.pointer.x||0):Math.round(Number(viewport.width||1000)*0.55),py=world.body.pointer?.known?Number(world.body.pointer.y||0):Math.round(Number(viewport.height||700)*0.55);actions.push({type:'body_step',capability:'motor.scrollVertical',step:{kind:'motor',intent:{type:'scrollVertical',delta:520}},purpose:'raw_vertical_environment_probe',baseUtility:world.formatMismatch?-22:-7,expected:'scroll_or_dom_change'});actions.push({type:'body_step',capability:'motor.scrollHorizontal',step:{kind:'motor',intent:{type:'scrollHorizontal',delta:420}},purpose:'raw_horizontal_environment_probe',baseUtility:-18,expected:'scroll_or_dom_change'});actions.push({type:'body_step',capability:'motor.moveTo',step:{kind:'motor',intent:{type:'moveTo',x:px,y:py,role:'page'}},purpose:'motor_probe',baseUtility:-25,expected:'pointer_change'});return actions;
}

class AutonomousAgentPlanner{
  constructor({memory=null,explorationBase=0.18}={}){this.memory=memory;this.explorationBase=clamp(explorationBase,0,0.8);this.catalog=bodyCapabilityCatalog();}
  inferTask(targetProfile,queryPlan,accountContext=null,discoveryPolicy=null){const targetFormat=formatKind(targetProfile?.mediaFormat),surfacePolicy=discoveryPolicy||{mode:MODE.AUTO,preferredSurface:SURFACE.AUTO,fallbackActive:false};return {objective:'reach_video_id_without_direct_title_or_id_search',targetVideoId:String(targetProfile?.videoId||''),targetTopic:queryPlan?.fingerprint?.primaryTopic||queryPlan?.semanticTopics?.[0]||'unknown',targetLanguage:queryPlan?.targetLanguage||'unknown',targetFormat,targetFormatConfidence:Number(targetProfile?.mediaFormat?.confidence||0),targetFormatEvidence:targetProfile?.mediaFormat?.evidence||[],formatPolicy:targetFormat===FORMAT.UNKNOWN?'observe_both_until_format_known':targetFormat===FORMAT.SHORT?'prefer_short_exploration':'exclude_known_shorts_from_long_form_exploration',accountContext:accountContext||null,discoveryPolicy:surfacePolicy,constraints:['do_not_search_target_video_id','do_not_search_exact_or_near_exact_target_title','account_history_is_context_not_direct_target_navigation','brain_generated_activity_is_not_preexisting_user_habit','do_not_use_target_as_preview_seed',...(surfacePolicy.mode===MODE.SURFACE_TEST?['prefer_target_open_from_requested_surface_until_fallback']:[])],successEvidence:['current_video_id_equals_target','target_candidate_observed_then_opened'],capabilities:this.catalog};}
  deriveSubgoal(world,task={}){
    if(world.currentIsTarget)return {id:'maintain_or_expand_from_goal',reason:'target_is_current'};
    if(world.formatMismatch)return {id:'exit_target_format_mismatch',reason:`target_${formatKind(task.targetFormat)}_current_${formatKind(world.current.mediaFormat)}`};
    if(world.targetVisible&&targetSurfaceAllowed(task,world.targetVisible.surface))return {id:'open_observed_target',reason:`target_visible:${world.targetVisible.surface}`};
    if(world.targetVisible&&surfaceTestMismatch(task,world.targetVisible.surface))return {id:'continue_surface_test_route',reason:`target_visible_on_nonpreferred_surface:${world.targetVisible.surface}`};
    const runtime=task.accountContext?.runtime||{},state=task.accountContext?.accountState;
    if([ACCOUNT_STATE.NEW_ACCOUNT_EMPTY,ACCOUNT_STATE.COLD_START_WEAK].includes(state)){
      if(runtime.homeCheckDue)return {id:'measure_personalization_home',reason:'confirmed_preview_requires_home_measurement'};
      if(!runtime.personalizationSeeded&&world.current.pageType==='search')return {id:'seed_personalization_with_preview',reason:`account_state:${state}`};
      if(!runtime.personalizationSeeded&&world.current.pageType==='home'&&!world.candidates.length)return {id:'bootstrap_cold_start_search',reason:'home_has_no_candidates'};
    }
    const compatible=world.candidates.filter(c=>formatRelation(task.targetFormat,c.mediaFormat)!=='MISMATCH'),best=[...compatible].sort((a,b)=>Number(b.targetProximity||0)-Number(a.targetProximity||0))[0];if(best&&Number(best.targetProximity||0)>=0.28)return {id:'follow_high_evidence_neighbor',reason:`proximity:${best.targetProximity}`};const relation=task.accountContext?.relationship?.kind;if(['RETURNING_TARGET','FAMILIAR_SOURCE','FAMILIAR_TOPIC'].includes(relation)&&['home','watch','watch_radio','shorts'].includes(world.current.pageType))return {id:'exploit_personalized_account_graph',reason:`account_relationship:${relation}`};if(relation==='NOVEL_TOPIC'&&world.current.pageType==='home')return {id:'bridge_out_of_account_habits',reason:'target_novel_for_account'};if(world.advertising.playingAd)return {id:'restore_observable_content',reason:'advertising_interruption'};if(world.current.pageType==='search'&&compatible.length)return {id:'learn_from_search_neighborhood',reason:'compatible_search_results_available'};if(['watch','watch_radio','shorts'].includes(world.current.pageType)&&compatible.length)return {id:'expand_recommendation_graph',reason:'compatible_recommendations_available'};if(world.tabs.length>1)return {id:'inspect_workspace_branches',reason:'multiple_tabs'};return {id:'acquire_more_target_evidence',reason:'low_environment_evidence'};
  }
  generate(world,{task,queryPlan,dynamicQueries=[],usedQueries=new Set(),stagnation=0}={}){
    const context=contextKey(world),targetFormat=formatKind(task?.targetFormat),subgoal=this.deriveSubgoal(world,task),actions=[],runtime=task?.accountContext?.runtime||{},isColdStart=coldStartState(task),previewed=new Set(runtime.previewedVideoIds||[]),seeded=isColdStart&&runtime.personalizationSeeded===true,pref=normalizeSurface(task?.discoveryPolicy?.preferredSurface);
    if(world.targetVisible&&targetSurfaceAllowed(task,world.targetVisible.surface)){const c=world.targetVisible;actions.push({type:'click_candidate',capability:'motor.click',target:c,purpose:'open_target',baseUtility:1500+discoverySurfaceBias(task,c.surface),expected:'target_video_current'});}
    for(const c of world.candidates){const relation=formatRelation(targetFormat,c.mediaFormat);if(!c.targetMatch&&relation==='MISMATCH')continue;if(c.targetMatch&&!targetSurfaceAllowed(task,c.surface))continue;const routeBootstrap=task?.discoveryPolicy?.mode===MODE.SURFACE_TEST&&[SURFACE.RELATED,SURFACE.MIX,SURFACE.HOME].includes(pref)&&c.surface===SURFACE.SEARCH&&!c.targetMatch,neighborBias=c.targetMatch?0:(seeded?0:accountNeighborClickBias(task)),seededSurfaceBonus=seeded&&['home_feed','related'].includes(c.surface)?28:0,surfaceBias=discoverySurfaceBias(task,c.surface,{routeBootstrap});actions.push({type:'click_candidate',capability:'motor.click',target:c,purpose:relation==='MATCH'?'follow_same_format_environment_edge':'follow_environment_edge_with_unknown_format',baseUtility:targetCandidateScore(c,world,targetFormat)+accountSurfaceBias(task,c.surface)+neighborBias+seededSurfaceBonus+surfaceBias,expected:`current_video:${c.videoId}`,formatRelation:relation});
      if(isColdStart&&!runtime.personalizationSeeded&&world.current.pageType==='search'&&c.surface==='search_results'&&!c.targetMatch&&c.visible&&c.actionRect&&!previewed.has(String(c.videoId))){const previewScore=38+Number(c.targetProximity||0)*95+accountPreviewBias(task)+(relation==='MATCH'?16:0)+(Number.isFinite(Number(c.position))?Math.max(0,7-Math.log2(Math.max(1,Number(c.position)))):0)+discoverySurfaceBias(task,SURFACE.SEARCH,{routeBootstrap:pref!==SURFACE.SEARCH});actions.push({type:'preview_candidate',capability:'motor.hover+preview_wait',target:c,purpose:'seed_personalization_with_confirmed_preview',baseUtility:previewScore,expected:`preview_playing:${c.videoId}`,formatRelation:relation});}
    }
    const allQueries=[...(queryPlan?.plan||[]),...(dynamicQueries||[])];for(const row of allQueries){const used=usedQueries.has(fold(row.query)),learned=this.memory?.state?.queries?.[fold(row.query)],searchBias=seeded?0:accountSearchBias(task),routeBootstrap=task?.discoveryPolicy?.mode===MODE.SURFACE_TEST&&pref!==SURFACE.SEARCH;let utility=32+Number(row.score||0)*1.5+(used?-12:10)+Number(learned?.meanReward||0)*2+searchBias+discoverySurfaceBias(task,SURFACE.SEARCH,{routeBootstrap});if(stagnation>=2)utility+=10;if(world.current.pageType==='search'&&used)utility-=5;if(world.formatMismatch)utility+=38;if(isColdStart&&runtime.homeCheckDue)utility-=55;if(seeded)utility-=18;actions.push({type:'search',capability:'motor+search_control',query:row.query,queryRow:row,purpose:world.formatMismatch?'leave_mismatched_format_and_acquire_target_evidence':isColdStart&&!runtime.personalizationSeeded?'bootstrap_target_anchored_search':'acquire_target_anchored_evidence',baseUtility:utility,expected:'search_results_for_query'});}
    if(['watch','watch_radio','shorts'].includes(world.current.pageType)&&!world.formatMismatch)actions.push({type:'dwell',capability:'brain.wait',purpose:'observe_recommendation_change',baseUtility:12+Math.min(12,stagnation*2),expected:'time_or_recommendation_change'});
    const scrollBase=world.formatMismatch?-18:(world.candidates.some(c=>!c.visible)?18:5);actions.push({type:'scroll',capability:'motor.scrollVertical',direction:'down',purpose:world.formatMismatch?'low_priority_scroll_on_wrong_format':'expand_visible_environment',baseUtility:scrollBase+stagnation*2,expected:'scroll_or_candidate_change'});actions.push({type:'scroll',capability:'motor.scrollVertical',direction:'up',purpose:'reinspect_previous_environment',baseUtility:world.formatMismatch?-12:(stagnation>=3?8:-3),expected:'scroll_or_candidate_change'});
    if(world.controls.homeLink||world.current.pageType!=='home'){let homeUtility=world.formatMismatch?52:(stagnation>=3?20:2)+accountHomeBias(task)+discoverySurfaceBias(task,SURFACE.HOME,{routeBootstrap:pref!==SURFACE.HOME});if(isColdStart&&runtime.homeCheckDue)homeUtility+=accountHomeCheckBias(task);if(seeded)homeUtility+=36;actions.push({type:'home',capability:'motor.click|browser_ui.address',purpose:world.formatMismatch?'leave_mismatched_format_surface':isColdStart&&runtime.homeCheckDue?'measure_home_after_preview':'sample_home_environment',baseUtility:homeUtility,expected:'page_type_home'});}
    for(const tab of world.tabs)if(tab.id!==world.tabId)actions.push({type:'tab_switch',capability:'tab.tab_switch',tabId:tab.id,purpose:'inspect_parallel_environment_branch',baseUtility:8+(tab.siteKey.includes('youtube.com')?10:0)+(world.formatMismatch?8:0),expected:`active_tab:${tab.id}`});const textProbe=allQueries.find(row=>!usedQueries.has(fold(row.query)))?.query||allQueries[0]?.query||null,targetVocabulary=[...(queryPlan?.signals||[]).map(x=>x.term),...(queryPlan?.semanticTopics||[])];actions.push(...genericBodyActions(world,{textProbe,targetVocabulary,targetFormat}));
    const history=world.history||[];for(const action of actions){const id=action.capability||action.type;action.context=context;action.subgoal=subgoal;action.actionKey=actionKey(action);action.utility=Number((Number(action.baseUtility||0)+memoryBonus(this.memory,id,context)-recentPenalty(action,history)+jitter(1.4)).toFixed(3));}actions.sort((a,b)=>b.utility-a.utility);return {task,subgoal,context,targetFormat,accountState:task?.accountContext?.accountState||null,accountRelationship:task?.accountContext?.relationship?.kind||null,accountPlanMode:task?.accountContext?.plan?.mode||null,discoveryMode:task?.discoveryPolicy?.mode||MODE.AUTO,preferredSurface:task?.discoveryPolicy?.preferredSurface||SURFACE.AUTO,surfaceFallbackActive:task?.discoveryPolicy?.fallbackActive===true,actions};
  }
  choose(plan,{stagnation=0}={}){const actions=plan.actions||[];if(!actions.length)return null;const epsilon=clamp(this.explorationBase+Math.min(0.35,Number(stagnation||0)*0.045),0,0.65);if(Math.random()<epsilon){const pool=actions.slice(0,Math.min(8,actions.length)),weights=pool.map((_,i)=>Math.max(1,pool.length-i)),total=weights.reduce((a,b)=>a+b,0);let r=Math.random()*total;for(let i=0;i<pool.length;i++){r-=weights[i];if(r<=0)return {...pool[i],selection:'exploration',epsilon};}}return {...actions[0],selection:'utility_max',epsilon};}
}

module.exports={AutonomousAgentPlanner,actionKey,targetCandidateScore,genericBodyActions,affordanceActions,recentPenalty,accountSurfaceBias,accountSearchBias,accountHomeBias,accountPreviewBias,accountNeighborClickBias,accountHomeCheckBias,coldStartState,targetSurfaceAllowed,discoverySurfaceBias,surfaceTestMismatch};
