'use strict';

const {fold}=require('./topic_classifier');
const {FORMAT,classifyMediaFormat,formatKind,formatRelation}=require('./media_format');

function num(value,fallback=null){const n=Number(value);return Number.isFinite(n)?n:fallback;}
function routeKey(semantic={}){const r=semantic.route||{};return `${r.pageType||'other'}|${r.videoId||''}|${r.listId||''}|${r.searchQueryFingerprint?.fnv1a32||''}`;}
function browserUiKey(browserUi={}){return `${browserUi.observed===true?'1':'0'}|${browserUi.signature||''}|${browserUi.reason||''}|${browserUi.focusedControl?.controlType||''}|${browserUi.focusedControl?.name||''}`;}
function selectionKey(semantic={}){const doc=semantic?.selection||{},input=semantic?.controls?.searchInput||{},sel=input.selection||{};return `${doc.available===true?'1':'0'}:${doc.collapsed===false?'1':'0'}:${num(doc.selectedLength,0)}:${doc.textFingerprint?.fnv1a32||''}|${input.active===true?'1':'0'}:${input.valueFingerprint?.fnv1a32||''}:${sel.available===true?'1':'0'}:${sel.fullSelection===true?'1':'0'}:${num(sel.start,-1)}:${num(sel.end,-1)}`;}
function observationSignature({semantic=null,browser=null,tabId=null,browserUi=null}={}){const tabs=(browser?.tabs||[]).map(t=>`${Number(t.id)}:${t.active?'1':'0'}:${t.navigationToken||''}:${t.siteKey||''}`).sort().join('|');const affordances=(semantic?.affordances||[]).slice(0,40).map(a=>`${a.tag||''}:${a.role||''}:${a.labelFingerprint?.fnv1a32||''}:${a.active?'1':'0'}`).join('|');return `${Number(tabId)}|${routeKey(semantic||{})}|${num(semantic?.viewport?.scrollY,0)}|${tabs}|${affordances}|${selectionKey(semantic||{})}|${browserUiKey(browserUi||{})}`;}
function tabNode(tab={}){return {id:Number(tab.id),active:tab.active===true,windowId:num(tab.windowId),siteKey:String(tab.siteKey||''),title:String(tab.title||''),navigationToken:tab.navigationToken||null,navigationEpoch:num(tab.navigationEpoch),status:tab.status||null};}
function rawRepresentations(candidate={}){
  if(Array.isArray(candidate?.representations)&&candidate.representations.length)return candidate.representations.slice(0,12);
  const legacyPoint=candidate?.actionPoint&&candidate?.evidence?.hitOwned===true?[{x:Number(candidate.actionPoint.x),y:Number(candidate.actionPoint.y),owned:true,blocker:null}]:[];return [{visible:candidate?.visible===true,visibleRect:candidate?.visibleRect||null,hitTested:candidate?.hitTested===true,hitSamples:Array.isArray(candidate?.hitSamples)?candidate.hitSamples:legacyPoint,evidence:candidate?.evidence||{},actionRect:candidate?.actionRect||null}];
}
function pointDistance(point,rect){if(!point||!rect)return Number.POSITIVE_INFINITY;const cx=Number(rect.centerX??(Number(rect.x||0)+Number(rect.width||0)/2)),cy=Number(rect.centerY??(Number(rect.y||0)+Number(rect.height||0)/2));return Math.hypot(Number(point.x)-cx,Number(point.y)-cy);}
function assessRepresentation(rep={},index=0){
  const evidence=rep?.evidence||{},legacyPoint=rep?.actionPoint&&evidence.hitOwned===true?[{x:Number(rep.actionPoint.x),y:Number(rep.actionPoint.y),owned:true,blocker:null}]:[],samples=Array.isArray(rep?.hitSamples)?rep.hitSamples:legacyPoint,owned=samples.filter(row=>row?.owned===true&&Number.isFinite(Number(row.x))&&Number.isFinite(Number(row.y))),actionRect=rep?.actionRect||null,visibleRect=rep?.visibleRect||null,geometryKnown=evidence.geometryKnown===true||Boolean(actionRect),rectIntersectsViewport=evidence.rectIntersectsViewport===true||Boolean(visibleRect),hitTested=rep?.hitTested===true||samples.length>0,hardStyleHidden=Boolean(evidence.explicitHidden||evidence.inert||evidence.displayNone||evidence.visibilityHidden||evidence.opacityZero);
  const chosen=[...owned].sort((a,b)=>pointDistance(a,visibleRect||actionRect)-pointDistance(b,visibleRect||actionRect))[0]||null,actionPoint=chosen?{x:Number(chosen.x),y:Number(chosen.y)}:null,actionable=Boolean(actionPoint);
  const score=(geometryKnown?2:0)+(rectIntersectsViewport?4:0)+(visibleRect?8:0)+(hitTested?2:0)+(owned.length?32:0)+(actionable?64:0)-(hardStyleHidden?24:0);
  const reason=actionable?'owned_hit_sample':!geometryKnown?'no_geometry':!rectIntersectsViewport?'outside_viewport':hardStyleHidden?'style_hidden_evidence':hitTested?'no_owned_hit_sample':'hit_test_unavailable';
  return {index,score,actionable,reason,actionPoint,actionRect,visibleRect,visible:rep?.visible===true,geometryKnown,rectIntersectsViewport,rectFullyInViewport:evidence.rectFullyInViewport===true,hitTested,hitOwned:owned.length>0,ownedHitCount:owned.length,hitSampleCount:samples.length,hardStyleHidden,explicitHidden:evidence.explicitHidden===true,inert:evidence.inert===true,ariaHidden:evidence.ariaHidden===true,displayNone:evidence.displayNone===true,visibilityHidden:evidence.visibilityHidden===true,opacityZero:evidence.opacityZero===true,clippedByContainer:evidence.clippedByContainer===true,clippedRect:evidence.clippedRect||null,evidence};
}
function candidateInteractionState(candidate={}){
  const representations=rawRepresentations(candidate),assessments=representations.map((rep,index)=>assessRepresentation(rep,index)).sort((a,b)=>b.score-a.score||a.index-b.index),best=assessments[0]||assessRepresentation({},0),exists=Boolean(candidate?.videoId);
  return {...best,exists,representationCount:representations.length,assessments};
}
function actionabilityState(candidate={}){return candidate?.actionability&&candidate.actionability.assessments?candidate.actionability:candidateInteractionState(candidate);}
function candidateActionabilityKey(candidate={}){const s=actionabilityState(candidate);return `${s.exists?'1':'0'}:${s.score}:${s.reason}:${s.representationCount}:${s.index}`;}
function finiteActionRect(rect){if(!rect)return null;const x=Number(rect.x),y=Number(rect.y),width=Number(rect.width),height=Number(rect.height);return [x,y,width,height].every(Number.isFinite)&&width>0&&height>0?{x,y,width,height,centerX:Number(rect.centerX??(x+width/2)),centerY:Number(rect.centerY??(y+height/2))}:null;}
function interactionBand(world={}){const width=Math.max(320,Number(world?.viewport?.width||1000)),height=Math.max(240,Number(world?.viewport?.height||700)),top=Math.min(Math.max(72,height*0.12),Math.max(72,height-120)),bottom=Math.max(top+80,height-Math.max(20,height*0.04));return {left:8,right:width-8,top,bottom,width,height,centerX:width/2,centerY:(top+bottom)/2};}
function rectPositionMetrics(rect,band){const r=finiteActionRect(rect);if(!r)return null;const verticalGap=r.y+r.height<band.top?band.top-(r.y+r.height):r.y>band.bottom?r.y-band.bottom:0,horizontalGap=r.x+r.width<band.left?band.left-(r.x+r.width):r.x>band.right?r.x-band.right:0,distancePx=Math.hypot(verticalGap,horizontalGap),centerOffsetY=r.centerY-band.centerY,centerOffsetX=r.centerX-band.centerX,verticalRelation=r.y+r.height<band.top?'above':r.y>band.bottom?'below':'intersects',horizontalRelation=r.x+r.width<band.left?'left':r.x>band.right?'right':'intersects';return {rect:r,distancePx:Number(distancePx.toFixed(3)),verticalGapPx:Number(verticalGap.toFixed(3)),horizontalGapPx:Number(horizontalGap.toFixed(3)),centerOffsetY:Number(centerOffsetY.toFixed(3)),centerOffsetX:Number(centerOffsetX.toFixed(3)),verticalRelation,horizontalRelation};}
function candidatePositionState(candidate={},world={}){
  const actionability=actionabilityState(candidate),band=interactionBand(world),assessments=Array.isArray(actionability.assessments)?actionability.assessments:[actionability],rows=[];
  for(const assessment of assessments){const metrics=rectPositionMetrics(assessment?.actionRect||assessment?.visibleRect,band);if(metrics)rows.push({assessment,metrics});}
  rows.sort((a,b)=>(a.assessment.actionable===true?0:1)-(b.assessment.actionable===true?0:1)||a.metrics.distancePx-b.metrics.distancePx||Math.abs(a.metrics.centerOffsetY)-Math.abs(b.metrics.centerOffsetY)||Number(a.assessment.index||0)-Number(b.assessment.index||0));
  const best=rows[0]||null,distancePx=best?.metrics?.distancePx??null,scale=distancePx==null?'unknown':distancePx<=band.height*0.25?'near':distancePx<=band.height?'medium':'far';
  return {exists:Boolean(candidate?.videoId),videoId:String(candidate?.videoId||''),surface:String(candidate?.surface||'unknown'),actionable:actionability.actionable===true,reason:actionability.reason||'unknown',score:Number(actionability.score||0),geometryKnown:Boolean(best),representationIndex:best?.assessment?.index??actionability.index??0,distancePx,verticalGapPx:best?.metrics?.verticalGapPx??null,horizontalGapPx:best?.metrics?.horizontalGapPx??null,centerOffsetY:best?.metrics?.centerOffsetY??null,centerOffsetX:best?.metrics?.centerOffsetX??null,verticalRelation:best?.metrics?.verticalRelation||'unknown',horizontalRelation:best?.metrics?.horizontalRelation||'unknown',distanceBucket:scale,actionRect:best?.metrics?.rect||actionability.actionRect||null,band};
}
function candidatePositionContext(world={},candidate={}){
  const p=candidatePositionState(candidate,world),page=String(world?.current?.pageType||'other'),surface=String(candidate?.surface||'unknown'),blocked=p.actionable?'actionable':p.reason||'blocked';return `effect_model_v2|${page}|${surface}|${p.verticalRelation}|${p.distanceBucket}|${blocked}`;
}
function candidateNode(candidate={}){const apiFormat=formatKind(candidate.youtubeApi?.mediaFormat),routeFormat=classifyMediaFormat({routePath:candidate.path||''}),mediaFormat=apiFormat!==FORMAT.UNKNOWN?apiFormat:routeFormat.kind,actionability=candidateInteractionState(candidate);return {videoId:String(candidate.videoId||''),surface:String(candidate.surface||'unknown'),position:num(candidate.position),visible:actionability.visible,actionable:actionability.actionable,reason:actionability.reason,hitTested:actionability.hitTested,actionPoint:actionability.actionPoint,visibleRect:actionability.visibleRect,actionRect:actionability.actionRect,evidence:actionability.evidence,actionability,representationIndex:actionability.index,representationCount:actionability.representationCount,representations:rawRepresentations(candidate),path:String(candidate.path||''),isRadio:candidate.isRadio===true,title:String(candidate.youtubeApi?.title||candidate.title||''),channel:String(candidate.youtubeApi?.channelTitle||candidate.channel||''),topic:String(candidate.classification?.primary||'unknown'),confidence:num(candidate.classification?.confidence,0),targetMatch:candidate.targetMatch===true,targetProximity:num(candidate.targetProximity,0),mediaFormat,mediaFormatConfidence:num(candidate.youtubeApi?.mediaFormat?.confidence,routeFormat.confidence),mediaFormatEvidence:candidate.youtubeApi?.mediaFormat?.evidence||routeFormat.evidence||[],metadataAvailable:Boolean(candidate.youtubeApi)};}
function affordanceNode(row={}){const interaction=assessRepresentation(row,0);return {index:num(row.index),tag:String(row.tag||''),role:String(row.role||''),type:String(row.type||''),editable:row.editable===true,disabled:row.disabled===true,label:String(row.label||''),labelFingerprint:row.labelFingerprint||null,link:row.link||null,active:row.active===true,state:row.state||{},actionRect:row.actionRect||null,interactionPoint:interaction.actionPoint,interaction};}
function browserUiNode(row={}){return {available:row.available===true,observed:row.observed===true,reason:row.reason||null,confidence:row.confidence||'unknown',source:row.source||null,observedAt:num(row.observedAt),signature:row.signature||null,window:row.window||null,focusedControl:row.focusedControl||null,addressBar:row.addressBar||null,tabs:Array.isArray(row.tabs)?row.tabs:[],controls:Array.isArray(row.controls)?row.controls:[]};}
function buildWorld({observation=null,semantic=null,snapshot=null,browser=null,tabId=null,target=null,history=[]}={}){
  const route=semantic?.route||{},controls=semantic?.controls||{},advertising=semantic?.advertising||{},page=observation?.content?.page||{},activeTarget=observation?.control?.activeTarget||page.activeTarget||null,candidates=(snapshot?.candidates||[]).map(candidateNode),affordances=(semantic?.affordances||[]).map(affordanceNode),browserUi=browserUiNode(observation?.browserUi||{});
  const pageType=String(snapshot?.pageType||route.pageType||'other'),snapshotFormat=formatKind(snapshot?.currentMediaFormat),routeFormat=pageType==='shorts'?FORMAT.SHORT:classifyMediaFormat({routePath:route.path||''}).kind,currentFormat=snapshotFormat!==FORMAT.UNKNOWN?snapshotFormat:routeFormat;
  const current={videoId:String(snapshot?.currentVideoId||route.videoId||''),title:String(snapshot?.currentTitle||''),topic:String(snapshot?.currentTopic||'unknown'),pageType,mediaFormat:currentFormat};const tabs=(browser?.tabs||[]).map(tabNode),knownTopics=[...new Set(candidates.map(x=>x.topic).filter(Boolean))],targetVisible=candidates.find(x=>x.targetMatch)||null,targetFormat=formatKind(target?.mediaFormat||target?.targetFormat),currentFormatRelation=formatRelation(targetFormat,currentFormat);
  return {observedAt:Date.now(),signature:observationSignature({semantic,browser,tabId,browserUi}),tabId:Number(tabId),tabs,browserUi,current,targetFormat,currentFormatRelation,formatMismatch:currentFormatRelation==='MISMATCH',route:{pageType:current.pageType,videoId:current.videoId,listId:route.listId||null,searchQueryFingerprint:route.searchQueryFingerprint||null},viewport:{width:num(semantic?.viewport?.width,1000),height:num(semantic?.viewport?.height,700),scrollX:num(semantic?.viewport?.scrollX,0),scrollY:num(semantic?.viewport?.scrollY,0)},controls:{searchInput:controls.searchInput||null,homeLink:controls.homeLink||null,activeTarget},selection:{document:semantic?.selection||null,searchInput:controls.searchInput?.selection||null},advertising:{playingAd:advertising.playingAd===true,skippable:advertising.skippable===true,skipButton:advertising.skipButton||null,feedAdCount:num(advertising.feedAdCount,0)},affordances,candidates,targetVisible,currentIsTarget:Boolean(current.videoId&&String(current.videoId)===String(target?.videoId||'')),knownTopics,environment:{online:observation?.environment?.online===true,eligible:observation?.environment?.eligible===true,status:observation?.environment?.status||null,browserState:observation?.environment?.browserState||null},body:{pointer:observation?.bodyState?.pointer||null,activeTabId:num(observation?.bodyState?.activeTabId)},history:(history||[]).slice(-24)};
}
function candidateByVideo(world,videoId){return (world?.candidates||[]).find(row=>String(row.videoId||'')===String(videoId||''))||null;}
function actionabilityDelta(before,after,videoId){
  const a=candidateByVideo(before,videoId),b=candidateByVideo(after,videoId),beforeState=actionabilityState(a||{}),afterState=actionabilityState(b||{}),beforePosition=candidatePositionState(a||{},before||{}),afterPosition=candidatePositionState(b||{},after||{}),scoreDelta=afterState.score-beforeState.score,goalReached=String(after?.current?.videoId||'')===String(videoId||''),becameActionable=!beforeState.actionable&&afterState.actionable,beforeDistance=Number(beforePosition.distancePx),afterDistance=Number(afterPosition.distancePx),distanceKnown=Number.isFinite(beforeDistance)&&Number.isFinite(afterDistance),distanceDelta=distanceKnown?beforeDistance-afterDistance:0,threshold=Math.max(8,Number(before?.viewport?.height||700)*0.025),positionImproved=distanceKnown&&distanceDelta>threshold,positionRegressed=distanceKnown&&distanceDelta<-threshold,changed=candidateActionabilityKey(a||{})!==candidateActionabilityKey(b||{})||Math.abs(distanceDelta)>=2;
  const improved=Boolean(goalReached||(!beforeState.exists&&afterState.exists)||scoreDelta>0||becameActionable||positionImproved),regressed=Boolean(!goalReached&&((beforeState.exists&&!afterState.exists)||scoreDelta<0||(beforeState.actionable&&!afterState.actionable)||positionRegressed)),distanceComponent=distanceKnown?Math.max(-1,Math.min(1,distanceDelta/Math.max(120,Number(before?.viewport?.height||700)))):0,scoreComponent=Math.max(-0.8,Math.min(0.8,scoreDelta/40)),effectDelta=goalReached?2:becameActionable?1.5:Number(Math.max(-2,Math.min(2,distanceComponent+scoreComponent)).toFixed(4));
  return {videoId:String(videoId||''),changed,improved,regressed,goalReached,scoreDelta,distanceDelta:Number(distanceDelta.toFixed(3)),effectDelta,becameActionable,positionImproved,positionRegressed,before:beforeState,after:afterState,beforePosition,afterPosition};
}
function worldDelta(before,after){if(!before||!after)return {changed:true,reasons:['missing_baseline']};const reasons=[];if(before.signature!==after.signature)reasons.push('signature');if(before.current.videoId!==after.current.videoId)reasons.push('video');if(before.current.pageType!==after.current.pageType)reasons.push('page_type');if(before.current.mediaFormat!==after.current.mediaFormat)reasons.push('media_format');if(Math.abs(Number(before.viewport.scrollY||0)-Number(after.viewport.scrollY||0))>=2)reasons.push('scroll');if(before.tabs.length!==after.tabs.length)reasons.push('tab_count');if(before.body.activeTabId!==after.body.activeTabId)reasons.push('active_tab');if(before.affordances.length!==after.affordances.length)reasons.push('affordance_count');if(JSON.stringify(before.selection||null)!==JSON.stringify(after.selection||null))reasons.push('selection');const ids=new Set([...(before.candidates||[]).map(c=>c.videoId),...(after.candidates||[]).map(c=>c.videoId)]);if([...ids].some(id=>actionabilityDelta(before,after,id).changed))reasons.push('actionability');if(browserUiKey(before.browserUi)!==browserUiKey(after.browserUi))reasons.push('browser_ui');return {changed:reasons.length>0,reasons};}
function distribution(items=[],keyFn=()=>'',weightFn=()=>1){
  const out=new Map();let total=0;for(const item of items||[]){const k=String(keyFn(item)||'unknown'),w=Math.max(0,Number(weightFn(item))||0);if(!w)continue;out.set(k,(out.get(k)||0)+w);total+=w;}if(!total)return out;for(const [k,v] of out)out.set(k,v/total);return out;
}
function totalVariation(a,b){const keys=new Set([...a.keys(),...b.keys()]);let sum=0;for(const key of keys)sum+=Math.abs(Number(a.get(key)||0)-Number(b.get(key)||0));return Math.min(1,sum/2);}
function recommendationDelta(before,after){
  const a=(before?.candidates||[]).filter(x=>x?.videoId),b=(after?.candidates||[]).filter(x=>x?.videoId),aIds=new Set(a.map(x=>String(x.videoId))),bIds=new Set(b.map(x=>String(x.videoId))),union=new Set([...aIds,...bIds]);let common=0;for(const id of aIds)if(bIds.has(id))common++;
  const candidateTurnover=union.size?1-common/union.size:0,topicShift=totalVariation(distribution(a,x=>x.topic),distribution(b,x=>x.topic)),surfaceShift=totalVariation(distribution(a,x=>x.surface),distribution(b,x=>x.surface)),maxBefore=Math.max(0,...a.map(x=>Number(x.targetProximity||0))),maxAfter=Math.max(0,...b.map(x=>Number(x.targetProximity||0))),proximityGain=Math.max(0,maxAfter-maxBefore);
  const recommendationShift=Number(Math.max(0,Math.min(1,candidateTurnover*0.6+topicShift*0.25+surfaceShift*0.15)).toFixed(4));
  return {recommendationShift,candidateTurnover:Number(candidateTurnover.toFixed(4)),topicShift:Number(topicShift.toFixed(4)),surfaceShift:Number(surfaceShift.toFixed(4)),proximityGain:Number(proximityGain.toFixed(4)),beforeCount:a.length,afterCount:b.length,newCandidateCount:[...bIds].filter(id=>!aIds.has(id)).length};
}
function contextKey(world){const exposure=world?.recentExposure,exposureKey=exposure?`preview_exposure:${fold(exposure.topic||'unknown')}:${String(exposure.surface||'unknown')}`:'no_recent_preview',targetState=world?.targetVisible?.actionability||null,targetKey=targetState?`target_actionability:${targetState.score}:${targetState.reason}`:'target_absent';return `${world.current.pageType}|${world.current.topic}|${world.targetFormat||FORMAT.UNKNOWN}->${world.current.mediaFormat||FORMAT.UNKNOWN}|${targetKey}|${world.advertising.playingAd?'ad':'clean'}|${exposureKey}`;}
function candidateIdentity(c){return `${c.videoId}|${c.surface}|${c.position??'?'}`;}
function queryEvidenceKey(query){return fold(String(query||''));}
module.exports={buildWorld,worldDelta,rawRepresentations,assessRepresentation,candidateInteractionState,actionabilityState,candidateActionabilityKey,candidatePositionState,candidatePositionContext,interactionBand,rectPositionMetrics,candidateByVideo,actionabilityDelta,recommendationDelta,distribution,totalVariation,contextKey,candidateIdentity,queryEvidenceKey,routeKey,browserUiKey,selectionKey,observationSignature,affordanceNode,candidateNode,browserUiNode};
