'use strict';

const GUARDIAN_PROTOCOL_VERSION=1;
const GUARDIAN_MESSAGES=Object.freeze({
  SET_GATE:'GUARDIAN_GATE_SET',
  REVOKE_GATE:'GUARDIAN_GATE_REVOKE',
  GATE_STATUS:'GUARDIAN_GATE_STATUS',
  BODY_STATUS:'GUARDIAN_BODY_STATUS',
  BODY_OBSERVE:'GUARDIAN_BODY_OBSERVE',
  ENVIRONMENT_PROBE:'GUARDIAN_EXTENSION_ENVIRONMENT_PROBE'
});

module.exports={GUARDIAN_PROTOCOL_VERSION,GUARDIAN_MESSAGES};
