'use strict';

const GUARDIAN_PROTOCOL_VERSION=1;
const GUARDIAN_MESSAGES=Object.freeze({
  BROWSER_VERDICT:'GUARDIAN_BROWSER_VERDICT',
  LEARNING_SET:'GUARDIAN_LEARNING_SET',
  PROTECTION_STATUS:'GUARDIAN_PROTECTION_STATUS',
  BODY_STATUS:'GUARDIAN_BODY_STATUS',
  BODY_OBSERVE:'GUARDIAN_BODY_OBSERVE',
  ENVIRONMENT_PROBE:'GUARDIAN_EXTENSION_ENVIRONMENT_PROBE'
});

module.exports={GUARDIAN_PROTOCOL_VERSION,GUARDIAN_MESSAGES};
