'use strict';

const BROWSER_CLI_ACTIONS=Object.freeze({
  back:'back',forward:'forward',reload:'reload',browserback:'back',browserforward:'forward',browserreload:'reload',browserhardreload:'hardreload',browserstop:'stop',
  browsernewtab:'newtab',browserclosetab:'closetab',browserreopentab:'reopentab',browsernexttab:'nexttab',browserprevtab:'prevtab',browsernewwindow:'newwindow',browseraddressbar:'addressbar',browserfind:'find',browserdownloads:'downloads',browserhistory:'history',browserdevtools:'devtools',browserfullscreen:'fullscreen',browserbookmark:'bookmark',browserzoomin:'zoomin',browserzoomout:'zoomout',browserzoomreset:'zoomreset'
});

const READ_ONLY_COMMANDS=new Set(['help','extensions','use','status','tabs','tab','sites','site','dataset','model','habit','globalmodel']);
function commandKind(line){
  const cmd=String(line||'').trim().split(/\s+/)[0]||'';
  if(READ_ONLY_COMMANDS.has(cmd))return 'read';
  if(cmd==='exit'||cmd==='thoat')return 'process';
  return 'control';
}

function createCommandRouter(runtime,{updatePrompt=()=>{}}={}){
  const pnum=runtime.pnum;
  function strategyTask(kind,args){const x=pnum(args[0],'x'),y=pnum(args[1],'y');if(kind==='focusnext')return {habitKey:'after_typing_next_focus',targetRole:args[4]||'textbox',strategies:[{id:'keyboard_tab',modality:'keyboard',actions:[{type:'pressKey',key:'Tab'}]},{id:'mouse_click',modality:'mouse',actions:[{type:'click',x,y,width:args[2]?pnum(args[2],'width'):120,height:args[3]?pnum(args[3],'height'):36,role:args[4]||'textbox'}]}]};if(kind==='submitchoice')return {habitKey:'after_typing_submit',targetRole:args[4]||'button',strategies:[{id:'keyboard_enter',modality:'keyboard',actions:[{type:'pressKey',key:'Enter'}]},{id:'mouse_click',modality:'mouse',actions:[{type:'click',x,y,width:args[2]?pnum(args[2],'width'):120,height:args[3]?pnum(args[3],'height'):40,role:args[4]||'button'}]}]};return {habitKey:'after_typing_dismiss',targetRole:'button',strategies:[{id:'keyboard_escape',modality:'keyboard',actions:[{type:'pressKey',key:'Escape'}]},{id:'mouse_click',modality:'mouse',actions:[{type:'click',x,y,width:args[2]?pnum(args[2],'width'):32,height:args[3]?pnum(args[3],'height'):32,role:'button'}]}]};}
  async function runCommand(line,{assertControl=null}={}){
    line=String(line||'').trim();if(!line)return null;const kind=commandKind(line);if(kind==='control'&&typeof assertControl==='function')assertControl();const [cmd,...args]=line.split(' ');
    if(cmd==='help')return helpText();if(cmd==='extensions')return runtime.registry.list();if(cmd==='use'){const item=runtime.registry.select(args[0]);updatePrompt();return {selectedExtension:item.extensionId,online:item.online,tabCount:item.tabs.size};}
    if(cmd==='status'){const extId=runtime.registry.selectedId,ext=extId?runtime.registry.get(extId):null;let ping=null;if(ext?.online)try{ping=await runtime.requestExtension(extId,'PING');}catch{}return {selectedExtension:extId,extensions:runtime.registry.list(),recordingEnabled:runtime.recordingEnabled,learningEnabled:runtime.learningEnabled,tabHabit:runtime.tabHabit.stats(extId),extension:ping};}
    if(cmd==='tabs'){const extId=runtime.selected(args[0]||null);return runtime.refreshTabs(extId);}if(cmd==='tab'){const extId=runtime.selected();return runtime.resolveTab(extId,args[0]||'active');}if(cmd==='switch')return runtime.switchTab(null,pnum(args[0],'tabId'));
    if(cmd==='sites')return runtime.learning.listSites(runtime.selected(args[0]||null));
    if(cmd==='site'||cmd==='dataset'||cmd==='model'||cmd==='habit'){const extId=runtime.selected(),tab=await runtime.resolveTab(extId,args[0]||'active'),stats=runtime.learning.stats(extId,String(tab.siteKey||'').toLowerCase());if(cmd==='dataset')return stats.dataset;if(cmd==='model')return stats.motor;if(cmd==='habit')return stats.habit;return stats;}
    if(cmd==='globalmodel')return runtime.learning.stats(runtime.selected(),'__global__');
    if(cmd==='train'){const extId=runtime.selected(),ref=args[0]||'active';if(ref==='all')return runtime.learning.rebuild(extId,'*');if(ref==='global')return runtime.learning.rebuild(extId,'__global__');const tab=await runtime.resolveTab(extId,ref);return runtime.learning.rebuild(extId,String(tab.siteKey||'').toLowerCase());}
    if(cmd==='record'){if(!['on','off'].includes(args[0]))throw new Error('record on|off');runtime.recordingEnabled=args[0]==='on';const results=[];for(const ext of runtime.registry.list().filter(x=>x.online)){try{results.push({extensionId:ext.extensionId,result:await runtime.requestExtension(ext.extensionId,'RECORD_SET',{enabled:runtime.recordingEnabled})});}catch(error){results.push({extensionId:ext.extensionId,error:String(error.message||error)});}}return {recordingEnabled:runtime.recordingEnabled,results};}
    if(cmd==='learn'){if(!['on','off'].includes(args[0]))throw new Error('learn on|off');runtime.learningEnabled=args[0]==='on';return {learningEnabled:runtime.learningEnabled};}if(cmd==='cursor'){if(!['on','off'].includes(args[0]))throw new Error('cursor on|off');return runtime.requestExtension(runtime.selected(),'CURSOR_SET',{enabled:args[0]==='on'});}
    if(BROWSER_CLI_ACTIONS[cmd])return runtime.executeBrowserCommand(BROWSER_CLI_ACTIONS[cmd]);if(cmd==='browseraddress')return runtime.executeBrowserCommand('address',{value:args.join(' ')});if(cmd==='browserfindtext')return runtime.executeBrowserCommand('findtext',{value:args.join(' ')});
    if(['focusnext','submitchoice','dismisschoice'].includes(cmd)){if(args.length<2)throw new Error(`${cmd} x y [width height role]`);return runtime.executeStrategy(strategyTask(cmd,args));}if(cmd==='strategy'){const obj=JSON.parse(line.slice('strategy'.length).trim());return runtime.executeStrategy(obj.task||obj,{extensionId:obj.extensionId||null,tabId:obj.tabId||'active'});}
    if(cmd==='click')return runtime.executeIntent({type:'click',x:pnum(args[0],'x'),y:pnum(args[1],'y'),width:args[2]?pnum(args[2],'width'):12,height:args[3]?pnum(args[3],'height'):12,role:args[4]||'unknown'});if(cmd==='doubleclick')return runtime.executeIntent({type:'doubleClick',x:pnum(args[0],'x'),y:pnum(args[1],'y'),width:args[2]?pnum(args[2],'width'):12,height:args[3]?pnum(args[3],'height'):12});if(cmd==='move'||cmd==='hover')return runtime.executeIntent({type:cmd==='move'?'moveTo':'hover',x:pnum(args[0],'x'),y:pnum(args[1],'y')});if(cmd==='drag')return runtime.executeIntent({type:'drag',x1:pnum(args[0],'x1'),y1:pnum(args[1],'y1'),x2:pnum(args[2],'x2'),y2:pnum(args[3],'y2')});if(cmd==='scroll'||cmd==='hscroll')return runtime.executeIntent({type:cmd==='scroll'?'scrollVertical':'scrollHorizontal',delta:pnum(args[0],'delta')});if(cmd==='type'){if(args.length<3)throw new Error('type x y noi_dung');return runtime.executeIntent({type:'typeText',x:pnum(args[0],'x'),y:pnum(args[1],'y'),text:args.slice(2).join(' '),role:'textbox',width:18,height:18});}if(cmd==='key')return runtime.executeIntent({type:'pressKey',key:args.join(' ')});if(cmd==='combo')return runtime.executeIntent({type:'keyCombo',key:args.join(' ')});
    if(cmd==='detach'){const extId=runtime.selected(),tab=await runtime.resolveTab(extId,args[0]||'active');return runtime.requestExtension(extId,'BODY_DETACH',{tabId:Number(tab.id)});}if(cmd==='intent'){const obj=JSON.parse(line.slice('intent'.length).trim());return runtime.executeIntent(obj.intent||obj,{extensionId:obj.extensionId||null,tabId:obj.tabId||'active'});}if(cmd==='exit'||cmd==='thoat'){process.nextTick(()=>process.exit(0));return {exiting:true};}throw new Error('unknown_command');
  }
  function helpText(){return ['DEBUG CLIENT ONLY — Brain uses structured socket messages, not text commands.','MULTI EXTENSION: extensions | use <extensionId> | status','MULTI TAB: tabs | tab | switch <tabId>','LEARNING: sites | site [tabId] | dataset | model | habit | globalmodel | train [tabId|global|all]','CONTROL: record on|off | learn on|off | cursor on|off','BROWSER UI: back | forward | reload | browserhardreload | browserstop | browsernewtab | browserclosetab | browserreopentab | browsernexttab | browserprevtab | browsernewwindow','BROWSER UI+: browseraddressbar | browseraddress <url/query> | browserfind | browserfindtext <text> | browserdownloads | browserhistory | browserdevtools | browserfullscreen | browserbookmark | browserzoomin | browserzoomout | browserzoomreset','STRATEGY: focusnext x y [w h role] | submitchoice x y [w h role] | dismisschoice x y [w h] | strategy {JSON}','PAGE MOTOR: move x y | click x y [w h role] | doubleclick | hover | drag x1 y1 x2 y2 | scroll delta | hscroll delta | type x y text | key Enter | combo Control+a | detach'].join('\n');}
  return {runCommand,helpText,BROWSER_CLI_ACTIONS,strategyTask,commandKind};
}
module.exports={BROWSER_CLI_ACTIONS,READ_ONLY_COMMANDS,commandKind,createCommandRouter};
