'use strict';

const crypto=require('node:crypto');
const fs=require('node:fs');
const path=require('node:path');
const {SafeJsonPersistence}=require('./safe_json_persistence');
const {DeviceNetworkProbe}=require('./device_network_probe');

function envBool(value,fallback){const raw=String(value??'').trim().toLowerCase();if(!raw)return fallback;if(['1','true','yes','on'].includes(raw))return true;if(['0','false','no','off'].includes(raw))return false;return fallback;}
function envInt(value,fallback,min,max){const n=Number(value);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.round(n))):fallback;}
function canonical(value){if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==='object'){const out={};for(const key of Object.keys(value).sort())out[key]=canonical(value[key]);return out;}return value;}
function hashObject(value){return crypto.createHash('sha256').update(JSON.stringify(canonical(value))).digest('hex');}
function compactDeepFingerprint(input={}){if(input?.available!==true)return {available:false,error:String(input?.error||'deep_fingerprint_unavailable')};const coveragePercent=envInt(input?.coverage?.percent,0,0,100),signalIds=Array.isArray(input.signals)?input.signals.map(x=>String(x?.id||'').trim()).filter(Boolean).slice(0,32):[];return {available:true,score:envInt(input.score,0,0,100),verdict:String(input.verdict||'UNKNOWN'),suspected:input.suspected===true,highSuspicion:input.highSuspicion===true,stableHash:String(input.stableHash||'').slice(0,128)||null,coverage:{percent:coveragePercent,available:Number(input?.coverage?.available)||0,total:Number(input?.coverage?.total)||0},signalIds};}
function environmentFingerprint(input={},deep=null){if(input?.available!==true)return null;return {userAgent:String(input.userAgent||''),platform:String(input.platform||''),language:String(input.language||''),languages:Array.isArray(input.languages)?input.languages.map(String):[],hardwareConcurrency:Number(input.hardwareConcurrency||0),deviceMemory:Number(input.deviceMemory||0),maxTouchPoints:Number(input.maxTouchPoints||0),webdriver:input.webdriver===true,timezone:String(input.timezone||''),screen:input.screen||{},devicePixelRatio:Number(input.devicePixelRatio||1),deepStableHash:deep?.available===true?String(deep.stableHash||''):''};}

class EnvironmentGuardian{
  constructor(baseDir,browserManager,{requestExtension,env=process.env,deviceProbe=new DeviceNetworkProbe({env}),now=()=>Date.now()}={}){
    if(!browserManager||typeof requestExtension!=='function')throw new Error('environment_guardian_dependencies_required');this.browserManager=browserManager;this.requestExtension=requestExtension;this.env=env||{};this.deviceProbe=deviceProbe;this.now=now;
    this.policy={directOnly:envBool(this.env.BODY_ENV_DIRECT_ONLY,true),requireUniquePublicIp:envBool(this.env.BODY_ENV_REQUIRE_UNIQUE_PUBLIC_IP,true),requireUniqueEnvironmentSignature:envBool(this.env.BODY_ENV_REQUIRE_UNIQUE_SIGNATURE,true),strictEnvironmentConsistency:envBool(this.env.BODY_ENV_STRICT_CONSISTENCY,false),deepFingerprintEnabled:envBool(this.env.BODY_ENV_DEEP_FINGERPRINT_ENABLED,true),deepBlockHighSuspicion:envBool(this.env.BODY_ENV_DEEP_BLOCK_HIGH_SUSPICION,true),deepMinCoveragePercent:envInt(this.env.BODY_ENV_DEEP_MIN_COVERAGE_PERCENT,50,0,100),observationTtlMs:Math.max(10000,Number(this.env.BODY_ENV_OBSERVATION_TTL_MS)||300000),publicIpEndpoint:String(this.env.BODY_PUBLIC_IP_ENDPOINT||'https://api.ipify.org?format=json'),probeTimeoutMs:Math.max(1000,Math.min(15000,Number(this.env.BODY_ENV_PROBE_TIMEOUT_MS)||6000))};
    this.file=path.join(baseDir,'state','environment.json');fs.mkdirSync(path.dirname(this.file),{recursive:true});this.state=this._load();this.persistence=new SafeJsonPersistence(this.file,{getValue:()=>this.state,debounceMs:0,retryAfterMs:1000,log:null});
  }
  _load(){if(!fs.existsSync(this.file))return {schemaVersion:1,baselines:{},observations:{}};let data;try{data=JSON.parse(fs.readFileSync(this.file,'utf8'));}catch{throw new Error('environment_state_invalid_json');}if(Number(data.schemaVersion)!==1||!data.baselines||!data.observations)throw new Error('environment_state_invalid');return data;}
  _persist(){this.persistence.schedule();const result=this.persistence.flushSync();if(!result.ok)throw new Error(`environment_state_persistence_failed:${result.lastError?.code||'UNKNOWN'}`);return result;}
  _fresh(observation){const at=Date.parse(observation?.observedAt||'');return Number.isFinite(at)&&(this.now()-at)<=this.policy.observationTtlMs;}
  _baseReasons(browserId,probe,device,signature,deep){
    const reasons=[];if(!probe?.pageEnvironment?.available)reasons.push('ENVIRONMENT_SIGNATURE_UNAVAILABLE');if(!probe?.publicEgress?.available||!probe.publicEgress.ip)reasons.push('PUBLIC_EGRESS_UNAVAILABLE');
    if(this.policy.directOnly){if(!probe?.proxy?.available)reasons.push('PROXY_STATUS_UNAVAILABLE');else if(probe.proxy.detected===true)reasons.push('BROWSER_PROXY_DETECTED');else if(probe.proxy.autoDetect===true)reasons.push('PROXY_AUTO_DETECT_ENABLED');if(device?.proxyEnvDetected===true)reasons.push('DEVICE_PROXY_ENV_DETECTED');if(device?.systemProxyDetected===true)reasons.push('SYSTEM_PROXY_DETECTED');if(device?.vpnInterfaceDetected===true)reasons.push('VPN_TUNNEL_INTERFACE_DETECTED');}
    if(this.policy.deepFingerprintEnabled&&this.policy.deepBlockHighSuspicion&&deep?.available===true&&deep.highSuspicion===true&&Number(deep.coverage?.percent||0)>=this.policy.deepMinCoveragePercent)reasons.push('DEEP_FINGERPRINT_HIGH_SUSPICION');
    const baseline=this.state.baselines[browserId];if(signature&&baseline?.environmentSignature&&baseline.environmentSignature!==signature&&this.policy.strictEnvironmentConsistency)reasons.push('ENVIRONMENT_SIGNATURE_DRIFT');return [...new Set(reasons)];
  }
  _groups(field){const groups=new Map();for(const [browserId,obs] of Object.entries(this.state.observations)){if(!this._fresh(obs))continue;const browser=this.browserManager.browsers.get(browserId);if(!browser?.online)continue;const value=obs[field];if(!value)continue;if(!groups.has(value))groups.set(value,[]);groups.get(value).push(browserId);}return groups;}
  _recompute(){
    const cross=new Map(),add=(browserId,reason)=>{if(!cross.has(browserId))cross.set(browserId,new Set());cross.get(browserId).add(reason);};
    if(this.policy.requireUniquePublicIp)for(const ids of this._groups('publicIp').values())if(ids.length>1)for(const id of ids)add(id,'DUPLICATE_PUBLIC_EGRESS');
    if(this.policy.requireUniqueEnvironmentSignature)for(const ids of this._groups('environmentSignature').values())if(ids.length>1)for(const id of ids)add(id,'DUPLICATE_ENVIRONMENT_SIGNATURE');
    const results=[];for(const browser of this.browserManager.browsers.values()){if(!browser.online)continue;const obs=this.state.observations[browser.browserInstanceId];let reasons=[];if(!obs||!this._fresh(obs))reasons=['ENVIRONMENT_OBSERVATION_STALE'];else reasons=[...(obs.baseReasons||[]),...(cross.get(browser.browserInstanceId)||[])];reasons=[...new Set(reasons)];const eligible=reasons.length===0,environment={eligible,status:eligible?'ELIGIBLE':'INELIGIBLE',observedAt:obs?.observedAt||null,publicIp:obs?.publicIp||null,environmentSignature:obs?.environmentSignature||null,deepFingerprint:obs?.deepFingerprint||{available:false,error:'deep_fingerprint_unavailable'},reasons,evidence:obs?.evidence||[]};this.browserManager.setEnvironment(browser.browserInstanceId,environment,eligible?'environment_eligible':'environment_policy_failed');results.push({browserInstanceId:browser.browserInstanceId,...environment});}return results;
  }
  async probeBrowser(browserInstanceId){
    const browser=this.browserManager.require(browserInstanceId);if(!browser.online)throw new Error(`browser_offline:${browser.browserInstanceId}`);if(browser.state==='BUSY')throw new Error(`environment_probe_browser_busy:${browser.browserInstanceId}`);this.browserManager.setState(browser.browserInstanceId,'ENV_CHECK','environment_probe_started');
    const tabId=Number.isInteger(Number(browser.activeTabId))?Number(browser.activeTabId):browser.tabs.keys().next().value;if(!Number.isInteger(Number(tabId))){this.state.observations[browser.browserInstanceId]={observedAt:new Date(this.now()).toISOString(),publicIp:null,environmentSignature:null,deepFingerprint:{available:false,error:'no_browser_tab'},baseReasons:['NO_BROWSER_TAB_FOR_ENVIRONMENT_PROBE'],evidence:[]};this._persist();return this._recompute().find(x=>x.browserInstanceId===browser.browserInstanceId);}
    let probe;try{probe=await this.requestExtension(browser.extensionInstanceId,'ENVIRONMENT_PROBE',{tabId:Number(tabId),publicIpEndpoint:this.policy.publicIpEndpoint,timeoutMs:this.policy.probeTimeoutMs},this.policy.probeTimeoutMs+4000);}catch(error){probe={pageEnvironment:{available:false,error:String(error?.message||error)},proxy:{available:false,detected:null},publicEgress:{available:false,ip:null,error:String(error?.message||error)},deepFingerprint:{available:false,error:String(error?.message||error)}};}
    const device=this.deviceProbe.probe(),deep=compactDeepFingerprint(probe.deepFingerprint),fingerprint=environmentFingerprint(probe.pageEnvironment,deep),signature=fingerprint?hashObject(fingerprint):null,observedAt=new Date(this.now()).toISOString();if(signature&&!this.state.baselines[browser.browserInstanceId])this.state.baselines[browser.browserInstanceId]={environmentSignature:signature,createdAt:observedAt};const baseReasons=this._baseReasons(browser.browserInstanceId,probe,device,signature,deep);
    this.state.observations[browser.browserInstanceId]={observedAt,publicIp:probe?.publicEgress?.ip||null,environmentSignature:signature,deepFingerprint:deep,baseReasons,evidence:[{type:'browser_environment',available:probe?.pageEnvironment?.available===true},{type:'deep_fingerprint',available:deep.available===true,score:deep.available?deep.score:null,highSuspicion:deep.available?deep.highSuspicion:null,coveragePercent:deep.available?deep.coverage.percent:null,signalIds:deep.available?deep.signalIds:[]},{type:'browser_proxy',available:probe?.proxy?.available===true,detected:probe?.proxy?.detected??null,mode:probe?.proxy?.mode||null},{type:'public_egress',available:probe?.publicEgress?.available===true,provider:probe?.publicEgress?.provider||null},{type:'device_network',proxyEnvDetected:device.proxyEnvDetected===true,systemProxyDetected:device.systemProxyDetected===true,vpnInterfaceDetected:device.vpnInterfaceDetected===true,vpnInterfaces:device.vpnInterfaces||[]}]};
    this._persist();const result=this._recompute().find(x=>x.browserInstanceId===browser.browserInstanceId);this._persist();return result;
  }
  async probeAll(){const results=[];for(const browser of this.browserManager.list().filter(x=>x.online)){try{results.push(await this.probeBrowser(browser.browserInstanceId));}catch(error){results.push({browserInstanceId:browser.browserInstanceId,eligible:false,status:'ERROR',reasons:[String(error?.message||error)]});}}return results;}
  browserOffline(browserInstanceId){const results=this._recompute();this._persist();return results.find(x=>x.browserInstanceId===browserInstanceId)||null;}
  status(){return {policy:{...this.policy},observations:JSON.parse(JSON.stringify(this.state.observations)),baselines:JSON.parse(JSON.stringify(this.state.baselines))};}
  flushSync(){return this.persistence.flushSync();}
}
module.exports={EnvironmentGuardian,envBool,envInt,canonical,hashObject,compactDeepFingerprint,environmentFingerprint};
