'use strict';

const CATEGORY_CAPS=Object.freeze({consistency:35,integrity:25,stability:25,automation:20,hardware:20,privacy:15,plausibility:15});
const AUTOMATION_MARKERS=['__playwright__binding__','__pwInitScripts','__webdriver_script_fn','__driver_evaluate','__selenium_evaluate','__fxdriver_evaluate','_Selenium_IDE_Recorder','callSelenium','_phantom','phantom','__nightmare'];

function collectRealmSnapshot(options={}){
  // chrome.scripting.executeScript serializes this function into the target realm, so it must not depend on module-scope bindings.
  const automationMarkers=['__playwright__binding__','__pwInitScripts','__webdriver_script_fn','__driver_evaluate','__selenium_evaluate','__fxdriver_evaluate','_Selenium_IDE_Recorder','callSelenium','_phantom','phantom','__nightmare'];
  const full=options.fullContext===true,canvasRepeats=Math.max(2,Math.min(4,Number(options.canvasRepeats)||(full?3:2))),audioRepeats=Math.max(1,Math.min(2,Number(options.audioRepeats)||1));
  const safe=(fn,fallback=null)=>{try{const v=fn();return v===undefined?fallback:v;}catch{return fallback;}};
  const hash=text=>{const s=String(text??'');let h=0x811c9dc5;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,0x01000193);}return (h>>>0).toString(16).padStart(8,'0');};
  const fnInfo=fn=>{let source='';try{source=Function.prototype.toString.call(fn);}catch{}return {native:/\{\s*\[native code\]\s*\}/.test(source),sourceHash:hash(source)};};
  const n=navigator,s=screen||{},out={context:{chromeObject:safe(()=>!!window.chrome,false)},navigator:{},userAgentData:null,intl:{},screen:{},canvas:{samples:[]},webgl:{samples:[]},audio:{samples:[]},nativeIntegrity:{},descriptors:{},automationMarkers:[],iframe:null,worker:null};
  out.navigator={userAgent:safe(()=>n.userAgent,''),platform:safe(()=>n.platform,''),vendor:safe(()=>n.vendor,''),language:safe(()=>n.language,''),languages:safe(()=>Array.from(n.languages||[]),[]),hardwareConcurrency:safe(()=>n.hardwareConcurrency),deviceMemory:safe(()=>n.deviceMemory),maxTouchPoints:safe(()=>n.maxTouchPoints),webdriver:safe(()=>n.webdriver),pdfViewerEnabled:safe(()=>n.pdfViewerEnabled)};
  if(n.userAgentData){out.userAgentData={brands:safe(()=>Array.from(n.userAgentData.brands||[]),[]),mobile:safe(()=>n.userAgentData.mobile,false),platform:safe(()=>n.userAgentData.platform,'')};}
  out.intl={timeZone:safe(()=>Intl.DateTimeFormat().resolvedOptions().timeZone,''),locale:safe(()=>Intl.DateTimeFormat().resolvedOptions().locale,'')};
  out.screen={width:safe(()=>s.width),height:safe(()=>s.height),availWidth:safe(()=>s.availWidth),availHeight:safe(()=>s.availHeight),colorDepth:safe(()=>s.colorDepth),pixelDepth:safe(()=>s.pixelDepth),devicePixelRatio:safe(()=>window.devicePixelRatio,1)};
  const canvasSample=()=>{try{const c=document.createElement('canvas');c.width=280;c.height=96;const x=c.getContext('2d',{willReadFrequently:true});x.textBaseline='alphabetic';x.fillStyle='#f60';x.fillRect(7,7,61,39);x.fillStyle='#069';x.font='17px Arial';x.fillText('Body Deep Probe π 漢 😀',4,34);x.globalCompositeOperation='multiply';x.fillStyle='rgba(102,204,0,.7)';x.beginPath();x.arc(86,44,25,0,Math.PI*2);x.fill();x.globalCompositeOperation='source-over';const m=x.measureText('mmmmlliWWπ漢😀');const data=x.toDataURL('image/png'),pixels=x.getImageData(0,0,c.width,c.height).data;let packed='';for(let i=0,step=Math.max(4,Math.floor(pixels.length/2500));i<pixels.length;i+=step)packed+=String.fromCharCode(pixels[i]);return {dataUrlHash:hash(data),pixelHash:hash(packed),textWidth:Number(m.width.toFixed(5))};}catch{return null;}};
  for(let i=0;i<canvasRepeats;i++)out.canvas.samples.push(canvasSample());
  const webglSample=()=>{try{const c=document.createElement('canvas');c.width=48;c.height=48;const gl=c.getContext('webgl2',{preserveDrawingBuffer:true})||c.getContext('webgl',{preserveDrawingBuffer:true});if(!gl)return {available:false};const dbg=gl.getExtension('WEBGL_debug_renderer_info');gl.viewport(0,0,48,48);gl.clearColor(.173,.419,.731,.913);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const pixels=new Uint8Array(48*48*4);gl.readPixels(0,0,48,48,gl.RGBA,gl.UNSIGNED_BYTE,pixels);let packed='';for(let i=0;i<pixels.length;i+=13)packed+=String.fromCharCode(pixels[i]);return {available:true,vendor:String(gl.getParameter(gl.VENDOR)||''),renderer:String(gl.getParameter(gl.RENDERER)||''),unmaskedVendor:dbg?String(gl.getParameter(dbg.UNMASKED_VENDOR_WEBGL)||''):null,unmaskedRenderer:dbg?String(gl.getParameter(dbg.UNMASKED_RENDERER_WEBGL)||''):null,maxTextureSize:Number(gl.getParameter(gl.MAX_TEXTURE_SIZE)||0),readPixelsHash:hash(packed)};}catch{return {available:false};}};
  for(let i=0;i<(full?2:1);i++)out.webgl.samples.push(webglSample());out.webgl.primary=out.webgl.samples[0]||{available:false};
  const audioSample=async()=>{try{const Offline=window.OfflineAudioContext||window.webkitOfflineAudioContext;if(!Offline)return {available:false};const c=new Offline(1,4000,44100),osc=c.createOscillator(),comp=c.createDynamicsCompressor();osc.type='triangle';osc.frequency.value=10000;comp.threshold.value=-50;comp.knee.value=40;comp.ratio.value=12;osc.connect(comp);comp.connect(c.destination);osc.start(0);const rendered=await c.startRendering(),ch=rendered.getChannelData(0);let packed='';for(let i=0;i<ch.length;i+=4)packed+=Math.round(ch[i]*1000000)+',';return {available:true,hash:hash(packed),sampleRate:rendered.sampleRate};}catch{return {available:false};}};
  return (async()=>{
    for(let i=0;i<audioRepeats;i++)out.audio.samples.push(await audioSample());out.audio.primary=out.audio.samples[0]||{available:false};
    const api={functionToString:Function.prototype.toString,canvasToDataURL:HTMLCanvasElement?.prototype?.toDataURL,canvasGetContext:HTMLCanvasElement?.prototype?.getContext,webglGetParameter:globalThis.WebGLRenderingContext?.prototype?.getParameter,rtcPeerConnection:globalThis.RTCPeerConnection};for(const [name,fn] of Object.entries(api))if(typeof fn==='function')out.nativeIntegrity[name]=fnInfo(fn);
    for(const key of ['userAgent','platform','languages','hardwareConcurrency','deviceMemory','webdriver']){try{const d=Object.getOwnPropertyDescriptor(Navigator.prototype,key);out.descriptors[key]=d?{configurable:d.configurable,enumerable:d.enumerable,hasGetter:typeof d.get==='function',hasSetter:typeof d.set==='function'}:null;}catch{out.descriptors[key]=null;}}
    out.automationMarkers=automationMarkers.filter(k=>safe(()=>k in globalThis,false));
    if(full){try{const frame=document.createElement('iframe');frame.src='about:blank';frame.style.display='none';document.documentElement.appendChild(frame);await new Promise(r=>setTimeout(r,0));const w=frame.contentWindow;out.iframe=w?{available:true,userAgent:String(w.navigator.userAgent||''),platform:String(w.navigator.platform||''),languages:Array.from(w.navigator.languages||[]),hardwareConcurrency:w.navigator.hardwareConcurrency??null,deviceMemory:w.navigator.deviceMemory??null,webdriver:w.navigator.webdriver??null,timeZone:w.Intl.DateTimeFormat().resolvedOptions().timeZone||''}:{available:false};frame.remove();}catch{out.iframe={available:false};}
      try{const source=`postMessage({userAgent:navigator.userAgent,platform:navigator.platform,languages:Array.from(navigator.languages||[]),hardwareConcurrency:navigator.hardwareConcurrency,deviceMemory:navigator.deviceMemory,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone||''})`,url=URL.createObjectURL(new Blob([source],{type:'text/javascript'}));out.worker=await new Promise(resolve=>{const w=new Worker(url),t=setTimeout(()=>{try{w.terminate();}catch{}URL.revokeObjectURL(url);resolve({available:false});},1200);w.onmessage=e=>{clearTimeout(t);try{w.terminate();}catch{}URL.revokeObjectURL(url);resolve({available:true,...e.data});};w.onerror=()=>{clearTimeout(t);try{w.terminate();}catch{}URL.revokeObjectURL(url);resolve({available:false});};});}catch{out.worker={available:false};}}
    return out;
  })();
}

async function settingSnapshot(setting){if(!setting?.get)return {available:false};try{const d=await setting.get({});return {available:true,value:d?.value??null,levelOfControl:d?.levelOfControl||null};}catch(error){return {available:false,error:String(error?.message||error)};}}
async function extensionSignals(chromeApi){
  const get=async(fn,fallback=null)=>{try{return await fn();}catch{return fallback;}};
  const runtimePlatform=await get(()=>chromeApi.runtime.getPlatformInfo(),null),cpu=await get(()=>chromeApi.system?.cpu?.getInfo(),null),memory=await get(()=>chromeApi.system?.memory?.getInfo(),null),displays=await get(()=>chromeApi.system?.display?.getInfo(),null),p=chromeApi.privacy;
  return {runtimePlatform,systemCpu:cpu?{archName:cpu.archName||null,numOfProcessors:cpu.numOfProcessors??null}:null,systemMemory:memory?{capacity:memory.capacity??null}:null,systemDisplays:Array.isArray(displays)?displays.map(d=>({isPrimary:d.isPrimary===true,deviceScaleFactor:d.deviceScaleFactor??null,bounds:d.bounds?{width:d.bounds.width,height:d.bounds.height}:null})):[],privacy:{available:Boolean(p),webRTCIPHandlingPolicy:await settingSnapshot(p?.network?.webRTCIPHandlingPolicy),doNotTrackEnabled:await settingSnapshot(p?.websites?.doNotTrackEnabled),referrersEnabled:await settingSnapshot(p?.websites?.referrersEnabled)}};
}
function runtimeOsMatches(os,ua,platform,chPlatform){const text=`${ua||''} ${platform||''} ${chPlatform||''}`.toLowerCase();if(!os)return true;if(os==='win')return /windows|win32|win64/.test(text);if(os==='mac')return /macintosh|mac os|macintel|macos/.test(text);if(os==='linux')return /linux|x11/.test(text)&&!/android/.test(text);if(os==='android')return /android/.test(text);if(os==='cros')return /cros|chrome os/.test(text);return true;}
function analyzeDeepSnapshots(main={},isolated={},extension={}){
  const signals=[],raw=Object.fromEntries(Object.keys(CATEGORY_CAPS).map(k=>[k,0])),add=(id,weight,category,severity='medium',confidence='high',detail='')=>{if(signals.some(x=>x.id===id))return;signals.push({id,weight,category,severity,confidence,detail:String(detail).slice(0,240)});raw[category]=(raw[category]||0)+Number(weight||0);},eq=(a,b)=>JSON.stringify(a)===JSON.stringify(b),get=(o,p)=>p.split('.').reduce((v,k)=>v?.[k],o),cmp=(a,b,id,w,c='consistency',s='medium')=>{if(a!==null&&a!==undefined&&b!==null&&b!==undefined&&!eq(a,b))add(id,w,c,s,'high',`${JSON.stringify(a).slice(0,80)} != ${JSON.stringify(b).slice(0,80)}`);};
  for(const [p,w] of [['navigator.userAgent',22],['navigator.platform',18],['navigator.languages',9],['navigator.hardwareConcurrency',10],['navigator.deviceMemory',10],['navigator.webdriver',15],['intl.timeZone',10],['screen.width',7],['screen.height',7]])cmp(get(main,p),get(isolated,p),`world_${p.replace(/\./g,'_')}`,w,'consistency',w>=15?'high':'medium');
  if(main.iframe?.available){cmp(main.iframe.userAgent,main.navigator?.userAgent,'iframe_userAgent_mismatch',18);cmp(main.iframe.platform,main.navigator?.platform,'iframe_platform_mismatch',15);cmp(main.iframe.webdriver,main.navigator?.webdriver,'iframe_webdriver_mismatch',12);}
  if(main.worker?.available){cmp(main.worker.userAgent,main.navigator?.userAgent,'worker_userAgent_mismatch',16);cmp(main.worker.platform,main.navigator?.platform,'worker_platform_mismatch',14);}
  const mc=(main.canvas?.samples||[]).filter(Boolean),ic=(isolated.canvas?.samples||[]).filter(Boolean);if(new Set(mc.map(x=>JSON.stringify(x))).size>1)add('canvas_unstable',28,'stability','high','high');if(mc[0]&&ic[0]&&!eq(mc[0],ic[0]))add('canvas_world_mismatch',22,'consistency','high','high');
  const mg=main.webgl?.primary||{},ig=isolated.webgl?.primary||{};for(const [k,w] of [['unmaskedVendor',12],['unmaskedRenderer',18],['maxTextureSize',8],['readPixelsHash',10]])cmp(mg[k],ig[k],`webgl_world_${k}`,w,'consistency',w>=15?'high':'medium');if(new Set((main.webgl?.samples||[]).filter(x=>x?.available).map(x=>x.readPixelsHash)).size>1)add('webgl_unstable',22,'stability','high','high');
  const ma=(main.audio?.samples||[]).filter(x=>x?.available).map(x=>x.hash),ia=isolated.audio?.primary;if(new Set(ma).size>1)add('audio_unstable',24,'stability','high','high');if(main.audio?.primary?.available&&ia?.available&&main.audio.primary.hash!==ia.hash)add('audio_world_mismatch',16,'consistency','medium','high');
  for(const [name,info] of Object.entries(main.nativeIntegrity||{})){const iso=isolated.nativeIntegrity?.[name];if(iso&&info.native===false&&iso.native===true)add(`api_hook_${name}`,14,'integrity','high','high');else if(iso&&info.sourceHash&&iso.sourceHash&&info.sourceHash!==iso.sourceHash)add(`api_source_${name}`,9,'integrity','medium','medium');}
  for(const [name,d] of Object.entries(main.descriptors||{})){const iso=isolated.descriptors?.[name];if(iso&&!eq(d,iso))add(`descriptor_${name}`,10,'integrity','medium','high');}
  if((main.automationMarkers||[]).length)add('automation_markers',20,'automation','high','medium',(main.automationMarkers||[]).join(','));if(main.navigator?.webdriver===true)add('webdriver_true',18,'automation','medium','high');
  const ua=String(main.navigator?.userAgent||''),platform=String(main.navigator?.platform||''),ch=String(main.userAgentData?.platform||''),os=String(extension.runtimePlatform?.os||'');if(!runtimeOsMatches(os,ua,platform,ch))add('runtime_os_mismatch',26,'hardware','high','high');
  const actualCpu=Number(extension.systemCpu?.numOfProcessors),claimedCpu=Number(main.navigator?.hardwareConcurrency);if(Number.isFinite(claimedCpu)&&(claimedCpu<=0||claimedCpu>256))add('cpu_implausible',12,'plausibility','medium','high');if(actualCpu>0&&claimedCpu>actualCpu)add('cpu_exceeds_system',22,'hardware','high','high');
  const dm=Number(main.navigator?.deviceMemory),actualGb=Number(extension.systemMemory?.capacity||0)/1073741824;if(Number.isFinite(dm)&&![.25,.5,1,2,4,8].includes(dm))add('memory_unusual',9,'plausibility','low','medium');if(actualGb>0&&dm>actualGb+.75)add('memory_exceeds_system',20,'hardware','high','high');
  const displays=extension.systemDisplays||[],w=Number(main.screen?.width),h=Number(main.screen?.height),dpr=Number(main.screen?.devicePixelRatio||0);if(displays.length&&w>0&&h>0&&!displays.some(d=>d.bounds&&((Math.abs(d.bounds.width-w)<=2&&Math.abs(d.bounds.height-h)<=2)||(Math.abs(d.bounds.width-h)<=2&&Math.abs(d.bounds.height-w)<=2))))add('screen_system_mismatch',12,'hardware','medium','medium');if(displays.length&&dpr>0&&!displays.some(d=>Number(d.deviceScaleFactor)>0&&Math.abs(Number(d.deviceScaleFactor)-dpr)<=.2))add('dpr_system_mismatch',9,'hardware','medium','medium');
  const renderer=String(mg.unmaskedRenderer||mg.renderer||'');if(/SwiftShader|llvmpipe|software/i.test(renderer))add('software_renderer',6,'plausibility','low','high');const wrtc=extension.privacy?.webRTCIPHandlingPolicy;if(wrtc?.available&&wrtc.value&&wrtc.value!=='default')add('webrtc_policy_nondefault',5,'privacy','low','high',wrtc.value);
  const categories={};let score=0;for(const [k,cap] of Object.entries(CATEGORY_CAPS)){categories[k]={raw:raw[k]||0,cap,score:Math.min(cap,raw[k]||0)};score+=categories[k].score;}score=Math.min(100,Math.round(score));signals.sort((a,b)=>b.weight-a.weight||a.id.localeCompare(b.id));
  const coverageChecks=[Boolean(main.navigator),Boolean(isolated.navigator),Boolean(extension.runtimePlatform),Boolean(extension.systemCpu),Boolean(extension.systemMemory),Array.isArray(extension.systemDisplays)&&extension.systemDisplays.length>=0,mc.length>=2,Boolean(mg.available),Object.keys(main.nativeIntegrity||{}).length>=3,Boolean(main.iframe),Boolean(main.worker)],available=coverageChecks.filter(Boolean).length,coverage={available,total:coverageChecks.length,percent:Math.round(available/coverageChecks.length*100)};
  return {available:true,score,verdict:score<15?'LOW':score<35?'REVIEW':score<60?'SUSPECTED':'HIGH_SUSPICION',suspected:score>=35,highSuspicion:score>=60,signalCount:signals.length,signals,categories,coverage};
}
async function stableHash(value){const text=JSON.stringify(value);try{const bytes=new TextEncoder().encode(text),digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('');}catch{let h=0x811c9dc5;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,0x01000193);}return (h>>>0).toString(16).padStart(8,'0');}}
async function deepEnvironmentProbe(chromeApi,tabId,{timeoutMs=5000}={}){
  const id=Number(tabId);if(!Number.isInteger(id))return {available:false,error:'deep_probe_tab_required'};if(!chromeApi?.scripting?.executeScript)return {available:false,error:'deep_probe_scripting_unavailable'};let tab;try{tab=await chromeApi.tabs.get(id);}catch{return {available:false,error:'deep_probe_tab_unavailable'};}if(!/^https?:/i.test(String(tab?.url||'')))return {available:false,error:'deep_probe_http_tab_required'};
  const work=(async()=>{const extPromise=extensionSignals(chromeApi),mainPromise=chromeApi.scripting.executeScript({target:{tabId:id},world:'MAIN',func:collectRealmSnapshot,args:[{fullContext:true,canvasRepeats:3,audioRepeats:1}]}),isoPromise=chromeApi.scripting.executeScript({target:{tabId:id},world:'ISOLATED',func:collectRealmSnapshot,args:[{fullContext:false,canvasRepeats:2,audioRepeats:1}]});const [mr,ir,ext]=await Promise.all([mainPromise,isoPromise,extPromise]),main=mr?.[0]?.result,isolated=ir?.[0]?.result;if(!main||!isolated)return {available:false,error:'deep_probe_realm_result_missing'};const analysis=analyzeDeepSnapshots(main,isolated,ext),stable={platform:main.navigator?.platform||null,languages:main.navigator?.languages||[],hardwareConcurrency:main.navigator?.hardwareConcurrency??null,deviceMemory:main.navigator?.deviceMemory??null,timeZone:main.intl?.timeZone||null,screen:main.screen?{width:main.screen.width,height:main.screen.height,devicePixelRatio:main.screen.devicePixelRatio}:null,webglRenderer:main.webgl?.primary?.unmaskedRenderer||main.webgl?.primary?.renderer||null,canvasHash:main.canvas?.samples?.[0]?.dataUrlHash||null,audioHash:main.audio?.primary?.hash||null,systemOs:ext.runtimePlatform?.os||null,systemCpuCount:ext.systemCpu?.numOfProcessors??null,systemMemoryCapacity:ext.systemMemory?.capacity??null};return {...analysis,stableHash:await stableHash(stable),privacy:{rawSamplesPersisted:false,rawWebRtcAddressCaptured:false,proxyModified:false,privacySettingsModified:false}};})();
  const bounded=Math.max(1000,Math.min(9000,Number(timeoutMs)||5000));return Promise.race([work,new Promise(resolve=>setTimeout(()=>resolve({available:false,error:'deep_probe_timeout'}),bounded))]).catch(error=>({available:false,error:String(error?.message||error)}));
}

module.exports={CATEGORY_CAPS,AUTOMATION_MARKERS,collectRealmSnapshot,extensionSignals,runtimeOsMatches,analyzeDeepSnapshots,deepEnvironmentProbe};
