'use strict';

const VIRTUAL_CURSOR_SCOPE = 'BODY_CHROME_ATTACH_CURSOR';
const MESSAGE_TYPES = Object.freeze({
  CDP_POINTER_EXPECTED: 'CDP_POINTER_EXPECTED',
  CDP_KEY_EXPECTED: 'CDP_KEY_EXPECTED',
  USER_MOTOR_EVENT: 'USER_MOTOR_EVENT',
  CURSOR_STATUS: 'CURSOR_STATUS'
});
const SOURCES = Object.freeze({ USER: 'USER', CDP: 'CDP' });

module.exports = { VIRTUAL_CURSOR_SCOPE, MESSAGE_TYPES, SOURCES };
